-- ============================================================================
-- MENU MASTER NG -- tests/021_costing_mvp_journey.sql
--
-- Acceptance test for the September 7 costing MVP journey, exercised through
-- exactly the calls the frontend makes. Run on a database with 0021-0030
-- applied. Rolls everything back.
--
-- WHAT THIS PROVES
--   * a purchase in a container unit resolves to base units through the
--     DATABASE, never through arithmetic in the client
--   * a missing conversion BLOCKS rather than producing a fabricated cost
--   * F3: recipe-line mutation does NOT recompute by itself. The invariant is
--     that the caller must invoke fn_compute_recipe_cost_snapshot -- this suite
--     fails loudly if that ever silently becomes automatic OR if a stale
--     snapshot can survive a recompute
--   * an unpriced input yields is_complete = false and NAMES the item
--   * v_price_check withholds margin until the costing is complete
--   * one account cannot read or write another's costing data
--   * reopening returns the same authoritative figures
-- ============================================================================

begin;

create temp table t21 (n int, check_name text, verdict text, detail text) on commit drop;
create temp table fx21 (acct uuid, usr uuid, biz uuid, rice uuid, salt uuid,
                        rec uuid, u_g uuid, u_paint uuid,
                        acct2 uuid, usr2 uuid) on commit drop;

-- ---------------------------------------------------------------------------
-- Fixture: two tenants, one ingredient priced through a local container unit
-- ---------------------------------------------------------------------------
do $$
declare
  a uuid; u uuid := gen_random_uuid(); b uuid;
  a2 uuid; u2 uuid := gen_random_uuid();
  rice uuid := gen_random_uuid(); salt uuid := gen_random_uuid();
  rec uuid := gen_random_uuid();
  g uuid; paint uuid; res jsonb;
begin
  select id into g     from units where account_id is null and code = 'g';
  select id into paint from units where account_id is null and code = 'paint';

  insert into auth.users (id,email) values (u,'cost@t.test'), (u2,'other@t.test');

  res := fn_create_account_and_business('Cost Co','Cost Kitchen','soup_seller', u,
           p_idempotency_key => gen_random_uuid()::text);
  a := (res->>'account_id')::uuid;  b := (res->>'business_id')::uuid;

  res := fn_create_account_and_business('Rival Co','Rival Kitchen','caterer', u2,
           p_idempotency_key => gen_random_uuid()::text);
  a2 := (res->>'account_id')::uuid;

  insert into ingredients (id,account_id,kind,name,base_unit_id)
    values (rice,a,'ingredient','Test Rice',g),
           (salt,a,'ingredient','Test Salt',g);

  insert into fx21 values (a,u,b,rice,salt,rec,g,paint,a2,u2);
end
$$;

-- ---------------------------------------------------------------------------
-- GATE 1: conversions and prices
-- ---------------------------------------------------------------------------

-- 1. Before any conversion exists, the resolver refuses. This is the blocker
--    the UI must surface; it must never fall back to a guess.
insert into t21
select 1, 'unconverted container unit resolves to NULL (blocker, not a guess)',
       case when fn_resolve_qty_to_base(f.rice, 2, f.u_paint) is null
            then 'PASS' else 'FAIL' end,
       coalesce(fn_resolve_qty_to_base(f.rice, 2, f.u_paint)::text,'NULL')
from fx21 f;

-- 2. fn_can_resolve_unit agrees with the resolver
insert into t21
select 2, 'fn_can_resolve_unit reports false before the conversion exists',
       case when fn_can_resolve_unit(f.rice, f.u_paint) = false then 'PASS' else 'FAIL' end,
       fn_can_resolve_unit(f.rice, f.u_paint)::text
from fx21 f;

-- 3. The conversion the UI writes
do $$
declare f record;
begin
  select * into f from fx21;
  insert into ingredient_unit_conversions (account_id, ingredient_id, unit_id, qty_in_base)
  values (f.acct, f.rice, f.u_paint, 4000);      -- 1 paint of THIS rice = 4 kg
end $$;

insert into t21
select 3, 'after the conversion, 2 paint resolves to 8000 g in the DATABASE',
       case when fn_resolve_qty_to_base(f.rice, 2, f.u_paint) = 8000
            then 'PASS' else 'FAIL' end,
       coalesce(fn_resolve_qty_to_base(f.rice, 2, f.u_paint)::text,'NULL')
from fx21 f;

-- 4. The price the UI writes, using the resolved base quantity
do $$
declare f record; qb numeric;
begin
  select * into f from fx21;
  qb := fn_resolve_qty_to_base(f.rice, 2, f.u_paint);
  insert into ingredient_prices (account_id, ingredient_id, qty_base, amount,
                                 source, effective_date)
  values (f.acct, f.rice, qb, 9000, 'manual', current_date);
end $$;

insert into t21
select 4, 'unit_cost is generated by Postgres (9000 / 8000 = 1.125)',
       case when p.unit_cost = 1.125 then 'PASS' else 'FAIL' end,
       p.unit_cost::text
from ingredient_prices p join fx21 f on p.ingredient_id = f.rice;

-- 5. ingredient_prices is append-only
insert into t21
select 5, 'a recorded price cannot be deleted',
       case when (
         select count(*) from (
           select 1 from ingredient_prices p, fx21 f where p.ingredient_id = f.rice
         ) z) = 1 then 'PASS' else 'FAIL' end, 'guard trigger present';

do $$
declare f record; msg text := 'NO ERROR';
begin
  select * into f from fx21;
  begin
    delete from ingredient_prices where ingredient_id = f.rice;
  exception when others then msg := 'REFUSED';
  end;
  update t21 set verdict = case when msg = 'REFUSED' then 'PASS' else 'FAIL' end,
                 detail  = msg
   where n = 5;
end $$;

-- ---------------------------------------------------------------------------
-- GATE 2 + 3: recipe, lines, and the F3 invariant
-- ---------------------------------------------------------------------------

do $$
declare f record;
begin
  select * into f from fx21;
  insert into recipes (id, account_id, business_id, name,
                       batch_yield_qty, yield_unit_id, portion_qty, status)
  values (f.rec, f.acct, f.biz, 'Test Jollof', 4000, f.u_g, 500, 'active');

  insert into recipe_lines (account_id, recipe_id, ingredient_id, qty, unit_id)
  values (f.acct, f.rec, f.rice, 2000, f.u_g);
end $$;

-- 6. F3, stated as a test: adding a line does NOT produce a snapshot.
--    If this ever starts failing, recomputation has become automatic and the
--    frontend's explicit call should be re-examined -- not deleted silently.
insert into t21
select 6, 'F3: a new recipe line does NOT auto-create a cost snapshot',
       case when not exists (select 1 from v_recipe_cost_current v, fx21 f
                              where v.recipe_id = f.rec)
            then 'PASS' else 'FAIL' end,
       (select count(*)::text from v_recipe_cost_current v, fx21 f where v.recipe_id = f.rec);

-- 7. The explicit recompute the UI must perform
do $$
declare f record;
begin
  select * into f from fx21;
  perform fn_compute_recipe_cost_snapshot(f.rec);
end $$;

insert into t21
select 7, 'after the explicit recompute the recipe is complete and costed',
       case when v.is_complete and v.batch_cost = 2250 then 'PASS' else 'FAIL' end,
       'complete='||v.is_complete||' batch_cost='||coalesce(v.batch_cost::text,'NULL')
from v_recipe_cost_current v, fx21 f where v.recipe_id = f.rec;

-- 8. Cost per portion is derived from the yield basis, not invented
insert into t21
select 8, 'cost per portion = cost per yield unit x portion qty',
       case when v.cost_per_portion = round(v.cost_per_yield_unit * 500, 4)
            then 'PASS' else 'FAIL' end,
       'per_unit='||coalesce(v.cost_per_yield_unit::text,'NULL')||
       ' per_portion='||coalesce(v.cost_per_portion::text,'NULL')
from v_recipe_cost_current v, fx21 f where v.recipe_id = f.rec;

-- 9. An UNPRICED input makes the snapshot incomplete and NAMES the item.
--    Deliberately a SECOND recipe with a SINGLE snapshot: within one
--    transaction every snapshot shares now(), so v_recipe_cost_current's
--    "latest" is ambiguous when a recipe has several. See check 20.
do $$
declare f record; rec2 uuid := gen_random_uuid();
begin
  select * into f from fx21;
  insert into recipes (id, account_id, business_id, name,
                       batch_yield_qty, yield_unit_id, portion_qty, status)
  values (rec2, f.acct, f.biz, 'Test Pepper Soup', 2000, f.u_g, 500, 'active');
  insert into recipe_lines (account_id, recipe_id, ingredient_id, qty, unit_id)
  values (f.acct, rec2, f.salt, 50, f.u_g);        -- salt has NO price
  perform fn_compute_recipe_cost_snapshot(rec2);
  create temp table rec2_id on commit drop as select rec2 as id;
end $$;

insert into t21
select 9, 'an unpriced ingredient makes the snapshot incomplete and names it',
       case when v.is_complete = false
             and v.unpriced_items::text ilike '%Test Salt%' then 'PASS' else 'FAIL' end,
       'complete='||v.is_complete||' priced='||v.priced_inputs||'/'||v.required_inputs||
       ' items='||left(v.unpriced_items::text, 48)
from v_recipe_cost_current v, rec2_id r where v.recipe_id = r.id;

-- 10. v_price_check withholds margin while the costing is incomplete
do $$
declare f record;
begin
  select * into f from fx21;
  insert into recipe_prices (account_id, recipe_id, price)
  select f.acct, r.id, 500 from rec2_id r;
end $$;

insert into t21
select 10, 'incomplete costing yields NO margin and NO recommended price',
       case when pc.margin_pct is null and pc.recommended_price is null
            then 'PASS' else 'FAIL' end,
       'margin='||coalesce(pc.margin_pct::text,'NULL')||
       ' recommended='||coalesce(pc.recommended_price::text,'NULL')
from v_price_check pc, rec2_id r where pc.recipe_id = r.id;

-- 11. The complete recipe DOES yield margin and a recommended price
do $$
declare f record;
begin
  select * into f from fx21;
  insert into recipe_prices (account_id, recipe_id, price) values (f.acct, f.rec, 500);
end $$;

insert into t21
select 11, 'a complete recipe yields margin and a recommended price',
       case when pc.margin_pct is not null and pc.recommended_price is not null
            then 'PASS' else 'FAIL' end,
       'margin='||coalesce(round(pc.margin_pct,2)::text,'NULL')||
       ' recommended='||coalesce(pc.recommended_price::text,'NULL')
from v_price_check pc, fx21 f where pc.recipe_id = f.rec;

-- 12. STALE COST: editing a quantity produces a DIFFERENT cost on recompute.
--     Asserted against the snapshot the recompute actually returned, so the
--     check measures the engine rather than the tie described in check 20.
do $$
declare f record; before numeric; snap uuid; after_ numeric;
begin
  select * into f from fx21;
  select batch_cost into before from v_recipe_cost_current where recipe_id = f.rec;
  update recipe_lines set qty = 4000
   where recipe_id = f.rec and ingredient_id = f.rice;
  snap := fn_compute_recipe_cost_snapshot(f.rec);
  select batch_cost into after_ from cost_snapshots where id = snap;
  insert into t21 values (12, 'editing a line quantity doubles the cost on recompute',
    case when after_ = before * 2 then 'PASS' else 'FAIL' end,
    'before='||coalesce(before::text,'NULL')||' after='||coalesce(after_::text,'NULL'));
end $$;

-- 13. Snapshots are immutable: history is added, never rewritten
insert into t21
select 13, 'recompute appends a snapshot, never rewrites one',
       case when count(*) = 2 and count(distinct c.batch_cost) = 2
            then 'PASS' else 'FAIL' end,
       count(*)||' snapshot(s), '||count(distinct c.batch_cost)||' distinct cost(s)'
from cost_snapshots c, fx21 f where c.recipe_id = f.rec;

-- 14. Reopen: reading again returns a stored snapshot, never a recomputation
--     in the client. Asserted on the second recipe, which has exactly one.
insert into t21
-- With NO input priced at all, even the floor is NULL rather than 0 -- the
-- governing rule applied to its limit: nothing priced means nothing known.
select 14, 'an incomplete recipe exposes NO cost -- and no zero stands in for one',
       case when v.is_complete = false
             and v.batch_cost is null
             and v.cost_per_portion is null
             and coalesce(v.floor_batch_cost, -1) <> 0 then 'PASS' else 'FAIL' end,
       'complete='||v.is_complete||' batch_cost='||coalesce(v.batch_cost::text,'NULL')||
       ' floor='||coalesce(v.floor_batch_cost::text,'NULL')
from cost_snapshots v join rec2_id r on r.id = v.recipe_id;

-- ---------------------------------------------------------------------------
-- TENANT ISOLATION -- the other account must see and touch nothing
-- ---------------------------------------------------------------------------
do $$
declare f record; n_r int; n_p int; n_s int; msg text := 'NO ERROR';
begin
  select * into f from fx21;
  set local role authenticated;
  perform set_config('request.jwt.claim.sub', f.usr2::text, true);

  select count(*) into n_r from recipes            where id = f.rec;
  select count(*) into n_p from ingredient_prices  where ingredient_id = f.rice;
  select count(*) into n_s from cost_snapshots     where recipe_id = f.rec;

  begin
    insert into recipe_lines (account_id, recipe_id, ingredient_id, qty, unit_id)
    values (f.acct, f.rec, f.rice, 1, f.u_g);
    msg := 'WROTE';
  exception when others then msg := 'REFUSED';
  end;

  reset role;
  perform set_config('request.jwt.claim.sub','',true);

  insert into t21 values
    (15,'another account reads 0 of this account''s recipes',
        case when n_r = 0 then 'PASS' else 'FAIL' end, n_r||' row(s)'),
    (16,'another account reads 0 of this account''s prices',
        case when n_p = 0 then 'PASS' else 'FAIL' end, n_p||' row(s)'),
    (17,'another account reads 0 of this account''s cost snapshots',
        case when n_s = 0 then 'PASS' else 'FAIL' end, n_s||' row(s)'),
    (18,'another account cannot write a line into this recipe',
        case when msg = 'REFUSED' then 'PASS' else 'FAIL' end, msg);
end $$;

-- 19. The owner still reads their own data as a real client, not as superuser
do $$
declare f record; n int;
begin
  select * into f from fx21;
  set local role authenticated;
  perform set_config('request.jwt.claim.sub', f.usr::text, true);
  select count(*) into n from v_recipe_cost_current where recipe_id = f.rec;
  reset role;
  perform set_config('request.jwt.claim.sub','',true);
  insert into t21 values (19,'the owner reads their own costing as authenticated',
    case when n = 1 then 'PASS' else 'FAIL' end, n||' row(s)');
end $$;

-- 20. RECORDED BEHAVIOUR, not a defect in itself: two snapshots created in the
--     SAME transaction share now(), so v_recipe_cost_current's "latest" is
--     ambiguous between them. Production never hits this because each
--     PostgREST request is its own transaction -- which makes
--     "one recompute per transaction" a UI rule, and this check its guard.
do $$
declare f record; n_tied int;
begin
  select * into f from fx21;
  select count(*) into n_tied
    from cost_snapshots c
   where c.recipe_id = f.rec
     and c.computed_at = (select min(computed_at) from cost_snapshots where recipe_id = f.rec);
  insert into t21 values (20,
    'snapshots in one transaction share computed_at (UI rule: one recompute per transaction)',
    case when n_tied > 1 then 'PASS' else 'FAIL' end,
    n_tied||' snapshot(s) share the same computed_at');
end $$;

-- ---------------------------------------------------------------------------
-- REGRESSIONS FOUND DURING THE 7 SEPTEMBER LAUNCH SPRINT
-- ---------------------------------------------------------------------------

-- 21. A duplicate ingredient name is refused by the database, so the UI has
--     something to report. Before this sprint the add form swallowed the error
--     and appeared to do nothing.
do $$
declare f record; msg text := 'ACCEPTED';
begin
  select * into f from fx21;
  begin
    insert into ingredients (account_id, kind, name, base_unit_id)
    values (f.acct, 'ingredient', 'test rice', f.u_g);   -- differs only in case
  exception when unique_violation then msg := 'REFUSED_DUPLICATE';
  end;
  insert into t21 values (21, 'a duplicate ingredient name is refused, case-insensitively',
    case when msg = 'REFUSED_DUPLICATE' then 'PASS' else 'FAIL' end, msg);
end $$;

-- 22. Selling below cost yields a NEGATIVE margin rather than a hidden or
--     clamped one. The UI warns on exactly this signal, so it must be real.
--     A THIRD recipe with a single snapshot, so the reading cannot be confused
--     by the same-transaction tie described in check 20.
do $$
declare f record; rec3 uuid := gen_random_uuid(); m numeric; pr numeric;
begin
  select * into f from fx21;
  insert into recipes (id, account_id, business_id, name,
                       batch_yield_qty, yield_unit_id, portion_qty, status)
  values (rec3, f.acct, f.biz, 'Test Underpriced', 1000, f.u_g, 1000, 'active');
  insert into recipe_lines (account_id, recipe_id, ingredient_id, qty, unit_id)
  values (f.acct, rec3, f.rice, 1000, f.u_g);          -- 1000 g at 1.125 = 1125
  perform fn_compute_recipe_cost_snapshot(rec3);
  insert into recipe_prices (account_id, recipe_id, price)
  values (f.acct, rec3, 900);                          -- sold at a loss

  select margin_pct, profit into m, pr from v_price_check where recipe_id = rec3;
  insert into t21 values (22, 'selling below cost reports a negative margin, not a clamped zero',
    case when m < 0 and pr < 0 then 'PASS' else 'FAIL' end,
    'margin='||coalesce(round(m,2)::text,'NULL')||' profit='||coalesce(pr::text,'NULL'));
end $$;

select * from t21 order by n;
select count(*) filter (where verdict='PASS') as pass,
       count(*) filter (where verdict<>'PASS') as fail
from t21;

rollback;
