-- ============================================================================
-- MENU MASTER NG
-- 0037: make "the latest cost snapshot" deterministic
--
-- Requires: 0001-0036 applied.
--
-- THE DEFECT (P1, financial)
--   Every view that resolves a recipe's current cost does
--       distinct on (recipe_id) ... order by recipe_id, computed_at desc
--   and computed_at defaults to now(), which in PostgreSQL is TRANSACTION
--   START. Two snapshots written for the same recipe inside one transaction
--   therefore carry an IDENTICAL timestamp, the ordering is a tie, and which
--   row wins is arbitrary.
--
--   Proven on the replica: a recipe costed at N850/portion, then given an
--   unpriced ingredient and recomputed in the same transaction, still reported
--   is_complete = true, a N650 profit and a 43.33% margin -- profit and margin
--   for a recipe whose cost the engine had just refused to compute. That is a
--   silent financial fallback of exactly the kind this product forbids.
--
--   It is reachable in normal use, not only in tests. fn_post_purchase writes
--   one ingredient_prices row per line inside a single transaction, and
--   ingredient_prices carries a recompute trigger (0008). A market run buying
--   two ingredients that appear in the same recipe recomputes that recipe
--   twice in one transaction and ties.
--
-- SECURITY_INVOKER IS RESTATED ON EVERY VIEW BELOW, DELIBERATELY.
--   CREATE OR REPLACE VIEW does not preserve reloptions. Omitting
--   `with (security_invoker = on)` silently RESETS it and the view then runs
--   with the definer's rights, reading across tenants. An earlier draft of
--   this migration did exactly that on all four views; tests/023 caught the
--   cross-tenant read. A definition fingerprint does NOT detect it, because
--   pg_views.definition excludes reloptions -- which is why the self-check
--   below asserts the option itself on every view touched.
--
-- THE FIX
--   cost_snapshots gains an identity column, seq, which is monotonic within
--   and across transactions. Every "latest" ordering becomes
--       order by ... computed_at desc, seq desc
--   so the newest row always wins and the result is deterministic.
--
--   Additive and non-destructive: no snapshot is altered or deleted, and the
--   costing arithmetic is untouched. Rows written before this migration are
--   assigned seq values in whatever order the table is scanned; for those,
--   computed_at remains the primary ordering exactly as before, so their
--   relative order is unchanged except where they already tied -- and where
--   they tied, no correct order existed to preserve.
-- ============================================================================

do $$
begin
  if not exists (select 1 from pg_class where relname = 'cost_snapshots') then
    raise exception '0037 preflight FAILED: cost_snapshots is missing.';
  end if;
  if exists (select 1 from information_schema.columns
              where table_name = 'cost_snapshots' and column_name = 'seq') then
    raise exception '0037 preflight FAILED: cost_snapshots.seq already exists.';
  end if;
  if not exists (select 1 from information_schema.columns
                  where table_name = 'v_price_check' and column_name = 'markup_pct') then
    raise exception '0037 preflight FAILED: 0036 must be applied first.';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public') <> 116 then
    raise exception '0037 preflight FAILED: policy count is %, expected 116.',
      (select count(*) from pg_policies where schemaname = 'public');
  end if;
end
$$;

alter table cost_snapshots
  add column seq bigint generated by default as identity;

comment on column cost_snapshots.seq is
  'Monotonic tie-breaker. computed_at is now(), which is transaction start, so '
  'two snapshots written in one transaction share a timestamp; seq makes '
  '"latest" deterministic. Never used in any cost calculation.';

create or replace view v_recipe_cost_current with (security_invoker = on) as
 SELECT DISTINCT ON (recipe_id) id,
    account_id,
    business_id,
    recipe_id,
    computed_at,
    costing_method,
    wavg_window_days,
    is_complete,
    required_inputs,
    priced_inputs,
    excluded_inputs,
    unpriced_items,
    ingredient_cost,
    packaging_cost,
    labour_cost,
    overhead_cost,
    batch_cost,
    cost_per_yield_unit,
    cost_per_portion,
    created_by
   FROM cost_snapshots
  ORDER BY recipe_id, computed_at DESC, seq DESC;

create or replace view v_price_check with (security_invoker = on) as
 WITH recipe_latest AS (
         SELECT DISTINCT ON (cost_snapshots.recipe_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion,
            cost_snapshots.variant_id,
            cost_snapshots.resolved_qty,
            cost_snapshots.resolved_unit_id,
            cost_snapshots.basis_used,
            cost_snapshots.format_packaging_cost
           FROM cost_snapshots
          WHERE cost_snapshots.variant_id IS NULL
          ORDER BY cost_snapshots.recipe_id, cost_snapshots.computed_at DESC, cost_snapshots.seq DESC
        ), variant_latest AS (
         SELECT DISTINCT ON (cost_snapshots.variant_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion,
            cost_snapshots.variant_id,
            cost_snapshots.resolved_qty,
            cost_snapshots.resolved_unit_id,
            cost_snapshots.basis_used,
            cost_snapshots.format_packaging_cost
           FROM cost_snapshots
          WHERE cost_snapshots.variant_id IS NOT NULL
          ORDER BY cost_snapshots.variant_id, cost_snapshots.computed_at DESC, cost_snapshots.seq DESC
        ), rows AS (
         SELECT r.id AS recipe_id,
            r.business_id,
            r.account_id,
            r.name,
            rv.id AS variant_id,
            f.name AS format_name,
            vl.resolved_qty,
            COALESCE(vl.is_complete, false) AS is_complete,
            vl.required_inputs,
            vl.priced_inputs,
            vl.excluded_inputs,
            COALESCE(vl.unpriced_items, '[]'::jsonb) AS unpriced_items,
            vl.floor_cost_per_portion,
            vl.cost_per_portion
           FROM recipes r
             JOIN recipe_variants rv ON rv.recipe_id = r.id AND rv.is_active
             JOIN serving_formats f ON f.id = rv.format_id
             LEFT JOIN variant_latest vl ON vl.variant_id = rv.id
          WHERE r.kind = 'dish'::recipe_kind AND r.deleted_at IS NULL
        UNION ALL
         SELECT r.id,
            r.business_id,
            r.account_id,
            r.name,
            NULL::uuid AS uuid,
            NULL::text AS text,
            NULL::numeric AS "numeric",
            COALESCE(rl.is_complete, false) AS "coalesce",
            rl.required_inputs,
            rl.priced_inputs,
            rl.excluded_inputs,
            COALESCE(rl.unpriced_items, '[]'::jsonb) AS "coalesce",
            rl.floor_cost_per_portion,
            rl.cost_per_portion
           FROM recipes r
             LEFT JOIN recipe_latest rl ON rl.recipe_id = r.id
          WHERE r.kind = 'dish'::recipe_kind AND r.deleted_at IS NULL AND NOT (EXISTS ( SELECT 1
                   FROM recipe_variants rv
                  WHERE rv.recipe_id = r.id AND rv.is_active))
        )
 SELECT x.recipe_id,
    x.business_id,
    x.account_id,
    x.name,
    ch.id AS channel_id,
    ch.name AS channel_name,
    x.is_complete,
    x.required_inputs,
    x.priced_inputs,
    x.excluded_inputs,
    x.unpriced_items,
    x.floor_cost_per_portion AS cost_floor_per_portion,
    x.cost_per_portion,
    p.price AS selling_price,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL THEN round(p.price - x.cost_per_portion, 2)
            ELSE NULL::numeric
        END AS profit,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL AND p.price > 0::numeric THEN round(100.0 * (p.price - x.cost_per_portion) / p.price, 2)
            ELSE NULL::numeric
        END AS margin_pct,
        CASE
            WHEN x.is_complete AND x.cost_per_portion IS NOT NULL AND COALESCE(ch.target_margin, bs.default_target_margin) < 100::numeric THEN ceil(x.cost_per_portion / (1::numeric - COALESCE(ch.target_margin, bs.default_target_margin) / 100.0) / bs.price_rounding_to) * bs.price_rounding_to
            ELSE NULL::numeric
        END AS recommended_price,
    COALESCE(ch.target_margin, bs.default_target_margin) AS target_margin,
    bs.price_rounding_to,
    ch.commission_pct,
    x.variant_id,
    x.format_name,
    x.resolved_qty,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL AND x.cost_per_portion > 0::numeric THEN round(100.0 * (p.price - x.cost_per_portion) / x.cost_per_portion, 2)
            ELSE NULL::numeric
        END AS markup_pct
   FROM rows x
     JOIN business_settings bs ON bs.business_id = x.business_id
     LEFT JOIN channels ch ON ch.business_id = x.business_id AND ch.is_active
     LEFT JOIN LATERAL ( SELECT rp.price
           FROM recipe_prices rp
          WHERE rp.recipe_id = x.recipe_id AND (rp.channel_id IS NULL OR rp.channel_id = ch.id) AND (rp.variant_id IS NULL OR rp.variant_id = x.variant_id) AND rp.effective_from <= CURRENT_DATE
          ORDER BY (rp.variant_id IS NOT NULL) DESC, rp.effective_from DESC, rp.created_at DESC
         LIMIT 1) p ON true;

create or replace view v_costing_blockers with (security_invoker = on) as
 WITH latest AS (
         SELECT DISTINCT ON (cost_snapshots.recipe_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion
           FROM cost_snapshots
          ORDER BY cost_snapshots.recipe_id, cost_snapshots.computed_at DESC, cost_snapshots.seq DESC
        )
 SELECT r.account_id,
    r.business_id,
    r.id AS recipe_id,
    r.name,
    s.required_inputs,
    s.priced_inputs,
    s.excluded_inputs,
    item.value ->> 'problem'::text AS problem,
    item.value ->> 'ingredient_name'::text AS ingredient_name,
    item.value ->> 'unit'::text AS unit_code,
    item.value AS item
   FROM recipes r
     JOIN latest s ON s.recipe_id = r.id
     CROSS JOIN LATERAL jsonb_array_elements(s.unpriced_items) item(value)
  WHERE NOT s.is_complete AND r.deleted_at IS NULL;

create or replace view v_gate2_cutover with (security_invoker = on) as
 WITH latest AS (
         SELECT DISTINCT ON (cost_snapshots.recipe_id) cost_snapshots.recipe_id,
            cost_snapshots.cost_per_portion,
            cost_snapshots.computed_at,
            cost_snapshots.is_complete
           FROM cost_snapshots
          ORDER BY cost_snapshots.recipe_id, cost_snapshots.computed_at DESC, cost_snapshots.seq DESC
        )
 SELECT rv.account_id,
    rv.business_id,
    rv.id AS variant_id,
    r.id AS recipe_id,
    r.name AS recipe_name,
    f.name AS format_name,
    rv.costing_basis,
    r.portion_qty AS legacy_portion_qty,
    fn_variant_resolved_qty(rv.id) AS resolved_qty,
    s.cost_per_portion AS legacy_cost_per_portion,
    fn_variant_cost(rv.id) AS variant_cost,
    pk.pack_cost AS format_packaging_cost,
    fn_variant_problem(rv.id) AS problem,
    bs.overhead_enabled,
        CASE
            WHEN s.cost_per_portion IS NULL AND fn_variant_cost(rv.id) IS NULL THEN 'BOTH INCOMPLETE'::text
            WHEN s.cost_per_portion IS NULL OR fn_variant_cost(rv.id) IS NULL THEN 'ONE SIDE INCOMPLETE'::text
            WHEN abs(s.cost_per_portion - (fn_variant_cost(rv.id) - pk.pack_cost)) <= 0.000001 THEN
            CASE
                WHEN pk.pack_cost > 0::numeric THEN 'MATCH -- plus new format packaging'::text
                ELSE 'MATCH'::text
            END
            WHEN bs.overhead_enabled THEN 'DIFFERS -- OVERHEAD METHODOLOGY CHANGED BY 0023 (expected)'::text
            ELSE 'MISMATCH'::text
        END AS verdict
   FROM recipe_variants rv
     JOIN recipes r ON r.id = rv.recipe_id
     JOIN serving_formats f ON f.id = rv.format_id
     JOIN business_settings bs ON bs.business_id = rv.business_id
     LEFT JOIN latest s ON s.recipe_id = r.id
     CROSS JOIN LATERAL ( SELECT COALESCE(sum(spk.qty * fn_ingredient_usable_unit_cost(spk.packaging_item_id, rv.business_id)), 0::numeric) AS pack_cost
           FROM serving_format_packaging spk
          WHERE spk.format_id = rv.format_id AND spk.is_cost_bearing) pk
  WHERE r.deleted_at IS NULL;

do $$
declare v_pol int; v_bad int; v_unsafe text;
begin
  if not exists (select 1 from information_schema.columns
                  where table_name = 'cost_snapshots' and column_name = 'seq') then
    raise exception '0037 self-check FAILED: seq was not added.';
  end if;

  select count(*) into v_bad from pg_views
   where schemaname = 'public'
     and viewname in ('v_recipe_cost_current','v_price_check','v_costing_blockers','v_gate2_cutover')
     and definition ~ 'computed_at DESC'
     and definition !~ 'computed_at DESC, [a-z_]*\.?seq DESC';
  if v_bad > 0 then
    raise exception '0037 self-check FAILED: % view(s) still order on computed_at alone.', v_bad;
  end if;

  -- The option, not the definition. A replaced view silently loses it.
  select string_agg(c.relname, ', ') into v_unsafe
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public'
     and c.relname in ('v_recipe_cost_current','v_price_check','v_costing_blockers','v_gate2_cutover')
     and not coalesce('security_invoker=on' = any(c.reloptions), false);
  if v_unsafe is not null then
    raise exception '0037 self-check FAILED: % lost security_invoker and would read across tenants.', v_unsafe;
  end if;

  if not exists (select 1 from information_schema.columns
                  where table_name = 'v_price_check' and column_name = 'markup_pct') then
    raise exception '0037 self-check FAILED: markup_pct was lost rebuilding v_price_check.';
  end if;

  select count(*) into v_pol from pg_policies where schemaname = 'public';
  if v_pol <> 116 then
    raise exception '0037 self-check FAILED: policy count moved to %.', v_pol;
  end if;

  raise notice '0037 OK: seq added, 4 views deterministic and security_invoker, 116 policies unchanged.';
end
$$;
