-- ============================================================================
-- MENU MASTER NG — Part 5 of 5: Gate 1 closure
--
-- DISPOSABLE / NON-PRODUCTION PROJECT ONLY.
-- Generated by scripts/build_deploy_chain.sh. Do not edit by hand.
-- Source migrations: 0013_reject_zero_value_amounts.sql 0014_sales_void_and_reissue.sql 0015_write_side_role_enforcement.sql 0016_role_function_permissions.sql 0017_subscription_state_integrity.sql
--
-- Zero-value rejection, void-and-reissue, write-side role enforcement, role function permissions, subscription state integrity.
-- ============================================================================

-- ---------------------------------------------------------------- 0013_reject_zero_value_amounts.sql
-- ============================================================================
-- MENU MASTER NG
-- 0013: reject zero-value acquisition amounts
--
-- GATE 1 CLOSURE, item A3.
--
-- THE DEFECT
--   0001 declared `check (amount >= 0)` on both purchase_lines and
--   ingredient_prices. ingredient_prices.unit_cost is
--   `generated always as (amount / qty_base) stored`, so a zero amount
--   produces a REAL unit cost of 0.000000. The completeness gate then counts
--   that ingredient as priced, and a fabricated zero flows into batch cost,
--   cost per portion, margin and recommended price.
--
--   That is precisely the failure the governing rule forbids:
--     A missing price is NULL. It is never zero.
--   A zero is worse than a missing price, because NULL is visibly incomplete
--   while 0.00 looks like an answer.
--
-- SCOPE
--   Both tables are tightened in this one migration because they are two ends
--   of a single write path: fn_post_purchase copies purchase_lines.amount
--   straight into ingredient_prices.amount. Closing one and leaving the other
--   open would leave the manual-price route wide open. Same invariant, same
--   migration.
--
-- OUT OF SCOPE (deliberate, per founder ruling C2)
--   Gifted, free, transferred, sampled and owner-supplied stock are NOT
--   modelled here. When they are needed they must be represented as their own
--   acquisition mechanism with their own cost semantics, never as a purchase
--   that happened to cost nothing. A zero-value purchase is not a cheap
--   purchase; it is an unpriced one wearing a price.
--
-- ADDITIVE. No earlier migration is rewritten. Idempotent.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. PRE-FLIGHT ASSERTION
--
-- Fail loudly rather than silently coercing. If real zero-value rows already
-- exist, the owner must decide what they meant before we harden the rule --
-- deleting or rewriting their data to make a constraint fit would be exactly
-- the kind of silent mutation this system exists to prevent.
-- ----------------------------------------------------------------------------

do $$
declare
  v_pl integer;
  v_ip integer;
begin
  select count(*) into v_pl from purchase_lines    where amount <= 0;
  select count(*) into v_ip from ingredient_prices where amount <= 0;

  if v_pl > 0 or v_ip > 0 then
    raise exception using
      errcode = 'check_violation',
      message = format(
        'Cannot apply 0013: %s purchase_lines and %s ingredient_prices rows have amount <= 0',
        v_pl, v_ip),
      hint = 'Reverse the offending purchases, or correct the amounts, then re-run. '
             'This migration will not delete or rewrite financial history.';
  end if;
end
$$;

-- ----------------------------------------------------------------------------
-- 2. TIGHTEN THE CONSTRAINTS
--
-- The 0001 constraints are inline and therefore auto-named by Postgres:
--   purchase_lines_amount_check, ingredient_prices_amount_check
-- They are replaced with explicitly named constraints so future migrations
-- can reference them without guessing.
-- ----------------------------------------------------------------------------

alter table purchase_lines    drop constraint if exists purchase_lines_amount_check;
alter table ingredient_prices drop constraint if exists ingredient_prices_amount_check;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'ck_purchase_lines_amount_positive') then
    alter table purchase_lines
      add constraint ck_purchase_lines_amount_positive check (amount > 0);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'ck_ingredient_prices_amount_positive') then
    alter table ingredient_prices
      add constraint ck_ingredient_prices_amount_positive check (amount > 0);
  end if;
end
$$;

comment on constraint ck_purchase_lines_amount_positive on purchase_lines is
  'A purchase line must carry a real price. Zero is not a cheap purchase, it is '
  'an unpriced one. Free or gifted stock needs its own acquisition mechanism.';

comment on constraint ck_ingredient_prices_amount_positive on ingredient_prices is
  'Closes the manual-price route to the same fabricated-zero defect. A price row '
  'exists only because a real amount was paid.';

-- ----------------------------------------------------------------------------
-- 3. DEFENCE IN DEPTH IN fn_post_purchase
--
-- The constraint above already makes a zero line unstorable, so this branch is
-- unreachable while the constraint stands. It is here because a future
-- migration that relaxes or drops the constraint must not silently re-open the
-- posting path. Reported in the same structured shape as the existing
-- unresolved_conversions blocker so the UI needs no new error handling.
--
-- This body is 0012's authorization-hardened version with the zero-value
-- blocker added. Every guard from 0012 is preserved verbatim:
--   - row lock via SELECT ... FOR UPDATE
--   - fn_require_account_role(owner, manager) on the account derived from the
--     purchase row itself, never from a caller-supplied id
-- ----------------------------------------------------------------------------

create or replace function fn_post_purchase(p_purchase_id uuid)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_p purchases%rowtype; v_blockers jsonb; v_zero jsonb; v_lines integer;
  v_written integer := 0; r record; v_base numeric;
begin
  select * into v_p from purchases where id = p_purchase_id for update;
  if not found then raise exception 'Purchase % not found', p_purchase_id; end if;

  perform fn_require_account_role(v_p.account_id,
    array['owner','manager']::member_role[], 'posting purchases');   -- AUTHORIZATION

  if v_p.status <> 'draft' then
    raise exception 'Purchase % is already %', p_purchase_id, v_p.status
      using errcode='check_violation';
  end if;

  select count(*) into v_lines from purchase_lines where purchase_id = p_purchase_id;
  if v_lines = 0 then
    raise exception 'Purchase % has no lines', p_purchase_id using errcode='check_violation';
  end if;

  -- 0013: refuse rather than record a fabricated zero cost.
  select coalesce(jsonb_agg(jsonb_build_object(
           'purchase_line_id', pl.id,
           'ingredient_id',    pl.ingredient_id,
           'ingredient_name',  i.name,
           'amount',           pl.amount,
           'problem',          'zero_value_line')), '[]'::jsonb)
    into v_zero
  from purchase_lines pl
  join ingredients i on i.id = pl.ingredient_id
  where pl.purchase_id = p_purchase_id
    and pl.amount <= 0;

  if jsonb_array_length(v_zero) > 0 then
    return jsonb_build_object('posted', false,
      'reason', 'zero_value_lines', 'blockers', v_zero);
  end if;

  v_blockers := fn_purchase_blockers(p_purchase_id);
  if jsonb_array_length(v_blockers) > 0 then
    return jsonb_build_object('posted', false,
      'reason', 'unresolved_conversions', 'blockers', v_blockers);
  end if;

  for r in select * from purchase_lines where purchase_id = p_purchase_id loop
    v_base := fn_resolve_qty_to_base(r.ingredient_id, r.qty, r.unit_id);
    if v_base is null or v_base <= 0 then
      raise exception 'Line % did not resolve. Refusing to post.', r.id
        using errcode='check_violation';
    end if;
    update purchase_lines set qty_base = v_base where id = r.id;
    insert into ingredient_prices (
      account_id, ingredient_id, supplier_id, purchase_line_id,
      qty_base, amount, source, effective_date, entered_by)
    values (v_p.account_id, r.ingredient_id, v_p.supplier_id, r.id,
      v_base, r.amount, 'purchase', v_p.purchase_date, auth.uid());
    v_written := v_written + 1;
  end loop;

  update purchases set status='posted', posted_at=now(), posted_by=auth.uid()
   where id = p_purchase_id;

  return jsonb_build_object('posted', true,
    'purchase_id', p_purchase_id, 'price_rows_written', v_written);
end;
$$;

-- ---------------------------------------------------------------- 0014_sales_void_and_reissue.sql
-- ============================================================================
-- MENU MASTER NG
-- 0014: sales void-and-reissue, and revenue immutability
--
-- GATE 1 CLOSURE, item A2.
--
-- THE DEFECT
--   fn_guard_frozen_cost (0009) protects cost_snapshot_id and
--   unit_cost_at_sale, and nothing else. order_lines.unit_price, qty and
--   recipe_id stayed freely editable after a sale, and lines could be inserted
--   or deleted at will. COGS was frozen; revenue was not. Historical gross
--   profit could therefore be rewritten after the fact, which defeats the
--   entire purpose of freezing cost in the first place.
--
-- THE RULE (founder ruling C3)
--   Corrections are void-and-reissue. The original sale is preserved, its
--   reversal is recorded with a reason and an actor, and a corrected
--   replacement is issued. History is never silently rewritten.
--
-- WHY NO NEW ENUM VALUE
--   Adding 'voided' to order_status would need ALTER TYPE ... ADD VALUE, which
--   Postgres refuses to use in the transaction that created it -- the exact
--   hazard that forces 0002 to run alone. Lifecycle is carried on explicit
--   columns instead. This also keeps 'voided' distinct from the existing
--   'cancelled', which means something different: cancelled = the order never
--   happened; voided = a recognised sale was later reversed.
--
-- WHY FINALISATION IS OPT-IN
--   Orders default to status 'confirmed' and the recovered baseline suites
--   create orders and then add lines to them. Making finalisation automatic
--   would block those inserts and regress the verified 80/80 baseline, which
--   is not permitted. finalised_at therefore defaults to NULL and the
--   immutability guards engage only once fn_finalise_order is called.
--   sales_entries have no draft stage and are immutable from insert.
--   See docs/GATE1_CLOSURE_REPORT.md for the residual this leaves.
--
-- ADDITIVE. No earlier migration is rewritten. Idempotent.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. KEYS AND COLUMNS
-- ----------------------------------------------------------------------------

-- sales_entries was not in 0004's composite-key list, so it needs the
-- (id, account_id) key before a same-account self reference can be enforced.
do $$
begin
  if not exists (select 1 from pg_constraint where conname='ux_sales_entries_id_account') then
    alter table sales_entries add constraint ux_sales_entries_id_account unique (id, account_id);
  end if;
end $$;

alter table orders
  add column if not exists finalised_at timestamptz,
  add column if not exists finalised_by uuid references auth.users(id) on delete set null,
  add column if not exists voided_at    timestamptz,
  add column if not exists voided_by    uuid references auth.users(id) on delete set null,
  add column if not exists void_reason  text,
  add column if not exists replaces     uuid;

alter table sales_entries
  add column if not exists voided_at   timestamptz,
  add column if not exists voided_by   uuid references auth.users(id) on delete set null,
  add column if not exists void_reason text,
  add column if not exists replaces    uuid;

-- Cross-account containment, same discipline as 0004's 37 composite keys.
do $$
begin
  if not exists (select 1 from pg_constraint where conname='fk_orders_replaces_account') then
    alter table orders add constraint fk_orders_replaces_account
      foreign key (replaces, account_id) references orders (id, account_id);
  end if;
  if not exists (select 1 from pg_constraint where conname='fk_sales_entries_replaces_account') then
    alter table sales_entries add constraint fk_sales_entries_replaces_account
      foreign key (replaces, account_id) references sales_entries (id, account_id);
  end if;
end $$;

comment on column orders.finalised_at is
  'Once set, revenue on this order is immutable. Corrections go through '
  'fn_void_order + fn_reissue_order, never through an UPDATE.';
comment on column orders.replaces is
  'For a reissued order: the voided order it corrects.';

create index if not exists ix_orders_open      on orders (business_id) where voided_at is null;
create index if not exists ix_sales_entries_open on sales_entries (business_id, sale_date) where voided_at is null;

-- ----------------------------------------------------------------------------
-- 2. LIFECYCLE FUNCTIONS
--
-- Authorization follows the 0012 rule without exception: the owning account is
-- derived from the target row's own relational chain, never from a parameter
-- the caller supplied.
-- ----------------------------------------------------------------------------

-- Finalising is a sales-desk act: owner, manager or sales.
create or replace function fn_finalise_order(p_order_id uuid)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_o orders%rowtype; v_lines integer;
begin
  select * into v_o from orders where id = p_order_id for update;
  if not found then raise exception 'Order % not found', p_order_id; end if;

  perform fn_require_account_role(v_o.account_id,
    array['owner','manager','sales']::member_role[], 'finalising orders');

  if v_o.voided_at is not null then
    raise exception 'Order % is voided and cannot be finalised', p_order_id
      using errcode='check_violation';
  end if;
  if v_o.finalised_at is not null then
    raise exception 'Order % is already finalised', p_order_id
      using errcode='check_violation';
  end if;

  select count(*) into v_lines from order_lines where order_id = p_order_id;
  if v_lines = 0 then
    raise exception 'Order % has no lines', p_order_id using errcode='check_violation';
  end if;

  update orders set finalised_at = now(), finalised_by = auth.uid() where id = p_order_id;

  return jsonb_build_object('finalised', true, 'order_id', p_order_id, 'lines', v_lines);
end;
$$;

-- Voiding reverses recognised revenue. Owner or manager only, matching
-- fn_reverse_purchase. Accountant is deliberately excluded here: founder ruling
-- C3 forbids the accountant rewriting finalised historical sales.
create or replace function fn_void_order(p_order_id uuid, p_reason text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_o orders%rowtype;
begin
  select * into v_o from orders where id = p_order_id for update;
  if not found then raise exception 'Order % not found', p_order_id; end if;

  perform fn_require_account_role(v_o.account_id,
    array['owner','manager']::member_role[], 'voiding sales');

  if v_o.finalised_at is null then
    raise exception 'Only a finalised order can be voided. Delete the draft instead.'
      using errcode='check_violation';
  end if;
  if v_o.voided_at is not null then
    raise exception 'Order % is already voided', p_order_id using errcode='check_violation';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A void requires a reason' using errcode='check_violation';
  end if;

  update orders
     set voided_at = now(), voided_by = auth.uid(), void_reason = btrim(p_reason)
   where id = p_order_id;

  return jsonb_build_object('voided', true, 'order_id', p_order_id, 'reason', btrim(p_reason));
end;
$$;

-- The replacement is created EMPTY on purpose. Copying the lines would carry
-- the mistake forward; the corrected figures must be entered deliberately.
create or replace function fn_reissue_order(p_voided_order_id uuid)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_o orders%rowtype; v_new uuid; v_no text; v_n integer := 1;
begin
  select * into v_o from orders where id = p_voided_order_id for update;
  if not found then raise exception 'Order % not found', p_voided_order_id; end if;

  perform fn_require_account_role(v_o.account_id,
    array['owner','manager','sales']::member_role[], 'reissuing orders');

  if v_o.voided_at is null then
    raise exception 'Only a voided order can be reissued' using errcode='check_violation';
  end if;

  -- orders carries unique (business_id, order_no), so the replacement needs a
  -- distinct reference. -R, -R2, -R3 ... until one is free.
  if v_o.order_no is not null then
    v_no := v_o.order_no || '-R';
    while exists (select 1 from orders where business_id = v_o.business_id and order_no = v_no) loop
      v_n := v_n + 1;
      v_no := v_o.order_no || '-R' || v_n;
    end loop;
  end if;

  insert into orders (account_id, business_id, location_id, customer_id, channel_id,
                      order_no, order_date, status, created_by, replaces)
  values (v_o.account_id, v_o.business_id, v_o.location_id, v_o.customer_id, v_o.channel_id,
          v_no, current_date, 'draft', auth.uid(), v_o.id)
  returning id into v_new;

  return jsonb_build_object('reissued', true,
    'replaces', p_voided_order_id, 'new_order_id', v_new, 'order_no', v_no,
    'next_step', 'add_corrected_lines_then_finalise');
end;
$$;

-- sales_entries are immutable from insert: there is no draft stage to correct in.
create or replace function fn_void_sales_entry(p_entry_id uuid, p_reason text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_e sales_entries%rowtype;
begin
  select * into v_e from sales_entries where id = p_entry_id for update;
  if not found then raise exception 'Sales entry % not found', p_entry_id; end if;

  perform fn_require_account_role(v_e.account_id,
    array['owner','manager']::member_role[], 'voiding sales');

  if v_e.voided_at is not null then
    raise exception 'Sales entry % is already voided', p_entry_id using errcode='check_violation';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A void requires a reason' using errcode='check_violation';
  end if;

  update sales_entries
     set voided_at = now(), voided_by = auth.uid(), void_reason = btrim(p_reason)
   where id = p_entry_id;

  return jsonb_build_object('voided', true, 'sales_entry_id', p_entry_id);
end;
$$;

-- ----------------------------------------------------------------------------
-- 3. IMMUTABILITY GUARDS
-- ----------------------------------------------------------------------------

create or replace function fn_guard_finalised_order()
returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    if old.finalised_at is not null then
      raise exception 'Order % is finalised and cannot be deleted. Void it instead.', old.id
        using errcode='check_violation';
    end if;
    return old;
  end if;

  if old.voided_at is not null then
    raise exception 'Order % is voided. Its record is closed.', old.id
      using errcode='check_violation';
  end if;

  if old.finalised_at is not null then
    -- Settlement may still move after the sale: collecting payment later is not
    -- a revenue rewrite. Everything that determines revenue is frozen.
    if (old.account_id, old.business_id, old.location_id, old.customer_id,
        old.channel_id, old.order_no, old.order_date, old.status,
        old.finalised_at, old.replaces)
       is distinct from
       (new.account_id, new.business_id, new.location_id, new.customer_id,
        new.channel_id, new.order_no, new.order_date, new.status,
        new.finalised_at, new.replaces)
    then
      raise exception 'Order % is finalised. Only payment state may change, or void it.', old.id
        using errcode='check_violation';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_orders_finalised on orders;
create trigger trg_orders_finalised
  before update or delete on orders
  for each row execute function fn_guard_finalised_order();

create or replace function fn_guard_order_line_revenue()
returns trigger language plpgsql as $$
declare v_final timestamptz; v_void timestamptz; v_order uuid;
begin
  v_order := coalesce(new.order_id, old.order_id);
  select finalised_at, voided_at into v_final, v_void from orders where id = v_order;

  if v_final is null then
    return coalesce(new, old);            -- still a draft: freely editable
  end if;

  if tg_op = 'INSERT' then
    raise exception 'Order % is finalised. No further lines may be added.', v_order
      using errcode='check_violation';
  elsif tg_op = 'DELETE' then
    raise exception 'Order % is finalised. Lines cannot be deleted. Void the order instead.', v_order
      using errcode='check_violation';
  else
    if (old.qty, old.unit_price, old.recipe_id)
       is distinct from (new.qty, new.unit_price, new.recipe_id) then
      raise exception 'Revenue on a finalised sale is immutable. Void and reissue instead.'
        using errcode='check_violation';
    end if;
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_order_lines_revenue on order_lines;
create trigger trg_order_lines_revenue
  before insert or update or delete on order_lines
  for each row execute function fn_guard_order_line_revenue();

create or replace function fn_guard_sales_entry_immutable()
returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'A recorded sale cannot be deleted. Void it instead.'
      using errcode='check_violation';
  end if;

  if (old.account_id, old.business_id, old.location_id, old.channel_id, old.sale_date,
      old.recipe_id, old.qty, old.unit_price)
     is distinct from
     (new.account_id, new.business_id, new.location_id, new.channel_id, new.sale_date,
      new.recipe_id, new.qty, new.unit_price)
  then
    raise exception 'A recorded sale is immutable. Void and re-enter instead.'
      using errcode='check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_sales_entries_immutable on sales_entries;
create trigger trg_sales_entries_immutable
  before update or delete on sales_entries
  for each row execute function fn_guard_sales_entry_immutable();

-- ----------------------------------------------------------------------------
-- 4. PROFITABILITY VIEWS REBUILT
--
-- Voided sales leave revenue and COGS. They remain fully queryable as rows, so
-- the audit trail is intact; they simply stop counting as money.
-- Grants are restated because DROP VIEW discards them (0011 granted these).
-- ----------------------------------------------------------------------------

drop view if exists v_dashboard_waterfall;
drop view if exists v_profit_by_product;
drop view if exists v_profit_by_period;
drop view if exists v_sales_unified;

create view v_sales_unified with (security_invoker = on) as
select
  ol.account_id, o.business_id, o.order_date as sale_date, o.channel_id,
  ol.recipe_id, ol.qty, ol.unit_price,
  ol.line_total as revenue,
  ol.unit_cost_at_sale,
  ol.cost_snapshot_id,
  case when ol.unit_cost_at_sale is not null
       then ol.qty * ol.unit_cost_at_sale end as cogs,
  'order'::text as source
from order_lines ol
join orders o on o.id = ol.order_id
where o.status <> 'cancelled'
  and o.voided_at is null                      -- 0014: voided sales do not count
union all
select
  se.account_id, se.business_id, se.sale_date, se.channel_id,
  se.recipe_id, se.qty, se.unit_price,
  se.qty * se.unit_price,
  se.unit_cost_at_sale,
  se.cost_snapshot_id,
  case when se.unit_cost_at_sale is not null
       then se.qty * se.unit_cost_at_sale end,
  'daily_total'
from sales_entries se
where se.voided_at is null;                    -- 0014

create view v_profit_by_period with (security_invoker = on) as
select
  account_id,
  business_id,
  date_trunc('month', sale_date)::date as period,
  round(sum(revenue), 2)                                  as revenue,
  round(sum(cogs), 2)                                     as cogs,
  round(sum(revenue) - coalesce(sum(cogs), 0), 2)         as gross_profit,
  round(100.0 * (sum(revenue) - coalesce(sum(cogs), 0))
        / nullif(sum(revenue), 0), 2)                     as gross_margin_pct,
  round(100.0 * sum(case when unit_cost_at_sale is not null then revenue else 0 end)
        / nullif(sum(revenue), 0), 2)                     as cost_coverage_pct,
  round(sum(case when unit_cost_at_sale is null then revenue else 0 end), 2)
                                                          as revenue_without_cost
from v_sales_unified
group by account_id, business_id, date_trunc('month', sale_date);

create view v_profit_by_product with (security_invoker = on) as
select
  s.account_id, s.business_id, s.recipe_id, r.name,
  round(sum(s.qty), 3)                                as units_sold,
  round(sum(s.revenue), 2)                            as revenue,
  round(sum(s.cogs), 2)                               as cogs,
  round(sum(s.revenue) - coalesce(sum(s.cogs), 0), 2) as gross_profit,
  round(100.0 * (sum(s.revenue) - coalesce(sum(s.cogs), 0))
        / nullif(sum(s.revenue), 0), 2)               as gross_margin_pct,
  round(100.0 * sum(case when s.unit_cost_at_sale is not null then s.revenue else 0 end)
        / nullif(sum(s.revenue), 0), 2)               as cost_coverage_pct
from v_sales_unified s
join recipes r on r.id = s.recipe_id
group by s.account_id, s.business_id, s.recipe_id, r.name;

create view v_dashboard_waterfall with (security_invoker = on) as
select
  business_id, account_id, period, revenue, cogs, gross_profit,
  gross_margin_pct, cost_coverage_pct, revenue_without_cost,
  case when cost_coverage_pct is null then 'no_sales'
       when cost_coverage_pct >= 100 then 'complete'
       when cost_coverage_pct >= 80  then 'mostly_covered'
       else 'partial' end as confidence
from v_profit_by_period;

grant select on v_sales_unified, v_profit_by_period,
                v_profit_by_product, v_dashboard_waterfall
  to authenticated;

-- A voided-sales audit surface, so a reversal is visible rather than merely absent.
create or replace view v_voided_sales with (security_invoker = on) as
select 'order'::text as source, o.account_id, o.business_id, o.id as record_id,
       o.order_no as reference, o.order_date as sale_date,
       o.voided_at, o.voided_by, o.void_reason,
       (select id from orders r where r.replaces = o.id) as replaced_by
from orders o
where o.voided_at is not null
union all
select 'daily_total', se.account_id, se.business_id, se.id, null, se.sale_date,
       se.voided_at, se.voided_by, se.void_reason,
       (select id from sales_entries r where r.replaces = se.id)
from sales_entries se
where se.voided_at is not null;

grant select on v_voided_sales to authenticated;

-- ---------------------------------------------------------------- 0015_write_side_role_enforcement.sql
-- ============================================================================
-- MENU MASTER NG
-- 0015: write-side role enforcement
--
-- GATE 1 CLOSURE, item A4.
--
-- THE DEFECT
--   0001 applied one blanket policy to every tenant table:
--       create policy p_<t> on <t> for all
--         using (fn_is_account_member(account_id))
--         with check (fn_is_account_member(account_id));
--   Membership alone therefore granted INSERT, UPDATE and DELETE on everything.
--   Read access was role-aware from 0004 onward; write access never was. A
--   kitchen user could delete recipes, edit business settings and change target
--   margins. Gate 1 fixed only memberships and subscriptions -- the two tables
--   that confer authority. This closes the remaining 21.
--
--   Measured, not assumed: 24 tables carried the blanket policy, 0012 re-scoped
--   memberships and subscriptions, 0004 cost-gated ingredient_prices and
--   recipe_prices. 21 remained.
--
-- THE MODEL (founder rulings, Gate 1 closure)
--   owner       full business control
--   manager     operational management; no ownership or security administration
--   kitchen     recipe/production operations only; no financial administration
--   sales       sales/order/customer operations only; cannot touch costing
--               history, recipe costing or protected settings
--   accountant  financial, purchasing, costing and reporting; no recipe or
--               production administration, no ownership or security control
--
-- NOTES ON TWO DELIBERATE RULINGS
--   * channels: manager MAY set channel-level target margins (legitimate
--     operational pricing). The business-wide default in business_settings
--     stays owner-only, so channel access is not a back door to the global
--     default.
--   * ingredients.purchase_yield_pct and ingredient_unit_conversions.qty_in_base
--     are production facts that move cost. Kitchen keeps INSERT/UPDATE on them
--     because the people who know the yields must be able to record them.
--     Kitchen gains no other financial permission, and every change still
--     writes an auditable snapshot through the 0008 recompute triggers.
--
-- SELECT is unchanged. Cost-bearing tables stay gated by fn_can_see_costs
-- (0004); this migration governs writes only.
--
-- ADDITIVE. No earlier migration is rewritten. Idempotent.
-- ============================================================================

do $$
declare
  spec record;
  v_roles text;
begin
  for spec in
    select * from (values
      --  table                          INSERT                                        UPDATE                                        DELETE
      ('businesses',                  array['owner'],                               array['owner'],                               array[]::text[]),
      ('locations',                   array['owner','manager'],                     array['owner','manager'],                     array['owner','manager']),
      ('ingredient_categories',       array['owner','manager','kitchen'],           array['owner','manager','kitchen'],           array['owner','manager']),
      ('ingredients',                 array['owner','manager','kitchen'],           array['owner','manager','kitchen'],           array['owner']),
      ('ingredient_unit_conversions', array['owner','manager','kitchen'],           array['owner','manager','kitchen'],           array['owner','manager']),
      ('suppliers',                   array['owner','manager','accountant'],        array['owner','manager','accountant'],        array['owner','manager']),
      ('business_settings',           array[]::text[],                              array['owner'],                               array[]::text[]),
      ('costing_method_changes',      array['owner'],                               array[]::text[],                              array[]::text[]),
      ('recipes',                     array['owner','manager','kitchen'],           array['owner','manager','kitchen'],           array['owner']),
      ('recipe_lines',                array['owner','manager','kitchen'],           array['owner','manager','kitchen'],           array['owner','manager','kitchen']),
      ('labour_rates',                array['owner','manager','accountant'],        array['owner','manager','accountant'],        array['owner','manager']),
      ('recipe_labour',               array['owner','manager','kitchen'],           array['owner','manager','kitchen'],           array['owner','manager','kitchen']),
      ('overhead_items',              array['owner','manager','accountant'],        array['owner','manager','accountant'],        array['owner','manager']),
      ('channels',                    array['owner','manager'],                     array['owner','manager'],                     array['owner']),
      ('purchases',                   array['owner','manager','accountant'],        array['owner','manager','accountant'],        array['owner','manager','accountant']),
      ('purchase_lines',              array['owner','manager','accountant'],        array['owner','manager','accountant'],        array['owner','manager','accountant']),
      ('customers',                   array['owner','manager','sales'],             array['owner','manager','sales'],             array['owner','manager']),
      ('orders',                      array['owner','manager','sales'],             array['owner','manager','sales'],             array['owner','manager']),
      ('order_lines',                 array['owner','manager','sales'],             array['owner','manager','sales'],             array['owner','manager','sales']),
      ('sales_entries',               array['owner','manager','sales'],             array[]::text[],                              array[]::text[]),
      ('period_closes',               array['owner','accountant'],                  array[]::text[],                              array[]::text[])
    ) as t(tbl, ins_roles, upd_roles, del_roles)
  loop
    -- Retire the blanket policy from 0001.
    execute format('drop policy if exists p_%I on %I', spec.tbl, spec.tbl);
    execute format('drop policy if exists p_%I_select on %I', spec.tbl, spec.tbl);
    execute format('drop policy if exists p_%I_insert on %I', spec.tbl, spec.tbl);
    execute format('drop policy if exists p_%I_update on %I', spec.tbl, spec.tbl);
    execute format('drop policy if exists p_%I_delete on %I', spec.tbl, spec.tbl);

    -- SELECT: unchanged. Any member of the account may read; cost-bearing
    -- tables remain separately gated by fn_can_see_costs.
    execute format(
      'create policy p_%I_select on %I for select using (fn_is_account_member(account_id))',
      spec.tbl, spec.tbl);

    if array_length(spec.ins_roles,1) is not null then
      v_roles := array_to_string(spec.ins_roles, ''',''');
      execute format(
        'create policy p_%I_insert on %I for insert
           with check (fn_is_account_member(account_id)
                       and fn_has_account_role(account_id, array[''%s'']::member_role[]))',
        spec.tbl, spec.tbl, v_roles);
    end if;

    if array_length(spec.upd_roles,1) is not null then
      v_roles := array_to_string(spec.upd_roles, ''',''');
      execute format(
        'create policy p_%I_update on %I for update
           using      (fn_is_account_member(account_id)
                       and fn_has_account_role(account_id, array[''%s'']::member_role[]))
           with check (fn_is_account_member(account_id)
                       and fn_has_account_role(account_id, array[''%s'']::member_role[]))',
        spec.tbl, spec.tbl, v_roles, v_roles);
    end if;

    if array_length(spec.del_roles,1) is not null then
      v_roles := array_to_string(spec.del_roles, ''',''');
      execute format(
        'create policy p_%I_delete on %I for delete
           using (fn_is_account_member(account_id)
                  and fn_has_account_role(account_id, array[''%s'']::member_role[]))',
        spec.tbl, spec.tbl, v_roles);
    end if;
  end loop;
end
$$;

-- ----------------------------------------------------------------------------
-- Tables with NO write policy at all, by design:
--   business_settings  INSERT/DELETE  one row per business, created by
--                      onboarding (SECURITY DEFINER). Deleting it would break
--                      costing outright.
--   costing_method_changes  UPDATE/DELETE  append-only audit of a dated event.
--   sales_entries      UPDATE/DELETE  immutable from insert (0014). Correction
--                      is fn_void_sales_entry.
--   period_closes      UPDATE/DELETE  a closed period never silently changes.
--   businesses         DELETE  cascades every financial record. Retirement is
--                      deleted_at, not DROP.
--
-- SECURITY DEFINER functions (onboarding, posting, voting, snapshotting) run as
-- the definer and are unaffected by these policies. They carry their own
-- authorization from 0012, which remains the enforcement point for those paths.
-- ----------------------------------------------------------------------------

-- ---------------------------------------------------------------- 0016_role_function_permissions.sql
-- ============================================================================
-- MENU MASTER NG
-- 0016: role-aware function permissions
--
-- GATE 1 CLOSURE. Three concerns, all about who may invoke what.
--
--   1. An internal recompute path, so a kitchen user can record a production
--      fact without holding cost access.
--   2. Accountant purchase posting and controlled reversal (founder ruling Q3b).
--   3. EXECUTE grants and revokes for everything 0013 and 0014 introduced.
--
-- ADDITIVE. No earlier migration is rewritten. Idempotent.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. TRIGGER-INITIATED RECOMPUTATION
--
-- THE CONFLICT, found by test 005 rather than by reading the SQL:
--   Founder ruling Q2 gives kitchen INSERT/UPDATE on ingredients.purchase_yield_pct
--   and ingredient_unit_conversions.qty_in_base -- production facts the kitchen
--   is the authority on. But 0008 puts recompute triggers on both tables, that
--   recompute reaches fn_ingredient_unit_cost, and 0012 guards it with
--   fn_require_cost_access. A kitchen user therefore held the RLS right to
--   record a yield and was still refused with
--   "Your role does not permit access to cost information", because recording a
--   production fact recomputes costs and kitchen cannot see costs.
--
--   The same wall blocks any sales user whose action triggers a recompute.
--
-- THE RESOLUTION
--   Inside a trigger, the ROLE half of the cost check is relaxed. The ACCOUNT
--   half is not: cross-account access still raises, so no tenant boundary moves.
--
--   This is the shape Gate 1 already ships and proves in report section 5 (R5):
--   a user without cost access performs an operation whose CONSEQUENCE is a cost
--   write, executed by a SECURITY DEFINER trigger, while that user still cannot
--   read a single cost figure. Causing a snapshot to exist is not reading it.
--
-- WHY pg_trigger_depth() CANNOT BE FORGED BY A CLIENT
--   It is non-zero only while Postgres is executing a trigger. A client reaches
--   that state only by performing a DML that migration 0015 already authorises
--   for its role, on its own account's rows. It cannot install a trigger of its
--   own: CREATE TRIGGER requires table ownership, which `authenticated` does not
--   have. There is no GUC or parameter here for a caller to set -- a deliberate
--   choice, because a settable bypass flag would be exactly the "authority taken
--   from the request instead of from the data" defect Gate 1 was called to fix.
--
--   Direct RPC calls are unaffected and remain fully guarded at trigger depth 0.
--   Attacks A1-A4, X6 and X7 in suite 002 continue to prove this.
-- ----------------------------------------------------------------------------

create or replace function fn_require_cost_access(p_account_id uuid)
returns void
language plpgsql stable security definer set search_path = public
as $$
begin
  if fn_is_service_context() then return; end if;

  -- Account boundary: enforced identically in every context.
  if p_account_id is null or not fn_is_account_member(p_account_id) then
    raise exception 'Not authorized for this account' using errcode = '42501';
  end if;

  -- Role boundary: relaxed ONLY for trigger-initiated recomputation, so that
  -- recording a production fact does not require permission to read costs.
  if pg_trigger_depth() > 0 then
    return;
  end if;

  if not fn_can_see_costs(p_account_id) then
    raise exception 'Your role does not permit access to cost information'
      using errcode = '42501';
  end if;
end;
$$;

-- ----------------------------------------------------------------------------
-- 2. ACCOUNTANT PURCHASE RIGHTS (founder ruling Q3b, with its restriction)
--
--   MAY   create and post purchases, and reverse a posted purchase through the
--         sanctioned fn_reverse_purchase, which preserves the original and
--         writes a compensating reversal.
--   MAY NOT  delete, rewrite or mutate a posted purchase directly. That is not
--         enforced here but by the 0006 immutability triggers, which refuse any
--         edit or deletion of a non-draft purchase regardless of role.
--   MAY NOT  void or rewrite finalised sales: fn_void_order and
--         fn_void_sales_entry (0014) deliberately exclude accountant.
-- ----------------------------------------------------------------------------

create or replace function fn_post_purchase(p_purchase_id uuid)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_p purchases%rowtype; v_blockers jsonb; v_zero jsonb; v_lines integer;
  v_written integer := 0; r record; v_base numeric;
begin
  select * into v_p from purchases where id = p_purchase_id for update;
  if not found then raise exception 'Purchase % not found', p_purchase_id; end if;

  perform fn_require_account_role(v_p.account_id,
    array['owner','manager','accountant']::member_role[], 'posting purchases');

  if v_p.status <> 'draft' then
    raise exception 'Purchase % is already %', p_purchase_id, v_p.status
      using errcode='check_violation';
  end if;

  select count(*) into v_lines from purchase_lines where purchase_id = p_purchase_id;
  if v_lines = 0 then
    raise exception 'Purchase % has no lines', p_purchase_id using errcode='check_violation';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
           'purchase_line_id', pl.id, 'ingredient_id', pl.ingredient_id,
           'ingredient_name', i.name, 'amount', pl.amount,
           'problem', 'zero_value_line')), '[]'::jsonb)
    into v_zero
  from purchase_lines pl join ingredients i on i.id = pl.ingredient_id
  where pl.purchase_id = p_purchase_id and pl.amount <= 0;

  if jsonb_array_length(v_zero) > 0 then
    return jsonb_build_object('posted', false, 'reason', 'zero_value_lines', 'blockers', v_zero);
  end if;

  v_blockers := fn_purchase_blockers(p_purchase_id);
  if jsonb_array_length(v_blockers) > 0 then
    return jsonb_build_object('posted', false,
      'reason', 'unresolved_conversions', 'blockers', v_blockers);
  end if;

  for r in select * from purchase_lines where purchase_id = p_purchase_id loop
    v_base := fn_resolve_qty_to_base(r.ingredient_id, r.qty, r.unit_id);
    if v_base is null or v_base <= 0 then
      raise exception 'Line % did not resolve. Refusing to post.', r.id
        using errcode='check_violation';
    end if;
    update purchase_lines set qty_base = v_base where id = r.id;
    insert into ingredient_prices (
      account_id, ingredient_id, supplier_id, purchase_line_id,
      qty_base, amount, source, effective_date, entered_by)
    values (v_p.account_id, r.ingredient_id, v_p.supplier_id, r.id,
      v_base, r.amount, 'purchase', v_p.purchase_date, auth.uid());
    v_written := v_written + 1;
  end loop;

  update purchases set status='posted', posted_at=now(), posted_by=auth.uid()
   where id = p_purchase_id;

  return jsonb_build_object('posted', true,
    'purchase_id', p_purchase_id, 'price_rows_written', v_written);
end;
$$;

create or replace function fn_reverse_purchase(p_purchase_id uuid, p_reason text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_p purchases%rowtype; v_rev_id uuid; v_marked integer;
begin
  select * into v_p from purchases where id = p_purchase_id for update;
  if not found then raise exception 'Purchase % not found', p_purchase_id; end if;

  perform fn_require_account_role(v_p.account_id,
    array['owner','manager','accountant']::member_role[], 'reversing purchases');

  if v_p.status <> 'posted' then
    raise exception 'Only a posted purchase can be reversed. This one is %', v_p.status
      using errcode='check_violation';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A reversal requires a reason' using errcode='check_violation';
  end if;

  insert into purchases (
    account_id, business_id, location_id, supplier_id, purchase_date,
    reference, note, status, reverses, reversal_reason, created_by, posted_at, posted_by)
  values (
    v_p.account_id, v_p.business_id, v_p.location_id, v_p.supplier_id, current_date,
    coalesce(v_p.reference,'') || ' (reversal)', v_p.note, 'reversed',
    v_p.id, p_reason, auth.uid(), now(), auth.uid())
  returning id into v_rev_id;

  update ingredient_prices ip
     set reversed_at = now(), reversed_by_purchase_id = v_rev_id
   where ip.purchase_line_id in (select id from purchase_lines where purchase_id = p_purchase_id)
     and ip.reversed_at is null;
  get diagnostics v_marked = row_count;

  update purchases set status = 'reversed' where id = p_purchase_id;

  return jsonb_build_object('reversed', true,
    'original_purchase_id', p_purchase_id, 'reversal_purchase_id', v_rev_id,
    'price_rows_reversed', v_marked);
end;
$$;

-- ----------------------------------------------------------------------------
-- 3. API SURFACE FOR 0013 / 0014 / 0016
-- ----------------------------------------------------------------------------

revoke execute on function fn_guard_finalised_order()        from public, anon, authenticated;
revoke execute on function fn_guard_order_line_revenue()     from public, anon, authenticated;
revoke execute on function fn_guard_sales_entry_immutable()  from public, anon, authenticated;

grant execute on function
  fn_finalise_order(uuid),
  fn_void_order(uuid, text),
  fn_reissue_order(uuid),
  fn_void_sales_entry(uuid, text)
  to authenticated;

grant select on v_voided_sales to authenticated;

-- ---------------------------------------------------------------- 0017_subscription_state_integrity.sql
-- ============================================================================
-- MENU MASTER NG
-- 0017: subscription state integrity
--
-- Closes two defects found while preparing the service-context test (S13):
--
--   1. fn_set_subscription_plan returned success when its UPDATE matched no
--      rows. A billing webhook would record a customer as upgraded while the
--      database still said 'trialing'. Money taken, no entitlement, no error.
--
--   2. subscriptions.status was free text with no CHECK. Any string could be
--      persisted as an entitlement state, including Paystack's own vocabulary
--      or a typo, permanently corrupting the state machine.
--
-- And closes one gap: the one-subscription-per-account rule was enforced by
-- trigger for CLIENTS only, leaving service_role free to create duplicates.
--
-- The canonical states and their transition semantics are documented in
-- docs/SUBSCRIPTION_STATE_MACHINE.md. This migration constrains the SET of
-- values; it deliberately does not enforce transitions between them.
--
-- ADDITIVE. Migrations 0001-0016 are not modified. Idempotent: re-running is
-- a no-op.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. PREFLIGHT
--
-- Refuses to apply rather than damaging data. Neither branch deletes, merges
-- nor coerces anything: choosing which duplicate subscription survives, or
-- what an unrecognised status "really meant", is a commercial decision and
-- not one a migration may take on the operator's behalf.
-- ----------------------------------------------------------------------------

do $$
declare
  v_bad     integer;
  v_values  text;
  v_dupes   text;
begin
  select count(*), string_agg(distinct status, ', ' order by status)
    into v_bad, v_values
    from subscriptions
   where status not in ('trialing','active','past_due','cancelled');

  if v_bad > 0 then
    raise exception
      '0017 preflight FAILED: % subscription row(s) hold a status outside the '
      'approved set. Offending values: %. Approved: trialing, active, past_due, '
      'cancelled. Correct these rows deliberately, then re-run. See '
      'docs/SUBSCRIPTION_STATE_MACHINE.md.', v_bad, v_values;
  end if;

  select string_agg(account_id::text || ' (' || n || ' rows)', ', ')
    into v_dupes
    from (select account_id, count(*) as n
            from subscriptions group by account_id having count(*) > 1) d;

  if v_dupes is not null then
    raise exception
      '0017 preflight FAILED: account(s) hold more than one subscription: %. '
      'The unique index cannot be created until exactly one row per account '
      'remains. Decide which survives before re-running.', v_dupes;
  end if;
end
$$;

-- ----------------------------------------------------------------------------
-- 2. PROTECTION 2a: the closed set, enforced by the database
--
-- The backstop. Even a direct service_role write cannot persist an
-- unrecognised value.
-- ----------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_constraint
                  where conrelid = 'subscriptions'::regclass
                    and conname  = 'ck_subscriptions_status') then
    alter table subscriptions
      add constraint ck_subscriptions_status
      check (status in ('trialing','active','past_due','cancelled'));
  end if;
end
$$;

comment on constraint ck_subscriptions_status on subscriptions is
  'Menu Master NG internal entitlement states. Paystack statuses are mapped at '
  'the boundary, never persisted. See docs/SUBSCRIPTION_STATE_MACHINE.md.';

-- ----------------------------------------------------------------------------
-- 3. PROTECTION 3: one subscription per account, at the database level
--
-- fn_guard_subscription_writes already refuses a client's second subscription,
-- but it returns early for service context. This closes that asymmetry, and is
-- what makes the multi-row branch in section 4 an assertion rather than a hope.
-- ----------------------------------------------------------------------------

create unique index if not exists ux_subscriptions_account
  on subscriptions (account_id);

-- ----------------------------------------------------------------------------
-- 4. PROTECTION 1 + 2b: the billing path fails loudly
--
-- Signature unchanged, so no second overload is created and 0012's REVOKEs
-- continue to apply. Re-stated at the end regardless.
-- ----------------------------------------------------------------------------

create or replace function fn_set_subscription_plan(
  p_account_id uuid,
  p_plan_id    text,
  p_status     text default 'active',
  p_period_end timestamptz default null,
  p_provider_ref text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rows integer;
begin
  if not fn_is_service_context() then
    raise exception 'Only the billing system may change a subscription'
      using errcode = '42501';
  end if;

  if not exists (select 1 from plans where id = p_plan_id and is_active) then
    raise exception 'Unknown or inactive plan %', p_plan_id
      using errcode = '22023';
  end if;

  -- Explicit validation ahead of the CHECK constraint, so the caller gets a
  -- message that says what to do rather than a raw constraint violation.
  -- An unrecognised external status leaves the row EXACTLY as it was: a
  -- guessed write is worse than no write, and neither 'cancelled' (cuts off a
  -- paying customer) nor 'active' (gives away the product) is a safe default.
  if p_status is null or p_status not in ('trialing','active','past_due','cancelled') then
    raise exception
      'Unknown subscription status %. Map external statuses to one of: '
      'trialing, active, past_due, cancelled.', coalesce(quote_literal(p_status),'NULL')
      using errcode = '22023';
  end if;

  update subscriptions
     set plan_id            = p_plan_id,
         status             = p_status,
         current_period_end = coalesce(p_period_end, current_period_end),
         provider_ref       = coalesce(p_provider_ref, provider_ref)
   where account_id = p_account_id;

  get diagnostics v_rows = row_count;

  -- A billing call that changed nothing must fail, not report success.
  if v_rows = 0 then
    raise exception
      'No subscription exists for account %. Nothing was changed.', p_account_id
      using errcode = 'P0002';
  elsif v_rows > 1 then
    raise exception
      'Account % holds % subscription rows; refusing an ambiguous update.',
      p_account_id, v_rows
      using errcode = '21000';
  end if;

  -- Report what actually happened rather than echoing the arguments back.
  return jsonb_build_object(
    'account_id',   p_account_id,
    'plan_id',      p_plan_id,
    'status',       p_status,
    'rows_updated', v_rows);
end;
$$;

comment on function fn_set_subscription_plan(uuid, text, text, timestamptz, text) is
  'The billing system''s only sanctioned path to change a subscription. Raises '
  'P0002 when no row matched and 21000 when more than one did. Rejects any '
  'status outside the four canonical states.';

revoke execute on function fn_set_subscription_plan(uuid, text, text, timestamptz, text)
  from public, anon, authenticated;

