-- ============================================================================
-- MENU MASTER NG — Part 4 of 5: engines and Gate 1 hardening
--
-- DISPOSABLE / NON-PRODUCTION PROJECT ONLY.
-- Generated by scripts/build_deploy_chain.sh. Do not edit by hand.
-- Source migrations: 0004_integrity_and_security_fixes.sql 0005_unit_conversion_engine.sql 0006_purchase_posting.sql 0007_recipe_cost_engine.sql 0008_snapshot_and_pricing_engine.sql 0009_sales_freeze_and_profitability.sql 0010_onboarding.sql 0011_grants_and_api_surface.sql 0012_gate1_authorization_hardening.sql
--
-- Unit conversion, purchase posting, recipe costing, snapshots, sales freeze, onboarding, grants, authorization hardening.
-- ============================================================================

-- ---------------------------------------------------------------- 0004_integrity_and_security_fixes.sql
-- ============================================================================
-- MENU MASTER NG
-- 0004: integrity and security fixes
--
-- BLOCKER FIXED HERE: fn_can_see_costs() checked whether the user held a
-- privileged role ANYWHERE. A manager of account B could therefore read
-- account A's ingredient prices and cost snapshots. It is now scoped to the
-- account being accessed.
--
-- Also: RLS is not enough. RLS protects reads and writes from the client.
-- It does nothing to stop a SECURITY DEFINER function or a bad join from
-- pulling another account's row into a calculation. Composite foreign keys
-- on (id, account_id) make a cross-account reference structurally impossible.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. THE BLOCKER: account scoped cost visibility
-- ----------------------------------------------------------------------------

drop policy if exists p_ingredient_prices on ingredient_prices;
drop policy if exists p_cost_snapshots  on cost_snapshots;
drop function if exists fn_can_see_costs();

create function fn_can_see_costs(p_account_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from memberships m
    where m.account_id = p_account_id
      and m.user_id    = auth.uid()
      and m.role in ('owner','manager','accountant')
  );
$$;

comment on function fn_can_see_costs(uuid) is
  'True only if the current user holds a cost bearing role IN THIS ACCOUNT. '
  'A role in another account grants nothing here.';

create policy p_ingredient_prices on ingredient_prices
  for all using      (fn_is_account_member(account_id) and fn_can_see_costs(account_id))
      with check (fn_is_account_member(account_id) and fn_can_see_costs(account_id));

create policy p_cost_snapshots on cost_snapshots
  for all using      (fn_is_account_member(account_id) and fn_can_see_costs(account_id))
      with check (fn_is_account_member(account_id) and fn_can_see_costs(account_id));

-- Selling prices and margins are cost adjacent. Kitchen and sales roles
-- should not read them either.
drop policy if exists p_recipe_prices on recipe_prices;
create policy p_recipe_prices on recipe_prices
  for all using      (fn_is_account_member(account_id) and fn_can_see_costs(account_id))
      with check (fn_is_account_member(account_id) and fn_can_see_costs(account_id));

-- ----------------------------------------------------------------------------
-- 2. NULLABILITY CORRECTIONS
-- ----------------------------------------------------------------------------

-- Global categories are unreachable under RLS. Categories are per account.
delete from ingredient_categories where account_id is null;
alter table ingredient_categories alter column account_id set not null;

-- CONFLICT FOUND: purchase_lines.qty_base was NOT NULL, which forced the
-- caller to invent a base quantity when no conversion exists. That is
-- exactly the behaviour the source of truth rule forbids. Unresolved lines
-- must be storable; they simply cannot be POSTED.
alter table purchase_lines alter column qty_base drop not null;

-- ----------------------------------------------------------------------------
-- 3. PURCHASE LIFECYCLE COLUMNS (posting flow, implemented in 0006)
-- ----------------------------------------------------------------------------

create type purchase_status as enum ('draft', 'posted', 'reversed');

alter table purchases
  add column status     purchase_status not null default 'draft',
  add column posted_at  timestamptz,
  add column posted_by  uuid references auth.users(id) on delete set null,
  add column reverses   uuid references purchases(id),
  add column reversal_reason text;

-- ----------------------------------------------------------------------------
-- 4. PRICE ROW PROVENANCE AND REVERSAL
-- A posted price is never edited or deleted. A reversal marks it superseded
-- and every cost function ignores superseded rows from that point forward.
-- ----------------------------------------------------------------------------

alter table ingredient_prices
  add column reversed_at timestamptz,
  add column reversed_by_purchase_id uuid references purchases(id),
  add constraint fk_ip_purchase_line
    foreign key (purchase_line_id) references purchase_lines(id) on delete restrict;

create index ix_ingredient_prices_active
  on ingredient_prices (ingredient_id, effective_date desc)
  where reversed_at is null;

-- ----------------------------------------------------------------------------
-- 5. CROSS ACCOUNT REFERENTIAL INTEGRITY
--
-- Every parent gets a unique key on (id, account_id). Every child then
-- references (child_col, account_id) instead of (child_col). The child's own
-- account_id becomes part of the constraint, so pointing at another account's
-- row raises a foreign key violation rather than silently costing a recipe
-- with someone else's ingredient.
-- ----------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array[
    'businesses','locations','ingredient_categories','ingredients','suppliers',
    'recipes','labour_rates','overhead_items','channels','purchases',
    'purchase_lines','customers','orders','cost_snapshots'
  ]
  loop
    execute format('alter table %I add constraint ux_%I_id_account unique (id, account_id)', t, t);
  end loop;
end $$;

do $$
declare
  r record;
  specs text[][] := array[
    -- child table,            child column,       parent table
    array['locations',                  'business_id',    'businesses'],
    array['memberships',                'business_id',    'businesses'],
    array['business_settings',          'business_id',    'businesses'],
    array['ingredients',                'category_id',    'ingredient_categories'],
    array['ingredient_unit_conversions','ingredient_id',  'ingredients'],
    array['ingredient_prices',          'ingredient_id',  'ingredients'],
    array['ingredient_prices',          'supplier_id',    'suppliers'],
    array['recipes',                    'business_id',    'businesses'],
    array['recipe_lines',               'recipe_id',      'recipes'],
    array['recipe_lines',               'ingredient_id',  'ingredients'],
    array['recipe_lines',               'sub_recipe_id',  'recipes'],
    array['labour_rates',               'business_id',    'businesses'],
    array['recipe_labour',              'recipe_id',      'recipes'],
    array['recipe_labour',              'labour_rate_id', 'labour_rates'],
    array['overhead_items',             'business_id',    'businesses'],
    array['channels',                   'business_id',    'businesses'],
    array['recipe_prices',              'recipe_id',      'recipes'],
    array['recipe_prices',              'channel_id',     'channels'],
    array['cost_snapshots',             'recipe_id',      'recipes'],
    array['cost_snapshots',             'business_id',    'businesses'],
    array['purchases',                  'business_id',    'businesses'],
    array['purchases',                  'location_id',    'locations'],
    array['purchases',                  'supplier_id',    'suppliers'],
    array['purchase_lines',             'purchase_id',    'purchases'],
    array['purchase_lines',             'ingredient_id',  'ingredients'],
    array['customers',                  'business_id',    'businesses'],
    array['orders',                     'business_id',    'businesses'],
    array['orders',                     'customer_id',    'customers'],
    array['orders',                     'channel_id',     'channels'],
    array['order_lines',                'order_id',       'orders'],
    array['order_lines',                'recipe_id',      'recipes'],
    array['order_lines',                'cost_snapshot_id','cost_snapshots'],
    array['sales_entries',              'business_id',    'businesses'],
    array['sales_entries',              'recipe_id',      'recipes'],
    array['sales_entries',              'channel_id',     'channels'],
    array['sales_entries',              'cost_snapshot_id','cost_snapshots'],
    array['period_closes',              'business_id',    'businesses']
  ];
  i int;
begin
  for i in 1 .. array_length(specs,1) loop
    execute format(
      'alter table %I add constraint fk_%I_%I_account
         foreign key (%I, account_id) references %I (id, account_id)',
      specs[i][1], specs[i][1], specs[i][2],
      specs[i][2], specs[i][3]);
  end loop;
end $$;

-- ----------------------------------------------------------------------------
-- 6. A recipe line's unit must be global or belong to the same account
-- ----------------------------------------------------------------------------

create or replace function fn_assert_unit_visible()
returns trigger language plpgsql as $$
declare v_unit_account uuid;
begin
  select account_id into v_unit_account from units where id = new.unit_id;
  if v_unit_account is not null and v_unit_account <> new.account_id then
    raise exception 'Unit % belongs to another account', new.unit_id
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

create trigger trg_recipe_lines_unit_scope
  before insert or update on recipe_lines
  for each row execute function fn_assert_unit_visible();

create trigger trg_purchase_lines_unit_scope
  before insert or update on purchase_lines
  for each row execute function fn_assert_unit_visible();

create trigger trg_iuc_unit_scope
  before insert or update on ingredient_unit_conversions
  for each row execute function fn_assert_unit_visible();

-- ---------------------------------------------------------------- 0005_unit_conversion_engine.sql
-- ============================================================================
-- MENU MASTER NG
-- 0005: unit conversion engine
--
-- One resolver, used by purchasing and by costing. It returns NULL when the
-- conversion cannot be established from data this account entered. It never
-- guesses, and it never falls back to a "typical" weight.
--
-- A paint of rice and a paint of beans are different masses. The resolver
-- looks up the conversion by (ingredient, unit), never by unit alone.
-- ============================================================================

create or replace function fn_resolve_qty_to_base(
  p_ingredient_id uuid,
  p_qty           numeric,
  p_unit_id       uuid
)
returns numeric
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_acct        uuid;
  v_base_unit   uuid;
  v_base_kind   unit_kind;
  v_base_factor numeric;
  v_kind        unit_kind;
  v_factor      numeric;
  v_unit_acct   uuid;
  v_specific    numeric;
begin
  if p_ingredient_id is null or p_unit_id is null or p_qty is null then
    return null;
  end if;

  select i.account_id, i.base_unit_id into v_acct, v_base_unit
  from ingredients i where i.id = p_ingredient_id and i.deleted_at is null;

  if v_base_unit is null then
    return null;                      -- unknown ingredient, resolve nothing
  end if;

  -- Same unit as the base: nothing to convert
  if p_unit_id = v_base_unit then
    return p_qty;
  end if;

  select u.kind, u.factor_to_base, u.account_id
    into v_kind, v_factor, v_unit_acct
  from units u where u.id = p_unit_id;

  if v_kind is null then
    return null;                      -- unknown unit
  end if;

  -- Account scoping: a unit is usable only if global, or owned by the
  -- same account as the ingredient.
  if v_unit_acct is not null and v_unit_acct <> v_acct then
    return null;
  end if;

  select u.kind, u.factor_to_base into v_base_kind, v_base_factor
  from units u where u.id = v_base_unit;

  -- CASE 1: universal ratio within the same measurement kind.
  -- 1 kg = 1000 g, 1 litre = 1000 ml, 1 dozen = 12 units.
  if v_factor is not null and v_kind = v_base_kind and coalesce(v_base_factor,0) > 0 then
    return p_qty * v_factor / v_base_factor;
  end if;

  -- CASE 2: container units, and any unit crossing measurement kinds.
  -- These MUST come from this account's own ingredient specific conversion.
  select c.qty_in_base into v_specific
  from ingredient_unit_conversions c
  where c.ingredient_id = p_ingredient_id
    and c.unit_id       = p_unit_id
    and c.account_id    = v_acct;

  if v_specific is null then
    return null;                      -- CASE 3: not knowable. Say so.
  end if;

  return p_qty * v_specific;
end;
$$;

comment on function fn_resolve_qty_to_base(uuid, numeric, uuid) is
  'Resolves a quantity to an ingredient base unit. Returns NULL when the '
  'conversion is not established by this account. Never estimates.';

-- ----------------------------------------------------------------------------
-- Diagnostic: does a given (ingredient, unit) pair resolve at all?
-- ----------------------------------------------------------------------------

create or replace function fn_can_resolve_unit(p_ingredient_id uuid, p_unit_id uuid)
returns boolean
language sql stable security definer set search_path = public
as $$
  select fn_resolve_qty_to_base(p_ingredient_id, 1, p_unit_id) is not null;
$$;

-- ----------------------------------------------------------------------------
-- v_missing_unit_conversions, rebuilt.
--
-- The 0003 version only matched ingredients whose names happened to equal a
-- catalogue entry, so a custom ingredient could never surface a missing
-- conversion. This version reports three sources, ranked by urgency:
--
--   blocking_recipe    a recipe line already uses this unit and cannot cost
--   blocking_purchase  a draft purchase line uses it and cannot post
--   suggested          the catalogue says this item is commonly bought this way
-- ----------------------------------------------------------------------------

drop view if exists v_missing_unit_conversions;

create view v_missing_unit_conversions with (security_invoker = on) as
with needed as (
  select rl.account_id, rl.ingredient_id, rl.unit_id, 'blocking_recipe'::text as reason
  from recipe_lines rl
  where rl.ingredient_id is not null and rl.is_cost_bearing
  union
  select pl.account_id, pl.ingredient_id, pl.unit_id, 'blocking_purchase'
  from purchase_lines pl
  join purchases p on p.id = pl.purchase_id
  where p.status = 'draft'
  union
  select i.account_id, i.id, u.id, 'suggested'
  from ingredients i
  join catalog_ingredients ci on lower(ci.name) = lower(i.name)
  join units u on u.account_id is null
              and u.code = any(ci.common_units)
              and u.factor_to_base is null
  where i.deleted_at is null
)
select distinct on (n.ingredient_id, n.unit_id)
  n.account_id,
  n.ingredient_id,
  i.name  as ingredient_name,
  n.unit_id,
  u.code  as unit_code,
  u.name  as unit_name,
  n.reason
from needed n
join ingredients i on i.id = n.ingredient_id and i.deleted_at is null
join units u on u.id = n.unit_id
where fn_resolve_qty_to_base(n.ingredient_id, 1, n.unit_id) is null
order by n.ingredient_id, n.unit_id,
         case n.reason when 'blocking_recipe' then 1
                       when 'blocking_purchase' then 2
                       else 3 end;

-- ---------------------------------------------------------------- 0006_purchase_posting.sql
-- ============================================================================
-- MENU MASTER NG
-- 0006: purchase posting
--
-- Flow:  CREATE PURCHASE -> ADD LINES -> POST -> PRICES WRITTEN -> IMMUTABLE
--
-- A purchase only becomes a costing input when every line resolves to the
-- ingredient's base unit. If one conversion is missing, posting is refused
-- and the caller is told which line. We never invent qty_base to get past it.
--
-- Corrections are reversals. A posted purchase is never edited, and its
-- price rows are never deleted: they are marked reversed and every cost
-- function ignores them from that moment on.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. A posted purchase is immutable
-- ----------------------------------------------------------------------------

create or replace function fn_guard_posted_purchase()
returns trigger language plpgsql as $$
declare v_status purchase_status;
begin
  if tg_table_name = 'purchases' then
    if tg_op = 'DELETE' then
      if old.status <> 'draft' then
        raise exception 'Purchase % is % and cannot be deleted. Reverse it instead.',
          old.id, old.status using errcode='check_violation';
      end if;
      return old;
    end if;
    -- Allow only the lifecycle transition itself
    if old.status = 'posted' and new.status = 'posted'
       and (old.purchase_date, old.supplier_id, old.business_id, old.location_id)
        is distinct from
           (new.purchase_date, new.supplier_id, new.business_id, new.location_id) then
      raise exception 'Posted purchase % is immutable', old.id
        using errcode='check_violation';
    end if;
    if old.status = 'reversed' and new.status <> 'reversed' then
      raise exception 'Reversed purchase % cannot be reopened', old.id
        using errcode='check_violation';
    end if;
    return new;
  else
    select p.status into v_status from purchases p
     where p.id = coalesce(new.purchase_id, old.purchase_id);
    if v_status <> 'draft' then
      raise exception 'Purchase is % . Its lines cannot be changed.', v_status
        using errcode='check_violation';
    end if;
    return coalesce(new, old);
  end if;
end;
$$;

create trigger trg_purchases_guard
  before update or delete on purchases
  for each row execute function fn_guard_posted_purchase();

create trigger trg_purchase_lines_guard
  before insert or update or delete on purchase_lines
  for each row execute function fn_guard_posted_purchase();

-- ----------------------------------------------------------------------------
-- 2. Price rows are append only and reversal marked
-- ----------------------------------------------------------------------------

create or replace function fn_guard_ingredient_prices()
returns trigger language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'ingredient_prices is append only. Reverse the purchase instead.'
      using errcode='check_violation';
  end if;
  -- The only permitted update is stamping a reversal
  if (old.ingredient_id, old.qty_base, old.amount, old.source,
      old.effective_date, old.supplier_id, old.account_id)
     is distinct from
     (new.ingredient_id, new.qty_base, new.amount, new.source,
      new.effective_date, new.supplier_id, new.account_id) then
    raise exception 'A recorded price is immutable. Only reversal may be stamped.'
      using errcode='check_violation';
  end if;
  return new;
end;
$$;

create trigger trg_ingredient_prices_guard
  before update or delete on ingredient_prices
  for each row execute function fn_guard_ingredient_prices();

-- ----------------------------------------------------------------------------
-- 3. Pre flight check: what stops this purchase from posting?
-- ----------------------------------------------------------------------------

create or replace function fn_purchase_blockers(p_purchase_id uuid)
returns jsonb
language sql stable security definer set search_path = public
as $$
  select coalesce(jsonb_agg(jsonb_build_object(
           'purchase_line_id', pl.id,
           'ingredient_id',    pl.ingredient_id,
           'ingredient_name',  i.name,
           'unit_id',          pl.unit_id,
           'unit_code',        u.code,
           'problem',          'missing_conversion'
         )), '[]'::jsonb)
  from purchase_lines pl
  join ingredients i on i.id = pl.ingredient_id
  join units u on u.id = pl.unit_id
  where pl.purchase_id = p_purchase_id
    and fn_resolve_qty_to_base(pl.ingredient_id, pl.qty, pl.unit_id) is null;
$$;

-- ----------------------------------------------------------------------------
-- 4. POST
-- ----------------------------------------------------------------------------

create or replace function fn_post_purchase(p_purchase_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_p         purchases%rowtype;
  v_blockers  jsonb;
  v_lines     integer;
  v_written   integer := 0;
  r           record;
  v_base      numeric;
begin
  select * into v_p from purchases where id = p_purchase_id;
  if not found then
    raise exception 'Purchase % not found', p_purchase_id;
  end if;
  if v_p.status <> 'draft' then
    raise exception 'Purchase % is already %', p_purchase_id, v_p.status
      using errcode='check_violation';
  end if;

  select count(*) into v_lines from purchase_lines where purchase_id = p_purchase_id;
  if v_lines = 0 then
    raise exception 'Purchase % has no lines', p_purchase_id
      using errcode='check_violation';
  end if;

  -- Refuse rather than invent
  v_blockers := fn_purchase_blockers(p_purchase_id);
  if jsonb_array_length(v_blockers) > 0 then
    return jsonb_build_object(
      'posted', false,
      'reason', 'unresolved_conversions',
      'blockers', v_blockers);
  end if;

  for r in select * from purchase_lines where purchase_id = p_purchase_id loop
    v_base := fn_resolve_qty_to_base(r.ingredient_id, r.qty, r.unit_id);

    -- Belt and braces: never write a price row without a resolved quantity
    if v_base is null or v_base <= 0 then
      raise exception 'Line % did not resolve. Refusing to post.', r.id
        using errcode='check_violation';
    end if;

    update purchase_lines set qty_base = v_base where id = r.id;

    insert into ingredient_prices (
      account_id, ingredient_id, supplier_id, purchase_line_id,
      qty_base, amount, source, effective_date, entered_by)
    values (
      v_p.account_id, r.ingredient_id, v_p.supplier_id, r.id,
      v_base, r.amount, 'purchase', v_p.purchase_date, auth.uid());

    v_written := v_written + 1;
  end loop;

  update purchases
     set status = 'posted', posted_at = now(), posted_by = auth.uid()
   where id = p_purchase_id;

  return jsonb_build_object(
    'posted', true,
    'purchase_id', p_purchase_id,
    'price_rows_written', v_written);
end;
$$;

-- ----------------------------------------------------------------------------
-- 5. REVERSE
-- The original purchase and its price rows stay on record. They are marked
-- reversed, which removes them from every future cost calculation while
-- leaving the history reproducible.
-- ----------------------------------------------------------------------------

create or replace function fn_reverse_purchase(
  p_purchase_id uuid,
  p_reason      text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_p        purchases%rowtype;
  v_rev_id   uuid;
  v_marked   integer;
begin
  select * into v_p from purchases where id = p_purchase_id;
  if not found then
    raise exception 'Purchase % not found', p_purchase_id;
  end if;
  if v_p.status <> 'posted' then
    raise exception 'Only a posted purchase can be reversed. This one is %', v_p.status
      using errcode='check_violation';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A reversal requires a reason' using errcode='check_violation';
  end if;

  insert into purchases (
    account_id, business_id, location_id, supplier_id, purchase_date,
    reference, note, status, reverses, reversal_reason, created_by, posted_at, posted_by)
  values (
    v_p.account_id, v_p.business_id, v_p.location_id, v_p.supplier_id, current_date,
    coalesce(v_p.reference,'') || ' (reversal)', v_p.note, 'reversed',
    v_p.id, p_reason, auth.uid(), now(), auth.uid())
  returning id into v_rev_id;

  update ingredient_prices ip
     set reversed_at = now(), reversed_by_purchase_id = v_rev_id
   where ip.purchase_line_id in (select id from purchase_lines where purchase_id = p_purchase_id)
     and ip.reversed_at is null;
  get diagnostics v_marked = row_count;

  update purchases set status = 'reversed' where id = p_purchase_id;

  return jsonb_build_object(
    'reversed', true,
    'original_purchase_id', p_purchase_id,
    'reversal_purchase_id', v_rev_id,
    'price_rows_reversed', v_marked);
end;
$$;

-- ----------------------------------------------------------------------------
-- 6. Cost resolution must ignore reversed prices
-- Replaces the 0001 version of fn_ingredient_unit_cost.
-- ----------------------------------------------------------------------------

create or replace function fn_ingredient_unit_cost(
  p_ingredient_id uuid,
  p_business_id   uuid,
  p_as_of         date default current_date
)
returns numeric
language plpgsql stable security definer set search_path = public
as $$
declare
  v_account_id uuid;
  v_window     integer;
  v_cost       numeric;
begin
  select account_id, wavg_window_days
    into v_account_id, v_window
  from business_settings where business_id = p_business_id;

  if v_account_id is null then
    return null;
  end if;

  -- Weighted average across this account's own, non reversed purchase history
  select sum(amount) / nullif(sum(qty_base), 0)
    into v_cost
  from ingredient_prices
  where ingredient_id  = p_ingredient_id
    and account_id     = v_account_id
    and reversed_at is null
    and effective_date <= p_as_of
    and effective_date >  p_as_of - (v_window || ' days')::interval;

  if v_cost is null then
    select unit_cost into v_cost
    from ingredient_prices
    where ingredient_id  = p_ingredient_id
      and account_id     = v_account_id
      and reversed_at is null
      and effective_date <= p_as_of
    order by effective_date desc, created_at desc
    limit 1;
  end if;

  return v_cost;   -- NULL means not entered. Never zero.
end;
$$;

-- ---------------------------------------------------------------- 0007_recipe_cost_engine.sql
-- ============================================================================
-- MENU MASTER NG
-- 0007: recipe cost engine
--
-- RECIPE -> LINES -> INGREDIENTS/SUB RECIPES -> CONVERSION -> PURCHASE YIELD
--   -> OWN ACCOUNT PRICE -> INGREDIENT COST -> PACKAGING -> LABOUR
--   -> OVERHEAD -> COOKING YIELD -> BATCH COST -> PER YIELD UNIT
--   -> PER PORTION -> COMPLETENESS GATE -> IMMUTABLE SNAPSHOT
--
-- Nothing here coalesces NULL to zero. A missing price, conversion, labour
-- rate, portion size or overhead configuration makes the snapshot incomplete
-- and is reported by name in unpriced_items.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Floor columns
-- The floor is always computed and stored. The gated figure is NULL unless
-- the snapshot is complete, so no caller can route around the gate.
-- ----------------------------------------------------------------------------

alter table cost_snapshots
  add column floor_batch_cost         numeric(18,4),
  add column floor_cost_per_yield_unit numeric(18,6),
  add column floor_cost_per_portion   numeric(18,4);

comment on column cost_snapshots.cost_per_portion is
  'NULL unless is_complete. Use floor_cost_per_portion for the incomplete floor.';

-- ----------------------------------------------------------------------------
-- 2. Cycle prevention
-- A recipe may not contain itself, directly or through any chain.
-- ----------------------------------------------------------------------------

create or replace function fn_prevent_recipe_cycle()
returns trigger language plpgsql as $$
declare v_cycle boolean;
begin
  if new.sub_recipe_id is null then
    return new;
  end if;

  if new.sub_recipe_id = new.recipe_id then
    raise exception 'A recipe cannot contain itself' using errcode='check_violation';
  end if;

  -- Would new.recipe_id already be reachable from new.sub_recipe_id?
  with recursive descend as (
    select rl.sub_recipe_id as rid, 1 as depth
    from recipe_lines rl
    where rl.recipe_id = new.sub_recipe_id and rl.sub_recipe_id is not null
    union all
    select rl.sub_recipe_id, d.depth + 1
    from recipe_lines rl
    join descend d on rl.recipe_id = d.rid
    where rl.sub_recipe_id is not null and d.depth < 20
  )
  select exists (select 1 from descend where rid = new.recipe_id) into v_cycle;

  if v_cycle then
    raise exception 'Circular sub recipe: % already contains %',
      new.sub_recipe_id, new.recipe_id using errcode='check_violation';
  end if;

  return new;
end;
$$;

create trigger trg_recipe_lines_no_cycle
  before insert or update on recipe_lines
  for each row execute function fn_prevent_recipe_cycle();

-- ----------------------------------------------------------------------------
-- 3. Unit to unit conversion, for sub recipe quantities
-- Sub recipes have no ingredient, so only universal ratios apply.
-- ----------------------------------------------------------------------------

create or replace function fn_convert_between_units(
  p_qty numeric, p_from_unit uuid, p_to_unit uuid)
returns numeric
language plpgsql stable security definer set search_path = public
as $$
declare
  fk unit_kind; ff numeric; tk unit_kind; tf numeric;
begin
  if p_qty is null or p_from_unit is null or p_to_unit is null then return null; end if;
  if p_from_unit = p_to_unit then return p_qty; end if;
  select kind, factor_to_base into fk, ff from units where id = p_from_unit;
  select kind, factor_to_base into tk, tf from units where id = p_to_unit;
  if fk is null or tk is null or fk <> tk then return null; end if;
  if ff is null or tf is null or tf = 0 then return null; end if;
  return p_qty * ff / tf;
end;
$$;

-- ----------------------------------------------------------------------------
-- 4. Usable ingredient cost, purchase yield applied
--
--   1 kg costs N5,000, yield 70 percent  ->  700 g usable
--   cost per usable gram = 5000 / 700, not 5000 / 1000
-- ----------------------------------------------------------------------------

create or replace function fn_ingredient_usable_unit_cost(
  p_ingredient_id uuid, p_business_id uuid, p_as_of date default current_date)
returns numeric
language plpgsql stable security definer set search_path = public
as $$
declare v_cost numeric; v_yield numeric;
begin
  v_cost := fn_ingredient_unit_cost(p_ingredient_id, p_business_id, p_as_of);
  if v_cost is null then return null; end if;
  select purchase_yield_pct into v_yield from ingredients where id = p_ingredient_id;
  if v_yield is null or v_yield <= 0 then return null; end if;
  return v_cost / (v_yield / 100.0);
end;
$$;

-- ----------------------------------------------------------------------------
-- 5. The recursive core
-- Returns costs for ONE BATCH of the recipe plus completeness accounting.
-- Writes nothing. The public function writes the snapshot.
-- ----------------------------------------------------------------------------

create type recipe_cost_result as (
  ingredient_cost      numeric,
  packaging_cost       numeric,
  labour_cost          numeric,
  batch_cost           numeric,
  cost_per_yield_unit  numeric,
  required_inputs      integer,
  priced_inputs        integer,
  excluded_inputs      integer,
  unpriced_items       jsonb,
  is_complete          boolean
);

create or replace function fn__recipe_cost_core(
  p_recipe_id uuid,
  p_as_of     date,
  p_depth     integer default 0
)
returns recipe_cost_result
language plpgsql stable security definer set search_path = public
as $$
declare
  res         recipe_cost_result;
  r           recipes%rowtype;
  line        record;
  lab         record;
  v_base      numeric;
  v_unitcost  numeric;
  v_linecost  numeric;
  sub         recipe_cost_result;
  v_subqty    numeric;
  v_kind      item_kind;
  v_name      text;
  v_unitcode  text;
  v_eff_yield numeric;
begin
  res.ingredient_cost := 0;
  res.packaging_cost  := 0;
  res.labour_cost     := 0;
  res.required_inputs := 0;
  res.priced_inputs   := 0;
  res.excluded_inputs := 0;
  res.unpriced_items  := '[]'::jsonb;
  res.is_complete     := true;

  if p_depth > 10 then
    res.is_complete := false;
    res.unpriced_items := res.unpriced_items || jsonb_build_object(
      'recipe_id', p_recipe_id, 'problem', 'sub_recipe_nesting_too_deep');
    return res;
  end if;

  select * into r from recipes where id = p_recipe_id and deleted_at is null;
  if not found then
    res.is_complete := false;
    res.unpriced_items := res.unpriced_items || jsonb_build_object(
      'recipe_id', p_recipe_id, 'problem', 'recipe_not_found');
    return res;
  end if;

  -- ---------------- recipe lines ----------------
  for line in
    select rl.*, i.name as ing_name, i.kind as ing_kind, u.code as unit_code
    from recipe_lines rl
    left join ingredients i on i.id = rl.ingredient_id
    left join units u on u.id = rl.unit_id
    where rl.recipe_id = p_recipe_id
  loop
    -- Deliberate exclusion. Counted separately, never treated as missing.
    if not line.is_cost_bearing then
      res.excluded_inputs := res.excluded_inputs + 1;
      continue;
    end if;

    res.required_inputs := res.required_inputs + 1;

    if line.ingredient_id is not null then
      v_name     := line.ing_name;
      v_kind     := line.ing_kind;
      v_unitcode := line.unit_code;

      v_base := fn_resolve_qty_to_base(line.ingredient_id, line.qty, line.unit_id);
      if v_base is null then
        res.is_complete := false;
        res.unpriced_items := res.unpriced_items || jsonb_build_object(
          'recipe_id',       p_recipe_id,
          'recipe_line_id',  line.id,
          'ingredient_id',   line.ingredient_id,
          'ingredient_name', v_name,
          'unit',            v_unitcode,
          'problem',         'missing_conversion');
        continue;
      end if;

      v_unitcost := fn_ingredient_usable_unit_cost(line.ingredient_id, r.business_id, p_as_of);
      if v_unitcost is null then
        res.is_complete := false;
        res.unpriced_items := res.unpriced_items || jsonb_build_object(
          'recipe_id',       p_recipe_id,
          'recipe_line_id',  line.id,
          'ingredient_id',   line.ingredient_id,
          'ingredient_name', v_name,
          'problem',         'missing_price');
        continue;
      end if;

      v_linecost := v_base * v_unitcost;
      if v_kind = 'packaging' then
        res.packaging_cost := res.packaging_cost + v_linecost;
      else
        res.ingredient_cost := res.ingredient_cost + v_linecost;
      end if;
      res.priced_inputs := res.priced_inputs + 1;

    else
      -- ---------------- sub recipe ----------------
      sub := fn__recipe_cost_core(line.sub_recipe_id, p_as_of, p_depth + 1);

      -- Completeness propagates upward, always
      if not sub.is_complete then
        res.is_complete := false;
        res.unpriced_items := res.unpriced_items || sub.unpriced_items;
        continue;
      end if;

      select fn_convert_between_units(line.qty, line.unit_id, rr.yield_unit_id)
        into v_subqty
      from recipes rr where rr.id = line.sub_recipe_id;

      if v_subqty is null or sub.cost_per_yield_unit is null then
        res.is_complete := false;
        res.unpriced_items := res.unpriced_items || jsonb_build_object(
          'recipe_id',      p_recipe_id,
          'recipe_line_id', line.id,
          'sub_recipe_id',  line.sub_recipe_id,
          'problem',        'missing_conversion');
        continue;
      end if;

      res.ingredient_cost := res.ingredient_cost + (v_subqty * sub.cost_per_yield_unit);
      res.priced_inputs   := res.priced_inputs + 1;
    end if;
  end loop;

  -- ---------------- labour ----------------
  for lab in
    select rl2.hours, lr.rate_per_hour, lr.name, lr.id as rate_id
    from recipe_labour rl2
    join labour_rates lr on lr.id = rl2.labour_rate_id
    where rl2.recipe_id = p_recipe_id
  loop
    res.required_inputs := res.required_inputs + 1;
    if lab.rate_per_hour is null then
      res.is_complete := false;
      res.unpriced_items := res.unpriced_items || jsonb_build_object(
        'recipe_id',      p_recipe_id,
        'labour_rate_id', lab.rate_id,
        'labour_name',    lab.name,
        'problem',        'missing_labour_rate');
    else
      res.labour_cost := res.labour_cost + (lab.hours * lab.rate_per_hour);
      res.priced_inputs := res.priced_inputs + 1;
    end if;
  end loop;

  -- ---------------- batch and yield ----------------
  res.batch_cost := res.ingredient_cost + res.packaging_cost + res.labour_cost;

  v_eff_yield := r.batch_yield_qty * (r.cooking_yield_pct / 100.0);
  if v_eff_yield is null or v_eff_yield <= 0 then
    res.is_complete := false;
    res.unpriced_items := res.unpriced_items || jsonb_build_object(
      'recipe_id', p_recipe_id, 'problem', 'invalid_yield');
    res.cost_per_yield_unit := null;
  else
    res.cost_per_yield_unit := res.batch_cost / v_eff_yield;
  end if;

  return res;
end;
$$;

-- ----------------------------------------------------------------------------
-- 6. Public entry point: compute and write an immutable snapshot
-- ----------------------------------------------------------------------------

create or replace function fn_compute_recipe_cost_snapshot(
  p_recipe_id  uuid,
  p_as_of      date default current_date,
  p_created_by uuid default auth.uid()
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  r            recipes%rowtype;
  bs           business_settings%rowtype;
  core         recipe_cost_result;
  v_overhead   numeric := 0;
  v_oh_total   numeric;
  v_required   integer;
  v_priced     integer;
  v_unpriced   jsonb;
  v_complete   boolean;
  v_floor_pp   numeric;
  v_snapshot   uuid;
begin
  select * into r from recipes where id = p_recipe_id and deleted_at is null;
  if not found then
    raise exception 'Recipe % not found', p_recipe_id;
  end if;

  select * into bs from business_settings where business_id = r.business_id;
  if not found then
    raise exception 'Business settings missing for business %', r.business_id;
  end if;

  core := fn__recipe_cost_core(p_recipe_id, p_as_of, 0);

  v_required := core.required_inputs;
  v_priced   := core.priced_inputs;
  v_unpriced := core.unpriced_items;
  v_complete := core.is_complete;

  -- ---------------- overhead ----------------
  if bs.overhead_enabled then
    v_required := v_required + 1;
    select sum(monthly_cost) into v_oh_total
    from overhead_items
    where business_id = r.business_id and is_active and monthly_cost is not null;

    if bs.expected_monthly_units is null or bs.expected_monthly_units <= 0
       or v_oh_total is null
       or exists (select 1 from overhead_items
                   where business_id = r.business_id and is_active and monthly_cost is null)
    then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id,
        'business_id', r.business_id,
        'problem', 'missing_overhead_config');
      v_overhead := null;
    else
      v_overhead := v_oh_total / bs.expected_monthly_units;
      v_priced   := v_priced + 1;
    end if;
  end if;

  -- ---------------- portion ----------------
  if r.kind = 'dish' then
    v_required := v_required + 1;
    if r.portion_qty is null then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'problem', 'missing_portion_size');
    else
      v_priced := v_priced + 1;
    end if;
  end if;

  -- ---------------- floor cost per portion ----------------
  -- A floor of zero is not a floor, it is noise. When NOTHING is priced we
  -- know nothing, and "your cost is at least N0.00" would be false comfort.
  -- In that case the floor is NULL and the UI shows the missing item list.
  if core.priced_inputs = 0 then
    v_floor_pp := null;
  elsif core.cost_per_yield_unit is not null and r.portion_qty is not null then
    v_floor_pp := core.cost_per_yield_unit * r.portion_qty + coalesce(v_overhead, 0);
  else
    v_floor_pp := null;
  end if;

  -- Final safety net: any recorded problem forces incompleteness
  if jsonb_array_length(v_unpriced) > 0 then
    v_complete := false;
  end if;

  insert into cost_snapshots (
    account_id, business_id, recipe_id, computed_at,
    costing_method, wavg_window_days,
    is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
    ingredient_cost, packaging_cost, labour_cost, overhead_cost,
    batch_cost, cost_per_yield_unit, cost_per_portion,
    floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
    created_by)
  values (
    r.account_id, r.business_id, p_recipe_id, now(),
    bs.costing_method, bs.wavg_window_days,
    v_complete, v_required, v_priced, core.excluded_inputs, v_unpriced,
    core.ingredient_cost, core.packaging_cost, core.labour_cost, v_overhead,
    -- Gated columns: NULL unless complete
    case when v_complete then core.batch_cost end,
    case when v_complete then core.cost_per_yield_unit end,
    case when v_complete then v_floor_pp end,
    -- Floor columns: what IS known, or NULL when nothing is known
    case when core.priced_inputs > 0 then core.batch_cost end,
    case when core.priced_inputs > 0 then core.cost_per_yield_unit end,
    v_floor_pp,
    p_created_by)
  returning id into v_snapshot;

  return v_snapshot;
end;
$$;

comment on function fn_compute_recipe_cost_snapshot(uuid, date, uuid) is
  'Computes and writes a new immutable cost snapshot. Never modifies an '
  'existing one. Gated cost columns are NULL unless every required cost '
  'bearing input is priced and resolvable.';

-- ---------------------------------------------------------------- 0008_snapshot_and_pricing_engine.sql
-- ============================================================================
-- MENU MASTER NG
-- 0008: snapshot propagation and the pricing gate
--
-- A price change writes a NEW snapshot for every affected recipe, including
-- parents that use the ingredient through a sub recipe. Old snapshots are
-- never touched, so last month's margin stays exactly what it was.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Which recipes depend on an ingredient, directly or through sub recipes
-- ----------------------------------------------------------------------------

create or replace function fn_recipes_using_ingredient(p_ingredient_id uuid)
returns setof uuid
language sql stable security definer set search_path = public
as $$
  with recursive direct as (
    select distinct rl.recipe_id
    from recipe_lines rl
    where rl.ingredient_id = p_ingredient_id
  ),
  ascend as (
    select recipe_id from direct
    union
    select rl.recipe_id
    from recipe_lines rl
    join ascend a on rl.sub_recipe_id = a.recipe_id
  )
  select distinct a.recipe_id
  from ascend a
  join recipes r on r.id = a.recipe_id
  where r.deleted_at is null;
$$;

-- ----------------------------------------------------------------------------
-- 2. Recompute
-- ----------------------------------------------------------------------------

create or replace function fn_recompute_recipes_for_ingredient(
  p_ingredient_id uuid, p_as_of date default current_date)
returns integer
language plpgsql security definer set search_path = public
as $$
declare v_id uuid; v_n integer := 0;
begin
  for v_id in select * from fn_recipes_using_ingredient(p_ingredient_id) loop
    perform fn_compute_recipe_cost_snapshot(v_id, p_as_of, auth.uid());
    v_n := v_n + 1;
  end loop;
  return v_n;
end;
$$;

create or replace function fn_trg_price_change_recompute()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  perform fn_recompute_recipes_for_ingredient(
    coalesce(new.ingredient_id, old.ingredient_id), current_date);
  return null;
end;
$$;

create trigger trg_ingredient_prices_recompute
  after insert or update on ingredient_prices
  for each row execute function fn_trg_price_change_recompute();

create trigger trg_conversion_recompute
  after insert or update or delete on ingredient_unit_conversions
  for each row execute function fn_trg_price_change_recompute();

-- Yield is a costing input. Changing it must produce new snapshots.
create or replace function fn_trg_ingredient_change_recompute()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.purchase_yield_pct is distinct from old.purchase_yield_pct
     or new.base_unit_id is distinct from old.base_unit_id then
    perform fn_recompute_recipes_for_ingredient(new.id, current_date);
  end if;
  return null;
end;
$$;

create trigger trg_ingredients_recompute
  after update on ingredients
  for each row execute function fn_trg_ingredient_change_recompute();

-- ----------------------------------------------------------------------------
-- 3. THE PRICING GATE
-- Rebuilt on the floor columns. profit, margin_pct and recommended_price are
-- NULL whenever the current snapshot is incomplete. There is no code path,
-- screen or export that can produce them otherwise.
-- ----------------------------------------------------------------------------

drop view if exists v_price_check;

create view v_price_check with (security_invoker = on) as
with latest as (
  select distinct on (recipe_id) *
  from cost_snapshots
  order by recipe_id, computed_at desc
)
select
  r.id                          as recipe_id,
  r.business_id,
  r.account_id,
  r.name,
  ch.id                         as channel_id,
  ch.name                       as channel_name,

  -- Completeness reporting, always visible
  coalesce(s.is_complete, false) as is_complete,
  s.required_inputs,
  s.priced_inputs,
  s.excluded_inputs,
  coalesce(s.unpriced_items, '[]'::jsonb) as unpriced_items,

  -- The floor is shown whether complete or not. It is labelled as a floor.
  s.floor_cost_per_portion      as cost_floor_per_portion,

  -- GATED. NULL unless complete.
  s.cost_per_portion,
  p.price                       as selling_price,

  case when s.is_complete and p.price is not null
       then round(p.price - s.cost_per_portion, 2) end                       as profit,

  case when s.is_complete and p.price is not null and p.price > 0
       then round(100.0 * (p.price - s.cost_per_portion) / p.price, 2) end   as margin_pct,

  case when s.is_complete and s.cost_per_portion is not null
        and coalesce(ch.target_margin, bs.default_target_margin) < 100
       then ceil(
              (s.cost_per_portion
                 / (1 - coalesce(ch.target_margin, bs.default_target_margin) / 100.0))
              / bs.price_rounding_to
            ) * bs.price_rounding_to
  end                                                                        as recommended_price,

  coalesce(ch.target_margin, bs.default_target_margin) as target_margin,
  bs.price_rounding_to,
  ch.commission_pct
from recipes r
join business_settings bs on bs.business_id = r.business_id
left join latest s on s.recipe_id = r.id
left join channels ch on ch.business_id = r.business_id and ch.is_active
left join lateral (
  select rp.price
  from recipe_prices rp
  where rp.recipe_id = r.id
    and (rp.channel_id is null or rp.channel_id = ch.id)
    and rp.effective_from <= current_date
  order by rp.effective_from desc, rp.created_at desc
  limit 1
) p on true
where r.kind = 'dish' and r.deleted_at is null;

comment on view v_price_check is
  'Database level pricing gate. profit, margin_pct and recommended_price are '
  'NULL unless the current cost snapshot is complete. The UI cannot override this.';

-- ----------------------------------------------------------------------------
-- 4. What is stopping each dish from costing
-- ----------------------------------------------------------------------------

create or replace view v_costing_blockers with (security_invoker = on) as
with latest as (
  select distinct on (recipe_id) * from cost_snapshots
  order by recipe_id, computed_at desc
)
select
  r.account_id, r.business_id, r.id as recipe_id, r.name,
  s.required_inputs, s.priced_inputs, s.excluded_inputs,
  item ->> 'problem'          as problem,
  item ->> 'ingredient_name'  as ingredient_name,
  item ->> 'unit'             as unit_code,
  item
from recipes r
join latest s on s.recipe_id = r.id
cross join lateral jsonb_array_elements(s.unpriced_items) as item
where not s.is_complete and r.deleted_at is null;

-- ---------------------------------------------------------------- 0009_sales_freeze_and_profitability.sql
-- ============================================================================
-- MENU MASTER NG
-- 0009: sales cost freeze and profitability
--
-- At the moment of sale the current cost snapshot is stamped onto the line.
-- Nothing that happens afterwards can move it: not a price change, not a
-- recipe edit, not a new conversion, not a yield correction, not a repricing.
--
-- If the cost was incomplete at sale time, both cost_snapshot_id and
-- unit_cost_at_sale stay NULL. Revenue counts. COGS does not. The gap is
-- reported as cost_coverage_pct rather than hidden.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Freeze on insert
-- ----------------------------------------------------------------------------

create or replace function fn_freeze_sale_cost()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  s cost_snapshots%rowtype;
begin
  if new.recipe_id is null then
    new.cost_snapshot_id  := null;
    new.unit_cost_at_sale := null;
    return new;
  end if;

  select * into s
  from cost_snapshots
  where recipe_id = new.recipe_id
  order by computed_at desc
  limit 1;

  -- The gate applies here too. An incomplete cost is not a cost.
  if not found or not s.is_complete or s.cost_per_portion is null then
    new.cost_snapshot_id  := null;
    new.unit_cost_at_sale := null;
  else
    new.cost_snapshot_id  := s.id;
    new.unit_cost_at_sale := s.cost_per_portion;
  end if;

  return new;
end;
$$;

create trigger trg_order_lines_freeze
  before insert on order_lines
  for each row execute function fn_freeze_sale_cost();

create trigger trg_sales_entries_freeze
  before insert on sales_entries
  for each row execute function fn_freeze_sale_cost();

-- ----------------------------------------------------------------------------
-- 2. The frozen cost is immutable
-- ----------------------------------------------------------------------------

create or replace function fn_guard_frozen_cost()
returns trigger language plpgsql as $$
begin
  if new.cost_snapshot_id is distinct from old.cost_snapshot_id
     or new.unit_cost_at_sale is distinct from old.unit_cost_at_sale then
    raise exception
      'The cost frozen at sale time cannot be changed. Reverse the sale instead.'
      using errcode='check_violation';
  end if;
  return new;
end;
$$;

create trigger trg_order_lines_frozen
  before update on order_lines
  for each row execute function fn_guard_frozen_cost();

create trigger trg_sales_entries_frozen
  before update on sales_entries
  for each row execute function fn_guard_frozen_cost();

-- ----------------------------------------------------------------------------
-- 3. Profitability, rebuilt on the frozen figures
-- ----------------------------------------------------------------------------

drop view if exists v_profit_by_period;
drop view if exists v_profit_by_product;
drop view if exists v_sales_unified;

create view v_sales_unified with (security_invoker = on) as
select
  ol.account_id, o.business_id, o.order_date as sale_date, o.channel_id,
  ol.recipe_id, ol.qty, ol.unit_price,
  ol.line_total as revenue,
  ol.unit_cost_at_sale,
  ol.cost_snapshot_id,
  case when ol.unit_cost_at_sale is not null
       then ol.qty * ol.unit_cost_at_sale end as cogs,
  'order'::text as source
from order_lines ol
join orders o on o.id = ol.order_id
where o.status <> 'cancelled'
union all
select
  se.account_id, se.business_id, se.sale_date, se.channel_id,
  se.recipe_id, se.qty, se.unit_price,
  se.qty * se.unit_price,
  se.unit_cost_at_sale,
  se.cost_snapshot_id,
  case when se.unit_cost_at_sale is not null
       then se.qty * se.unit_cost_at_sale end,
  'daily_total'
from sales_entries se;

create view v_profit_by_period with (security_invoker = on) as
select
  account_id,
  business_id,
  date_trunc('month', sale_date)::date as period,
  round(sum(revenue), 2)                                  as revenue,
  round(sum(cogs), 2)                                     as cogs,
  round(sum(revenue) - coalesce(sum(cogs), 0), 2)         as gross_profit,
  round(100.0 * (sum(revenue) - coalesce(sum(cogs), 0))
        / nullif(sum(revenue), 0), 2)                     as gross_margin_pct,
  -- Share of revenue with a complete cost behind it. Anything below 100
  -- means the profit figure above is partial, and the UI must say so.
  round(100.0 * sum(case when unit_cost_at_sale is not null then revenue else 0 end)
        / nullif(sum(revenue), 0), 2)                     as cost_coverage_pct,
  round(sum(case when unit_cost_at_sale is null then revenue else 0 end), 2)
                                                          as revenue_without_cost
from v_sales_unified
group by account_id, business_id, date_trunc('month', sale_date);

create view v_profit_by_product with (security_invoker = on) as
select
  s.account_id,
  s.business_id,
  s.recipe_id,
  r.name,
  round(sum(s.qty), 3)                              as units_sold,
  round(sum(s.revenue), 2)                          as revenue,
  round(sum(s.cogs), 2)                             as cogs,
  round(sum(s.revenue) - coalesce(sum(s.cogs), 0), 2) as gross_profit,
  round(100.0 * (sum(s.revenue) - coalesce(sum(s.cogs), 0))
        / nullif(sum(s.revenue), 0), 2)             as gross_margin_pct,
  round(100.0 * sum(case when s.unit_cost_at_sale is not null then s.revenue else 0 end)
        / nullif(sum(s.revenue), 0), 2)             as cost_coverage_pct
from v_sales_unified s
join recipes r on r.id = s.recipe_id
group by s.account_id, s.business_id, s.recipe_id, r.name;

-- The dashboard waterfall for a period
create or replace view v_dashboard_waterfall with (security_invoker = on) as
select
  business_id,
  account_id,
  period,
  revenue,
  cogs,
  gross_profit,
  gross_margin_pct,
  cost_coverage_pct,
  revenue_without_cost,
  case when cost_coverage_pct is null then 'no_sales'
       when cost_coverage_pct >= 100 then 'complete'
       when cost_coverage_pct >= 80  then 'mostly_covered'
       else 'partial' end as confidence
from v_profit_by_period;

-- ---------------------------------------------------------------- 0010_onboarding.sql
-- ============================================================================
-- MENU MASTER NG
-- 0010: onboarding
--
-- One atomic call creates everything a new owner needs to reach the first
-- costing screen: account, owner membership, business, default location,
-- settings, starter catalogue and a trial subscription.
--
-- It seeds NO prices, NO conversions and NO purchase yields. Those are the
-- owner's data and the product is worthless if we guess them.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Plans. These are OUR product prices, not food prices.
-- ----------------------------------------------------------------------------

insert into plans (id, name, monthly_price, currency, is_active) values
  ('trial',    'Free Trial',      0, 'NGN', true),
  ('costing',  'Costing',         0, 'NGN', true),
  ('trading',  'Costing + Sales', 0, 'NGN', true)
on conflict (id) do nothing;

-- Monthly prices are 0 pending your commercial decision. They are values in
-- a table, so changing them is an update, never a deployment.

insert into plan_features (plan_id, feature_key, limit_value, is_enabled) values
  ('trial',   'level',        1,    true),
  ('trial',   'businesses',   1,    true),
  ('trial',   'users',        2,    true),
  ('trial',   'recipes',      20,   true),
  ('costing', 'level',        1,    true),
  ('costing', 'businesses',   1,    true),
  ('costing', 'users',        3,    true),
  ('costing', 'recipes',      null, true),
  ('trading', 'level',        2,    true),
  ('trading', 'businesses',   3,    true),
  ('trading', 'users',        10,   true),
  ('trading', 'recipes',      null, true)
on conflict (plan_id, feature_key) do nothing;

-- ----------------------------------------------------------------------------
-- 2. Atomic account creation
-- ----------------------------------------------------------------------------

create or replace function fn_create_account_and_business(
  p_account_name   text,
  p_business_name  text,
  p_business_type  business_type default 'other',
  p_user_id        uuid default auth.uid(),
  p_currency       text default 'NGN',
  p_plan_id        text default 'trial',
  p_trial_days     integer default 14
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account   uuid;
  v_business  uuid;
  v_location  uuid;
  v_slug      text;
  v_cloned    integer;
begin
  if p_user_id is null then
    raise exception 'A user is required to own the account';
  end if;
  if not exists (select 1 from auth.users where id = p_user_id) then
    raise exception 'User % does not exist', p_user_id;
  end if;
  if coalesce(btrim(p_account_name),'') = '' or coalesce(btrim(p_business_name),'') = '' then
    raise exception 'Account name and business name are required';
  end if;

  -- 1. account
  insert into accounts (name) values (btrim(p_account_name))
  returning id into v_account;

  -- 2. owner membership, account wide
  insert into memberships (account_id, business_id, user_id, role)
  values (v_account, null, p_user_id, 'owner');

  -- 3. business
  v_slug := regexp_replace(lower(btrim(p_business_name)), '[^a-z0-9]+', '-', 'g');
  v_slug := btrim(v_slug, '-');
  insert into businesses (account_id, name, slug, type)
  values (v_account, btrim(p_business_name), v_slug, p_business_type)
  returning id into v_business;

  -- 4. default location, hidden in the MVP UI
  insert into locations (account_id, business_id, name, is_default)
  values (v_account, v_business, 'Main', true)
  returning id into v_location;

  -- 5. settings. Financial defaults only, no market assumptions.
  insert into business_settings (business_id, account_id, currency)
  values (v_business, v_account, p_currency);

  -- 6. default sales channel
  insert into channels (account_id, business_id, name, is_default)
  values (v_account, v_business, 'Direct', true);

  -- 7. starter catalogue: names, categories, units. Nothing priced.
  v_cloned := fn_clone_starter_catalog(v_account, p_business_type);

  -- 8. trial subscription
  insert into subscriptions (account_id, plan_id, status, trial_ends_at, current_period_end)
  values (v_account, p_plan_id, 'trialing',
          now() + (p_trial_days || ' days')::interval,
          now() + (p_trial_days || ' days')::interval);

  return jsonb_build_object(
    'account_id',        v_account,
    'business_id',       v_business,
    'location_id',       v_location,
    'ingredients_added', v_cloned,
    'next_step',         'enter_your_own_prices');
end;
$$;

comment on function fn_create_account_and_business is
  'Atomic onboarding. Seeds no prices, no conversions and no purchase yields.';

-- ----------------------------------------------------------------------------
-- 3. Activation progress, drives the onboarding checklist
-- ----------------------------------------------------------------------------

create or replace view v_onboarding_status with (security_invoker = on) as
select
  b.account_id,
  b.id as business_id,
  b.name,
  (select count(*) from ingredients i
     where i.account_id = b.account_id and i.deleted_at is null)          as ingredients,
  (select count(*) from ingredient_prices ip
     where ip.account_id = b.account_id and ip.reversed_at is null)       as prices_entered,
  (select count(*) from recipes r
     where r.business_id = b.id and r.deleted_at is null)                 as recipes,
  (select count(*) from cost_snapshots s
     where s.business_id = b.id and s.is_complete)                        as complete_costings,
  (select count(*) from v_missing_unit_conversions m
     where m.account_id = b.account_id and m.reason <> 'suggested')       as blocking_conversions,
  (select count(*) from recipe_prices rp
     join recipes r2 on r2.id = rp.recipe_id
     where r2.business_id = b.id)                                         as selling_prices_set
from businesses b
where b.deleted_at is null;

-- ---------------------------------------------------------------- 0011_grants_and_api_surface.sql
-- ============================================================================
-- MENU MASTER NG
-- 0011: API surface and grants
--
-- Supabase relies on default privileges to expose tables to the anon and
-- authenticated roles. Depending on that default is fragile: if it is ever
-- changed, or a table is created outside the dashboard, the app silently
-- breaks or, worse, a later blanket GRANT opens something that should stay
-- closed. Privileges are stated explicitly here.
--
-- RLS remains the gate. Grants only decide which tables the gate applies to.
-- ============================================================================

grant usage on schema public to anon, authenticated;

-- ----------------------------------------------------------------------------
-- 1. Reference data readable by anyone signed in or not
-- ----------------------------------------------------------------------------

grant select on units, catalog_categories, catalog_ingredients, plans, plan_features
  to anon, authenticated;

-- ----------------------------------------------------------------------------
-- 2. Tenant data: full DML for authenticated users, every row gated by RLS
-- ----------------------------------------------------------------------------

do $$
declare t text;
begin
  foreach t in array array[
    'accounts','profiles','businesses','locations','memberships','subscriptions',
    'ingredient_categories','ingredients','ingredient_unit_conversions',
    'suppliers','ingredient_prices','business_settings','costing_method_changes',
    'recipes','recipe_lines','labour_rates','recipe_labour','overhead_items',
    'cost_snapshots','channels','recipe_prices','purchases','purchase_lines',
    'customers','orders','order_lines','sales_entries','period_closes'
  ]
  loop
    execute format('grant select, insert, update, delete on %I to authenticated', t);
  end loop;
end $$;

-- The anon role gets nothing on tenant data. Not read, not write.
-- An unauthenticated request should return zero rows, not an empty policy match.

-- ----------------------------------------------------------------------------
-- 3. Views
-- ----------------------------------------------------------------------------

grant select on
  v_price_check, v_costing_blockers, v_missing_unit_conversions,
  v_recipe_cost_current, v_sales_unified, v_profit_by_period,
  v_profit_by_product, v_dashboard_waterfall, v_onboarding_status
  to authenticated;

-- ----------------------------------------------------------------------------
-- 4. Functions
-- Only the ones a client legitimately calls. The recursive costing internals
-- are not part of the API.
-- ----------------------------------------------------------------------------

revoke execute on function fn__recipe_cost_core(uuid, date, integer) from public, anon, authenticated;
revoke execute on function fn_guard_posted_purchase() from public, anon, authenticated;
revoke execute on function fn_guard_ingredient_prices() from public, anon, authenticated;
revoke execute on function fn_block_snapshot_mutation() from public, anon, authenticated;
revoke execute on function fn_freeze_sale_cost() from public, anon, authenticated;
revoke execute on function fn_guard_frozen_cost() from public, anon, authenticated;

grant execute on function
  fn_resolve_qty_to_base(uuid, numeric, uuid),
  fn_can_resolve_unit(uuid, uuid),
  fn_ingredient_unit_cost(uuid, uuid, date),
  fn_ingredient_usable_unit_cost(uuid, uuid, date),
  fn_compute_recipe_cost_snapshot(uuid, date, uuid),
  fn_recompute_recipes_for_ingredient(uuid, date),
  fn_purchase_blockers(uuid),
  fn_post_purchase(uuid),
  fn_reverse_purchase(uuid, text),
  fn_is_account_member(uuid),
  fn_can_see_costs(uuid),
  fn_create_account_and_business(text, text, business_type, uuid, text, text, integer),
  fn_clone_starter_catalog(uuid, business_type)
  to authenticated;

-- ----------------------------------------------------------------------------
-- 5. Sequences
-- ----------------------------------------------------------------------------

do $$
declare s text;
begin
  for s in select sequence_name from information_schema.sequences where sequence_schema='public'
  loop
    execute format('grant usage, select on sequence %I to authenticated', s);
  end loop;
end $$;

-- ---------------------------------------------------------------- 0012_gate1_authorization_hardening.sql
-- ============================================================================
-- MENU MASTER NG
-- 0012: GATE 1 AUTHORIZATION HARDENING
--
-- Closes the four P0 vulnerabilities proven in the forensic audit. Additive.
-- No earlier migration is rewritten.
--
-- THE DESIGN RULE THIS MIGRATION INTRODUCES:
--
--   A function must NEVER derive authority from a parameter the caller
--   supplied. It derives the owning account from the target row's own
--   relational chain, then asks whether THIS caller may act on THAT account.
--
-- Every SECURITY DEFINER function below previously trusted its arguments.
-- That is the whole vulnerability class, and it is closed uniformly.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. AUTHORIZATION PRIMITIVES
-- ----------------------------------------------------------------------------

-- Trusted backend context: the service role, a scheduled job, a migration,
-- or the SQL editor.
--
-- CRITICAL DETAIL, learned the hard way during Gate 1 testing:
-- do NOT use current_user or session_user here. Inside a SECURITY DEFINER
-- function both report the function OWNER, not the caller, so every guard
-- silently believed it was running as the billing system. The `role` GUC is
-- set by SET ROLE at the connection edge and is NOT changed by SECURITY
-- DEFINER, so it still reports what the client actually is.
--
-- A hostile client always arrives as 'authenticated' or 'anon'. PostgREST
-- connects as `authenticator`, which may only SET ROLE to anon,
-- authenticated or service_role, and a client cannot issue raw SQL through
-- PostgREST to change it.
--
-- Defence in depth: `authenticator` IS granted service_role, so anyone who
-- reaches a raw SQL channel could SET ROLE service_role. We therefore also
-- require the absence of an end-user JWT subject. A genuine service_role
-- key carries no `sub` claim; a hijacking end user always does.
create or replace function fn_is_service_context()
returns boolean
language sql stable
as $$
  select coalesce(current_setting('role', true), 'none')
           not in ('authenticated', 'anon')
     and coalesce(current_setting('request.jwt.claim.sub', true), '') = '';
$$;

create or replace function fn_has_account_role(
  p_account_id uuid,
  p_roles      member_role[]
)
returns boolean
language sql stable security definer set search_path = public
as $$
  select exists (
    select 1 from memberships m
    where m.account_id = p_account_id
      and m.user_id    = auth.uid()
      and m.role       = any(p_roles)
  );
$$;

-- Raising, rather than returning NULL, matters here. NULL already means
-- "not entered" in this system. An authorization failure must be
-- distinguishable from missing data, or the client cannot tell a locked
-- door from an empty room.
create or replace function fn_require_member(p_account_id uuid)
returns void
language plpgsql stable security definer set search_path = public
as $$
begin
  if fn_is_service_context() then return; end if;
  if p_account_id is null or not fn_is_account_member(p_account_id) then
    raise exception 'Not authorized for this account'
      using errcode = '42501';
  end if;
end;
$$;

create or replace function fn_require_cost_access(p_account_id uuid)
returns void
language plpgsql stable security definer set search_path = public
as $$
begin
  if fn_is_service_context() then return; end if;
  if p_account_id is null or not fn_is_account_member(p_account_id) then
    raise exception 'Not authorized for this account' using errcode = '42501';
  end if;
  if not fn_can_see_costs(p_account_id) then
    raise exception 'Your role does not permit access to cost information'
      using errcode = '42501';
  end if;
end;
$$;

create or replace function fn_require_account_role(
  p_account_id uuid, p_roles member_role[], p_action text)
returns void
language plpgsql stable security definer set search_path = public
as $$
begin
  if fn_is_service_context() then return; end if;
  if p_account_id is null or not fn_is_account_member(p_account_id) then
    raise exception 'Not authorized for this account' using errcode = '42501';
  end if;
  if not fn_has_account_role(p_account_id, p_roles) then
    raise exception 'Your role does not permit %', p_action using errcode = '42501';
  end if;
end;
$$;

-- ============================================================================
-- P0-1: COSTING AND CONVERSION RPCs
-- ============================================================================

-- The account comes from the BUSINESS ROW, not from the caller. Passing
-- another tenant's ingredient id now fails the ownership cross-check rather
-- than returning their cost.
create or replace function fn_ingredient_unit_cost(
  p_ingredient_id uuid,
  p_business_id   uuid,
  p_as_of         date default current_date
)
returns numeric
language plpgsql stable security definer set search_path = public
as $$
declare
  v_account_id uuid;
  v_ing_acct   uuid;
  v_window     integer;
  v_cost       numeric;
begin
  select account_id, wavg_window_days into v_account_id, v_window
  from business_settings where business_id = p_business_id;

  if v_account_id is null then
    return null;                                  -- unknown business
  end if;

  perform fn_require_cost_access(v_account_id);   -- AUTHORIZATION

  -- The ingredient must belong to the same account as the business.
  -- This blocks the mix-and-match parameter attack.
  select account_id into v_ing_acct from ingredients where id = p_ingredient_id;
  if v_ing_acct is distinct from v_account_id then
    raise exception 'Ingredient does not belong to this account'
      using errcode = '42501';
  end if;

  select sum(amount) / nullif(sum(qty_base), 0) into v_cost
  from ingredient_prices
  where ingredient_id = p_ingredient_id
    and account_id    = v_account_id
    and reversed_at is null
    and effective_date <= p_as_of
    and effective_date >  p_as_of - (v_window || ' days')::interval;

  if v_cost is null then
    select unit_cost into v_cost
    from ingredient_prices
    where ingredient_id = p_ingredient_id
      and account_id    = v_account_id
      and reversed_at is null
      and effective_date <= p_as_of
    order by effective_date desc, created_at desc
    limit 1;
  end if;

  return v_cost;   -- NULL still means not entered. Never zero.
end;
$$;

create or replace function fn_ingredient_usable_unit_cost(
  p_ingredient_id uuid, p_business_id uuid, p_as_of date default current_date)
returns numeric
language plpgsql stable security definer set search_path = public
as $$
declare v_cost numeric; v_yield numeric;
begin
  -- Delegates authorization to fn_ingredient_unit_cost, which raises.
  v_cost := fn_ingredient_unit_cost(p_ingredient_id, p_business_id, p_as_of);
  if v_cost is null then return null; end if;
  select purchase_yield_pct into v_yield from ingredients where id = p_ingredient_id;
  if v_yield is null or v_yield <= 0 then return null; end if;
  return v_cost / (v_yield / 100.0);
end;
$$;

-- A conversion is private measurement data: how many kg of rice fit in
-- this owner's paint. The account is derived from the ingredient itself.
create or replace function fn_resolve_qty_to_base(
  p_ingredient_id uuid,
  p_qty           numeric,
  p_unit_id       uuid
)
returns numeric
language plpgsql stable security definer set search_path = public
as $$
declare
  v_acct        uuid;
  v_base_unit   uuid;
  v_base_kind   unit_kind;
  v_base_factor numeric;
  v_kind        unit_kind;
  v_factor      numeric;
  v_unit_acct   uuid;
  v_specific    numeric;
begin
  if p_ingredient_id is null or p_unit_id is null or p_qty is null then
    return null;
  end if;

  select i.account_id, i.base_unit_id into v_acct, v_base_unit
  from ingredients i where i.id = p_ingredient_id and i.deleted_at is null;

  if v_base_unit is null then
    return null;                                  -- unknown ingredient
  end if;

  perform fn_require_member(v_acct);              -- AUTHORIZATION

  if p_unit_id = v_base_unit then
    return p_qty;
  end if;

  select u.kind, u.factor_to_base, u.account_id
    into v_kind, v_factor, v_unit_acct
  from units u where u.id = p_unit_id;

  if v_kind is null then return null; end if;
  if v_unit_acct is not null and v_unit_acct <> v_acct then return null; end if;

  select u.kind, u.factor_to_base into v_base_kind, v_base_factor
  from units u where u.id = v_base_unit;

  if v_factor is not null and v_kind = v_base_kind and coalesce(v_base_factor,0) > 0 then
    return p_qty * v_factor / v_base_factor;
  end if;

  select c.qty_in_base into v_specific
  from ingredient_unit_conversions c
  where c.ingredient_id = p_ingredient_id
    and c.unit_id       = p_unit_id
    and c.account_id    = v_acct;

  if v_specific is null then return null; end if;
  return p_qty * v_specific;
end;
$$;

create or replace function fn_recipes_using_ingredient(p_ingredient_id uuid)
returns setof uuid
language plpgsql stable security definer set search_path = public
as $$
declare v_acct uuid;
begin
  select account_id into v_acct from ingredients where id = p_ingredient_id;
  if v_acct is null then return; end if;
  perform fn_require_member(v_acct);              -- AUTHORIZATION

  return query
  with recursive direct as (
    select distinct rl.recipe_id from recipe_lines rl
    where rl.ingredient_id = p_ingredient_id
  ),
  ascend as (
    select recipe_id from direct
    union
    select rl.recipe_id from recipe_lines rl
    join ascend a on rl.sub_recipe_id = a.recipe_id
  )
  select distinct a.recipe_id
  from ascend a join recipes r on r.id = a.recipe_id
  where r.deleted_at is null;
end;
$$;

create or replace function fn_compute_recipe_cost_snapshot(
  p_recipe_id  uuid,
  p_as_of      date default current_date,
  p_created_by uuid default auth.uid()
)
returns uuid
language plpgsql security definer set search_path = public
as $$
declare
  r recipes%rowtype; bs business_settings%rowtype; core recipe_cost_result;
  v_overhead numeric := 0; v_oh_total numeric;
  v_required integer; v_priced integer; v_unpriced jsonb; v_complete boolean;
  v_floor_pp numeric; v_snapshot uuid;
begin
  select * into r from recipes where id = p_recipe_id and deleted_at is null;
  if not found then raise exception 'Recipe % not found', p_recipe_id; end if;

  perform fn_require_cost_access(r.account_id);   -- AUTHORIZATION

  select * into bs from business_settings where business_id = r.business_id;
  if not found then
    raise exception 'Business settings missing for business %', r.business_id;
  end if;

  core := fn__recipe_cost_core(p_recipe_id, p_as_of, 0);

  v_required := core.required_inputs;
  v_priced   := core.priced_inputs;
  v_unpriced := core.unpriced_items;
  v_complete := core.is_complete;

  if bs.overhead_enabled then
    v_required := v_required + 1;
    select sum(monthly_cost) into v_oh_total
    from overhead_items
    where business_id = r.business_id and is_active and monthly_cost is not null;

    if bs.expected_monthly_units is null or bs.expected_monthly_units <= 0
       or v_oh_total is null
       or exists (select 1 from overhead_items
                   where business_id = r.business_id and is_active and monthly_cost is null)
    then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'business_id', r.business_id,
        'problem', 'missing_overhead_config');
      v_overhead := null;
    else
      v_overhead := v_oh_total / bs.expected_monthly_units;
      v_priced   := v_priced + 1;
    end if;
  end if;

  if r.kind = 'dish' then
    v_required := v_required + 1;
    if r.portion_qty is null then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'problem', 'missing_portion_size');
    else
      v_priced := v_priced + 1;
    end if;
  end if;

  if core.priced_inputs = 0 then
    v_floor_pp := null;
  elsif core.cost_per_yield_unit is not null and r.portion_qty is not null then
    v_floor_pp := core.cost_per_yield_unit * r.portion_qty + coalesce(v_overhead, 0);
  else
    v_floor_pp := null;
  end if;

  if jsonb_array_length(v_unpriced) > 0 then
    v_complete := false;
  end if;

  insert into cost_snapshots (
    account_id, business_id, recipe_id, computed_at,
    costing_method, wavg_window_days,
    is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
    ingredient_cost, packaging_cost, labour_cost, overhead_cost,
    batch_cost, cost_per_yield_unit, cost_per_portion,
    floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
    created_by)
  values (
    r.account_id, r.business_id, p_recipe_id, now(),
    bs.costing_method, bs.wavg_window_days,
    v_complete, v_required, v_priced, core.excluded_inputs, v_unpriced,
    core.ingredient_cost, core.packaging_cost, core.labour_cost, v_overhead,
    case when v_complete then core.batch_cost end,
    case when v_complete then core.cost_per_yield_unit end,
    case when v_complete then v_floor_pp end,
    case when core.priced_inputs > 0 then core.batch_cost end,
    case when core.priced_inputs > 0 then core.cost_per_yield_unit end,
    v_floor_pp,
    p_created_by)
  returning id into v_snapshot;

  return v_snapshot;
end;
$$;

create or replace function fn_recompute_recipes_for_ingredient(
  p_ingredient_id uuid, p_as_of date default current_date)
returns integer
language plpgsql security definer set search_path = public
as $$
declare v_id uuid; v_n integer := 0; v_acct uuid;
begin
  select account_id into v_acct from ingredients where id = p_ingredient_id;
  if v_acct is null then return 0; end if;
  perform fn_require_cost_access(v_acct);         -- AUTHORIZATION

  for v_id in select * from fn_recipes_using_ingredient(p_ingredient_id) loop
    perform fn_compute_recipe_cost_snapshot(v_id, p_as_of, auth.uid());
    v_n := v_n + 1;
  end loop;
  return v_n;
end;
$$;

-- ============================================================================
-- P0-2: PURCHASE POSTING AND REVERSAL
-- Posting and reversing are financial acts. Owner or manager only.
-- ============================================================================

create or replace function fn_purchase_blockers(p_purchase_id uuid)
returns jsonb
language plpgsql stable security definer set search_path = public
as $$
declare v_acct uuid; v_out jsonb;
begin
  select account_id into v_acct from purchases where id = p_purchase_id;
  if v_acct is null then return '[]'::jsonb; end if;
  perform fn_require_member(v_acct);              -- AUTHORIZATION

  select coalesce(jsonb_agg(jsonb_build_object(
           'purchase_line_id', pl.id,
           'ingredient_id',    pl.ingredient_id,
           'ingredient_name',  i.name,
           'unit_id',          pl.unit_id,
           'unit_code',        u.code,
           'problem',          'missing_conversion')), '[]'::jsonb)
    into v_out
  from purchase_lines pl
  join ingredients i on i.id = pl.ingredient_id
  join units u on u.id = pl.unit_id
  where pl.purchase_id = p_purchase_id
    and fn_resolve_qty_to_base(pl.ingredient_id, pl.qty, pl.unit_id) is null;

  return v_out;
end;
$$;

create or replace function fn_post_purchase(p_purchase_id uuid)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_p purchases%rowtype; v_blockers jsonb; v_lines integer;
  v_written integer := 0; r record; v_base numeric;
begin
  -- Lock the row: closes the concurrent double-post race as a side effect
  -- of having to fetch it for the authorization check anyway.
  select * into v_p from purchases where id = p_purchase_id for update;
  if not found then raise exception 'Purchase % not found', p_purchase_id; end if;

  perform fn_require_account_role(v_p.account_id,
    array['owner','manager']::member_role[], 'posting purchases');   -- AUTHORIZATION

  if v_p.status <> 'draft' then
    raise exception 'Purchase % is already %', p_purchase_id, v_p.status
      using errcode='check_violation';
  end if;

  select count(*) into v_lines from purchase_lines where purchase_id = p_purchase_id;
  if v_lines = 0 then
    raise exception 'Purchase % has no lines', p_purchase_id using errcode='check_violation';
  end if;

  v_blockers := fn_purchase_blockers(p_purchase_id);
  if jsonb_array_length(v_blockers) > 0 then
    return jsonb_build_object('posted', false,
      'reason', 'unresolved_conversions', 'blockers', v_blockers);
  end if;

  for r in select * from purchase_lines where purchase_id = p_purchase_id loop
    v_base := fn_resolve_qty_to_base(r.ingredient_id, r.qty, r.unit_id);
    if v_base is null or v_base <= 0 then
      raise exception 'Line % did not resolve. Refusing to post.', r.id
        using errcode='check_violation';
    end if;
    update purchase_lines set qty_base = v_base where id = r.id;
    insert into ingredient_prices (
      account_id, ingredient_id, supplier_id, purchase_line_id,
      qty_base, amount, source, effective_date, entered_by)
    values (v_p.account_id, r.ingredient_id, v_p.supplier_id, r.id,
      v_base, r.amount, 'purchase', v_p.purchase_date, auth.uid());
    v_written := v_written + 1;
  end loop;

  update purchases set status='posted', posted_at=now(), posted_by=auth.uid()
   where id = p_purchase_id;

  return jsonb_build_object('posted', true,
    'purchase_id', p_purchase_id, 'price_rows_written', v_written);
end;
$$;

create or replace function fn_reverse_purchase(
  p_purchase_id uuid, p_reason text)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare v_p purchases%rowtype; v_rev_id uuid; v_marked integer;
begin
  select * into v_p from purchases where id = p_purchase_id for update;
  if not found then raise exception 'Purchase % not found', p_purchase_id; end if;

  -- AUTHORIZATION. Ownership is derived from the purchase row itself,
  -- never from a business id the caller supplied.
  perform fn_require_account_role(v_p.account_id,
    array['owner','manager']::member_role[], 'reversing purchases');

  if v_p.status <> 'posted' then
    raise exception 'Only a posted purchase can be reversed. This one is %', v_p.status
      using errcode='check_violation';
  end if;
  if p_reason is null or btrim(p_reason) = '' then
    raise exception 'A reversal requires a reason' using errcode='check_violation';
  end if;

  insert into purchases (
    account_id, business_id, location_id, supplier_id, purchase_date,
    reference, note, status, reverses, reversal_reason, created_by, posted_at, posted_by)
  values (
    v_p.account_id, v_p.business_id, v_p.location_id, v_p.supplier_id, current_date,
    coalesce(v_p.reference,'') || ' (reversal)', v_p.note, 'reversed',
    v_p.id, p_reason, auth.uid(), now(), auth.uid())
  returning id into v_rev_id;

  update ingredient_prices ip
     set reversed_at = now(), reversed_by_purchase_id = v_rev_id
   where ip.purchase_line_id in (select id from purchase_lines where purchase_id = p_purchase_id)
     and ip.reversed_at is null;
  get diagnostics v_marked = row_count;

  update purchases set status = 'reversed' where id = p_purchase_id;

  return jsonb_build_object('reversed', true,
    'original_purchase_id', p_purchase_id,
    'reversal_purchase_id', v_rev_id,
    'price_rows_reversed', v_marked);
end;
$$;

-- ============================================================================
-- P0-3: MEMBERSHIP AND ROLE ELEVATION
--
-- The old policy asked only "are you in this account". The row that GRANTS
-- authority was therefore writable by anyone it would grant authority over.
-- Writes now require an EXISTING owner, which a self-promoting cashier
-- by definition is not.
-- ============================================================================

drop policy if exists p_memberships on memberships;

create policy p_memberships_select on memberships
  for select using (fn_is_account_member(account_id));

create policy p_memberships_insert on memberships
  for insert with check (fn_has_account_role(account_id, array['owner']::member_role[]));

create policy p_memberships_update on memberships
  for update using      (fn_has_account_role(account_id, array['owner']::member_role[]))
             with check (fn_has_account_role(account_id, array['owner']::member_role[]));

create policy p_memberships_delete on memberships
  for delete using (fn_has_account_role(account_id, array['owner']::member_role[]));

-- An account must never lose its last owner, or it becomes unadministrable
-- and no one can ever grant a role in it again.
create or replace function fn_guard_last_owner()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_owners integer; v_acct uuid;
begin
  v_acct := coalesce(old.account_id, new.account_id);
  if tg_op = 'DELETE' or (tg_op = 'UPDATE' and old.role = 'owner' and new.role <> 'owner') then
    select count(*) into v_owners from memberships
     where account_id = v_acct and role = 'owner'
       and id <> old.id;
    if v_owners = 0 then
      raise exception 'An account must retain at least one owner'
        using errcode = 'check_violation';
    end if;
  end if;
  return coalesce(new, old);
end;
$$;

create trigger trg_memberships_last_owner
  before update or delete on memberships
  for each row execute function fn_guard_last_owner();

-- Onboarding creates the first owner. Force the owner to be the caller, so
-- the function cannot be used to mint an owner membership for anyone else.
create or replace function fn_create_account_and_business(
  p_account_name   text,
  p_business_name  text,
  p_business_type  business_type default 'other',
  p_user_id        uuid default auth.uid(),
  p_currency       text default 'NGN',
  p_plan_id        text default 'trial',
  p_trial_days     integer default 14
)
returns jsonb
language plpgsql security definer set search_path = public
as $$
declare
  v_account uuid; v_business uuid; v_location uuid; v_slug text;
  v_cloned integer; v_user uuid;
begin
  -- A client may only create an account for itself. Service context may
  -- still act on behalf of a user, for support and migration purposes.
  if fn_is_service_context() then
    v_user := coalesce(p_user_id, auth.uid());
  else
    v_user := auth.uid();
    if p_user_id is not null and p_user_id <> v_user then
      raise exception 'You may only create an account for yourself'
        using errcode = '42501';
    end if;
  end if;

  if v_user is null then
    raise exception 'A user is required to own the account';
  end if;
  if not exists (select 1 from auth.users where id = v_user) then
    raise exception 'User % does not exist', v_user;
  end if;
  if coalesce(btrim(p_account_name),'') = '' or coalesce(btrim(p_business_name),'') = '' then
    raise exception 'Account name and business name are required';
  end if;

  insert into accounts (name) values (btrim(p_account_name)) returning id into v_account;

  insert into memberships (account_id, business_id, user_id, role)
  values (v_account, null, v_user, 'owner');

  v_slug := btrim(regexp_replace(lower(btrim(p_business_name)), '[^a-z0-9]+', '-', 'g'), '-');
  insert into businesses (account_id, name, slug, type)
  values (v_account, btrim(p_business_name), v_slug, p_business_type)
  returning id into v_business;

  insert into locations (account_id, business_id, name, is_default)
  values (v_account, v_business, 'Main', true) returning id into v_location;

  insert into business_settings (business_id, account_id, currency)
  values (v_business, v_account, p_currency);

  insert into channels (account_id, business_id, name, is_default)
  values (v_account, v_business, 'Direct', true);

  v_cloned := fn_clone_starter_catalog(v_account, p_business_type);

  insert into subscriptions (account_id, plan_id, status, trial_ends_at, current_period_end)
  values (v_account, p_plan_id, 'trialing',
          now() + (p_trial_days || ' days')::interval,
          now() + (p_trial_days || ' days')::interval);

  return jsonb_build_object(
    'account_id', v_account, 'business_id', v_business, 'location_id', v_location,
    'ingredients_added', v_cloned, 'next_step', 'enter_your_own_prices');
end;
$$;

-- The catalogue clone writes into an account. Owners only.
create or replace function fn_clone_starter_catalog(
  p_account_id uuid, p_type business_type default null)
returns integer
language plpgsql security definer set search_path = public
as $$
declare v_count integer;
begin
  perform fn_require_account_role(p_account_id,
    array['owner']::member_role[], 'loading the starter catalogue');  -- AUTHORIZATION

  insert into ingredient_categories (account_id, name)
  select p_account_id, c.name from catalog_categories c
  where not exists (select 1 from ingredient_categories ic
                     where ic.account_id = p_account_id and ic.name = c.name);

  insert into ingredients (account_id, kind, name, category_id, base_unit_id)
  select p_account_id, ci.kind, ci.name, ic.id, u.id
  from catalog_ingredients ci
  join ingredient_categories ic on ic.account_id = p_account_id and ic.name = ci.category_name
  join units u on u.account_id is null and u.code = ci.base_unit
  where (ci.applies_to is null or p_type is null or p_type = any(ci.applies_to))
    and not exists (select 1 from ingredients i
                     where i.account_id = p_account_id and lower(i.name) = lower(ci.name));

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ============================================================================
-- P0-4: SUBSCRIPTION ENTITLEMENT
-- Entitlement is not client state. Read only from the client; changes come
-- from the payment webhook or support tooling running as service role.
-- ============================================================================

drop policy if exists p_subscriptions on subscriptions;

create policy p_subscriptions_select on subscriptions
  for select using (fn_is_account_member(account_id));

revoke insert, update, delete on subscriptions from authenticated;

-- Belt and braces: even if a future migration re-grants DML by accident,
-- the trigger refuses a client-originated write.
-- Entitlement is not client state. But onboarding legitimately creates a
-- TRIAL subscription on behalf of a brand new user, so a blanket
-- service-only rule breaks self-signup. The rule is therefore:
--   a client may create ONE trialing subscription on a plan explicitly
--   marked self-serve, and may never update or delete any subscription.
alter table plans add column if not exists is_self_serve_trial boolean not null default false;
update plans set is_self_serve_trial = true where id = 'trial';

create or replace function fn_guard_subscription_writes()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_existing integer;
begin
  if fn_is_service_context() then
    return coalesce(new, old);
  end if;

  if tg_op <> 'INSERT' then
    raise exception 'Subscription changes must go through the billing system'
      using errcode = '42501';
  end if;

  select count(*) into v_existing from subscriptions where account_id = new.account_id;
  if v_existing > 0 then
    raise exception 'This account already has a subscription' using errcode = '42501';
  end if;

  if new.status <> 'trialing'
     or not exists (select 1 from plans
                     where id = new.plan_id and is_active and is_self_serve_trial) then
    raise exception 'Only a trial subscription can be created without billing'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger trg_subscriptions_guard
  before insert or update or delete on subscriptions
  for each row execute function fn_guard_subscription_writes();

-- The legitimate path, for the Paystack webhook running as service role.
create or replace function fn_set_subscription_plan(
  p_account_id uuid,
  p_plan_id    text,
  p_status     text default 'active',
  p_period_end timestamptz default null,
  p_provider_ref text default null
)
returns jsonb
language plpgsql security definer set search_path = public
as $$
begin
  if not fn_is_service_context() then
    raise exception 'Only the billing system may change a subscription'
      using errcode = '42501';
  end if;
  if not exists (select 1 from plans where id = p_plan_id and is_active) then
    raise exception 'Unknown or inactive plan %', p_plan_id;
  end if;

  update subscriptions
     set plan_id = p_plan_id,
         status  = p_status,
         current_period_end = coalesce(p_period_end, current_period_end),
         provider_ref = coalesce(p_provider_ref, provider_ref)
   where account_id = p_account_id;

  return jsonb_build_object('account_id', p_account_id, 'plan_id', p_plan_id);
end;
$$;

-- ============================================================================
-- SWEEP: nothing internal should be callable by a client
-- ============================================================================

revoke execute on function fn_trg_price_change_recompute()      from public, anon, authenticated;
revoke execute on function fn_trg_ingredient_change_recompute() from public, anon, authenticated;
revoke execute on function fn_assert_unit_visible()             from public, anon, authenticated;
revoke execute on function fn_prevent_recipe_cycle()            from public, anon, authenticated;
revoke execute on function fn_guard_last_owner()                from public, anon, authenticated;
revoke execute on function fn_guard_subscription_writes()       from public, anon, authenticated;
revoke execute on function fn_set_subscription_plan(uuid, text, text, timestamptz, text)
                                                                from public, anon, authenticated;

grant execute on function
  fn_has_account_role(uuid, member_role[]),
  fn_is_service_context()
  to authenticated;

