-- ============================================================================
-- MENU MASTER NG — Part 2 of 5: container unit kind
--
-- DISPOSABLE / NON-PRODUCTION PROJECT ONLY.
-- Generated by scripts/build_deploy_chain.sh. Do not edit by hand.
-- Source migrations: 0002_unit_kind_container.sql
--
-- RUN THIS ALONE, in its own submission. ALTER TYPE ... ADD VALUE cannot run in the transaction that created the type.
-- ============================================================================

-- ---------------------------------------------------------------- 0002_unit_kind_container.sql
-- ============================================================================
-- MENU MASTER NG
-- Migration 0002: add the 'container' unit kind
--
-- THIS FILE MUST RUN ALONE, IN ITS OWN TRANSACTION.
--
-- A paint, basket, tuber or keg is not mass, volume or count. It is a
-- container or a natural item whose conversion to a base unit is specific
-- to the ingredient inside it. Giving it its own kind makes "this unit
-- needs a per ingredient conversion" a queryable fact rather than a
-- convention someone has to remember.
--
-- Postgres will not allow a newly added enum value to be USED in the same
-- transaction that added it. Migration 0003 inserts rows with kind =
-- 'container', so this alter has to commit first. Run 0002 on its own,
-- confirm success, then run 0003.
-- ============================================================================

alter type unit_kind add value if not exists 'container';

