-- ============================================================================
-- MENU MASTER NG — 004_gate1_closure.sql (Supabase SQL Editor build)
--
-- DISPOSABLE PROJECT ONLY. Never run against production.
-- Generated by scripts/build_supabase_suites.sh from tests/004_gate1_closure.sql.
-- Do not edit by hand. psql meta-commands stripped; nothing else changed.
--
-- The editor renders only the LAST result set, which is this suite's
-- passed/failed/total summary.
-- ============================================================================

-- ============================================================================
-- MENU MASTER NG
-- Test suite 004: GATE 1 CLOSURE
--
-- Covers migration 0013 (zero-value amounts) and 0014 (sales void-and-reissue).
-- Uses its own results table (_c1) so it never clobbers suite 001 (_test_results)
-- or suite 002 (_g1).
-- ============================================================================

set client_min_messages = warning;

create table if not exists _c1 (
  seq serial primary key, phase text, name text, passed boolean, detail text);
truncate _c1 restart identity;

create or replace function c(p_phase text, p_name text, p_ok boolean, p_detail text default null)
returns void language plpgsql as $$
begin insert into _c1 (phase,name,passed,detail) values (p_phase,p_name,coalesce(p_ok,false),p_detail); end; $$;

-- ============================================================================
-- FIXTURES (independent of suites 001/002)
-- ============================================================================
do $$
declare
  u uuid; onboard jsonb; acc uuid; biz uuid;
  rice uuid; tom uuid; u_kg uuid; u_g uuid;
begin
  insert into auth.users (id,email) values (gen_random_uuid(),'closure@test.local') returning id into u;
  onboard := fn_create_account_and_business('Closure Group','Closure Kitchen','soup_seller', u);
  acc := (onboard->>'account_id')::uuid;  biz := (onboard->>'business_id')::uuid;

  select id into u_kg from units where account_id is null and code='kg';
  select id into u_g  from units where account_id is null and code='g';
  select id into rice from ingredients where account_id=acc and name='Rice (local)';
  select id into tom  from ingredients where account_id=acc and name='Tomato';

  create temp table _cfx as select u, acc, biz, rice, tom, u_kg, u_g;
end $$;

-- ============================================================================
-- A3 / 0013 : ZERO-VALUE AMOUNTS
-- ============================================================================

-- TEST 37: a zero-value purchase line cannot be stored at all
do $$
declare f record; p uuid; ok boolean := false;
begin
  select * into f from _cfx;
  insert into purchases (account_id,business_id,purchase_date,reference)
  values (f.acc,f.biz,current_date,'T37') returning id into p;
  begin
    insert into purchase_lines (account_id,purchase_id,ingredient_id,qty,unit_id,amount)
    values (f.acc,p,f.rice,1,f.u_kg,0);
  exception when check_violation then ok := true;
  end;
  perform c('0013','T37 zero-value purchase line rejected at constraint level', ok);
  delete from purchases where id = p;
end $$;

-- TEST 38: negative still rejected
do $$
declare f record; p uuid; ok boolean := false;
begin
  select * into f from _cfx;
  insert into purchases (account_id,business_id,purchase_date,reference)
  values (f.acc,f.biz,current_date,'T38') returning id into p;
  begin
    insert into purchase_lines (account_id,purchase_id,ingredient_id,qty,unit_id,amount)
    values (f.acc,p,f.rice,1,f.u_kg,-500);
  exception when check_violation then ok := true;
  end;
  perform c('0013','T38 negative purchase line still rejected', ok);
  delete from purchases where id = p;
end $$;

-- TEST 40: the manual-price route is closed too
do $$
declare f record; ok boolean := false;
begin
  select * into f from _cfx;
  begin
    insert into ingredient_prices (account_id,ingredient_id,qty_base,amount,source,effective_date)
    values (f.acc,f.tom,1000,0,'manual',current_date);
  exception when check_violation then ok := true;
  end;
  perform c('0013','T40 zero-value manual ingredient price rejected', ok);
end $$;

-- TEST 41: the fix is "> 0", not a minimum threshold. A genuinely tiny amount stands.
do $$
declare f record; p uuid; res jsonb; ok boolean;
begin
  select * into f from _cfx;
  insert into purchases (account_id,business_id,purchase_date,reference)
  values (f.acc,f.biz,current_date,'T41') returning id into p;
  insert into purchase_lines (account_id,purchase_id,ingredient_id,qty,unit_id,amount)
  values (f.acc,p,f.rice,1,f.u_kg,0.01);
  res := fn_post_purchase(p);
  ok := (res->>'posted')::boolean;
  perform c('0013','T41 smallest legitimate amount (0.01) still posts', ok, res::text);
end $$;

-- TEST 39: defence in depth. The constraint is the first line; fn_post_purchase
-- is the second. This proves the second line works by removing the first,
-- exercising it, then restoring the constraint. The test row is deleted before
-- the constraint is re-added, so the table is left exactly as it was found.
alter table purchase_lines drop constraint ck_purchase_lines_amount_positive;

do $$
declare f record; p uuid; res jsonb; still_draft boolean; rows_written int;
begin
  select * into f from _cfx;
  insert into purchases (account_id,business_id,purchase_date,reference)
  values (f.acc,f.biz,current_date,'T39') returning id into p;
  insert into purchase_lines (account_id,purchase_id,ingredient_id,qty,unit_id,amount)
  values (f.acc,p,f.tom,1,f.u_kg,0);          -- only possible with the constraint gone

  res := fn_post_purchase(p);
  select status='draft' into still_draft from purchases where id = p;
  select count(*) into rows_written from ingredient_prices where ingredient_id = f.tom;

  perform c('0013','T39 fn_post_purchase refuses a zero-value line (defence in depth)',
    (res->>'posted')::boolean = false
      and res->>'reason' = 'zero_value_lines'
      and still_draft
      and rows_written = 0,
    res::text);

  delete from purchases where id = p;          -- draft, so deletion is permitted
end $$;

alter table purchase_lines add constraint ck_purchase_lines_amount_positive check (amount > 0);

do $$
declare n int;
begin
  select count(*) into n from pg_constraint where conname='ck_purchase_lines_amount_positive';
  perform c('0013','T39b constraint restored after the defence-in-depth test', n = 1);
end $$;

-- ============================================================================
-- A2 / 0014 : SALES VOID-AND-REISSUE AND REVENUE IMMUTABILITY
-- ============================================================================

-- Fixture: a fully priced dish so cost actually freezes at sale.
do $$
declare
  f record; p uuid; rid uuid; ord uuid; ol uuid;
begin
  select * into f from _cfx;

  insert into purchases (account_id,business_id,purchase_date,reference)
  values (f.acc,f.biz,current_date,'A2-BUY') returning id into p;
  insert into purchase_lines (account_id,purchase_id,ingredient_id,qty,unit_id,amount)
  values (f.acc,p,f.rice,10,f.u_kg,50000);        -- 10kg for 50,000 => 5/g
  perform fn_post_purchase(p);

  insert into recipes (account_id,business_id,kind,name,batch_yield_qty,yield_unit_id,
                       cooking_yield_pct,portion_qty,status)
  values (f.acc,f.biz,'dish','A2 Jollof',5000,f.u_g,100,500,'active') returning id into rid;
  insert into recipe_lines (account_id,recipe_id,ingredient_id,qty,unit_id)
  values (f.acc,rid,f.rice,1000,f.u_g);
  perform fn_compute_recipe_cost_snapshot(rid);

  insert into orders (account_id,business_id,order_no,order_date)
  values (f.acc,f.biz,'A2-ORD-1',current_date) returning id into ord;
  insert into order_lines (account_id,order_id,recipe_id,qty,unit_price)
  values (f.acc,ord,rid,2,3500) returning id into ol;

  create temp table _cfx2 as select rid, ord, ol;
end $$;

-- TEST 28 (before finalisation): a draft order is freely editable
do $$
declare g record; ok boolean := true;
begin
  select * into g from _cfx2;
  begin
    update order_lines set unit_price = 3600 where id = g.ol;
    update order_lines set unit_price = 3500 where id = g.ol;   -- put it back
  exception when others then ok := false;
  end;
  perform c('0014','T28 draft order lines remain freely editable', ok);
end $$;

-- Finalise it.
do $$
declare g record; res jsonb;
begin
  select * into g from _cfx2;
  res := fn_finalise_order(g.ord);
  perform c('0014','T23a order finalises', (res->>'finalised')::boolean, res::text);
end $$;

-- TEST 24 / 25 / 26 / 27: revenue is frozen once finalised
do $$
declare g record; ok boolean := false;
begin
  select * into g from _cfx2;
  begin update order_lines set unit_price = 9999 where id = g.ol;
  exception when others then ok := true; end;
  perform c('0014','T24 finalised line unit_price cannot be UPDATEd', ok);
end $$;

do $$
declare g record; ok boolean := false;
begin
  select * into g from _cfx2;
  begin update order_lines set qty = 99 where id = g.ol;
  exception when others then ok := true; end;
  perform c('0014','T25 finalised line qty cannot be UPDATEd', ok);
end $$;

do $$
declare g record; ok boolean := false;
begin
  select * into g from _cfx2;
  begin delete from order_lines where id = g.ol;
  exception when others then ok := true; end;
  perform c('0014','T26 finalised line cannot be DELETEd', ok);
end $$;

do $$
declare f record; g record; ok boolean := false;
begin
  select * into f from _cfx; select * into g from _cfx2;
  begin
    insert into order_lines (account_id,order_id,recipe_id,qty,unit_price)
    values (f.acc,g.ord,g.rid,1,1000);
  exception when others then ok := true; end;
  perform c('0014','T27 no new lines on a finalised order', ok);
end $$;

-- TEST 34: settlement may still move. Collecting money later is not a rewrite.
do $$
declare g record; ok boolean := true;
begin
  select * into g from _cfx2;
  begin
    update orders set payment_status='paid', amount_paid=7000 where id = g.ord;
  exception when others then ok := false; end;
  perform c('0014','T34 payment state still updatable after finalisation', ok);
end $$;

-- TEST 26b: a finalised order cannot be deleted either
do $$
declare g record; ok boolean := false;
begin
  select * into g from _cfx2;
  begin delete from orders where id = g.ord;
  exception when others then ok := true; end;
  perform c('0014','T26b finalised order cannot be DELETEd', ok);
end $$;

-- TEST 29: a void needs a reason
do $$
declare g record; ok boolean := false;
begin
  select * into g from _cfx2;
  begin perform fn_void_order(g.ord, '   ');
  exception when others then ok := true; end;
  perform c('0014','T29 void requires a non-empty reason', ok);
end $$;

-- TEST 30 / 33: void removes the money, preserves the record and the frozen cost
do $$
declare
  g record; f record; rev_before numeric; rev_after numeric;
  cost_before numeric; cost_after numeric; still_there boolean; res jsonb;
begin
  select * into f from _cfx; select * into g from _cfx2;
  select revenue into rev_before from v_profit_by_period where business_id = f.biz;
  select unit_cost_at_sale into cost_before from order_lines where id = g.ol;

  res := fn_void_order(g.ord, 'customer returned the order');

  select coalesce(revenue,0) into rev_after from v_profit_by_period where business_id = f.biz;
  select unit_cost_at_sale into cost_after from order_lines where id = g.ol;
  select exists(select 1 from orders where id = g.ord and voided_at is not null) into still_there;

  perform c('0014','T30 voided sale leaves revenue but the record survives',
    coalesce(rev_after,0) < rev_before and still_there,
    format('revenue %s -> %s, row present=%s', rev_before, coalesce(rev_after,0), still_there));

  perform c('0014','T33 voiding does not disturb the frozen unit_cost_at_sale',
    cost_before is not null and cost_before = cost_after,
    format('before=%s after=%s', cost_before, cost_after));

  perform c('0014','T30b voided sale is visible in the audit view',
    exists(select 1 from v_voided_sales where record_id = g.ord
             and void_reason = 'customer returned the order'));
end $$;

-- TEST 31 / 32: reissue carries the link and the corrected sale counts again
do $$
declare
  f record; g record; res jsonb; newid uuid; rev numeric; linked boolean;
begin
  select * into f from _cfx; select * into g from _cfx2;
  res := fn_reissue_order(g.ord);
  newid := (res->>'new_order_id')::uuid;

  select exists(select 1 from orders where id = newid and replaces = g.ord) into linked;
  perform c('0014','T31 reissued order carries replaces -> original', linked, res::text);

  insert into order_lines (account_id,order_id,recipe_id,qty,unit_price)
  values (f.acc,newid,g.rid,1,3500);
  perform fn_finalise_order(newid);

  select revenue into rev from v_profit_by_period where business_id = f.biz;
  perform c('0014','T32 corrected sale counts, voided original does not',
    rev = 3500, format('revenue=%s (expected 3500: 1 x 3500, original 2 x 3500 voided)', rev));
end $$;

-- TEST 36: sales_entries are immutable; correction is void + re-enter
do $$
declare f record; g record; se uuid; ok_u boolean := false; ok_d boolean := false; res jsonb;
begin
  select * into f from _cfx; select * into g from _cfx2;
  insert into sales_entries (account_id,business_id,sale_date,recipe_id,qty,unit_price)
  values (f.acc,f.biz,current_date,g.rid,3,3500) returning id into se;

  begin update sales_entries set unit_price = 1 where id = se;
  exception when others then ok_u := true; end;
  begin delete from sales_entries where id = se;
  exception when others then ok_d := true; end;

  perform c('0014','T36 recorded sales_entry cannot be UPDATEd or DELETEd', ok_u and ok_d);

  res := fn_void_sales_entry(se, 'miscount at close of day');
  perform c('0014','T36b sales_entry void path works and is auditable',
    (res->>'voided')::boolean
      and exists(select 1 from v_voided_sales where record_id = se));
end $$;

-- TEST 35: the Gate 1 R5 property must survive. A sales user records and
-- finalises a sale, the cost freezes correctly, and that user still cannot
-- read a single cost figure.
do $$
declare
  f record; g record; su uuid; ord2 uuid; froze numeric; saw_cost int; ok_fin boolean;
begin
  select * into f from _cfx; select * into g from _cfx2;
  insert into auth.users (id,email) values (gen_random_uuid(),'salesperson@test.local') returning id into su;
  insert into memberships (account_id,business_id,user_id,role) values (f.acc,null,su,'sales');

  set local role authenticated;
  perform set_config('request.jwt.claim.sub', su::text, true);

  insert into orders (account_id,business_id,order_no,order_date)
  values (f.acc,f.biz,'A2-SALES',current_date) returning id into ord2;
  insert into order_lines (account_id,order_id,recipe_id,qty,unit_price)
  values (f.acc,ord2,g.rid,1,3500);
  ok_fin := (fn_finalise_order(ord2)->>'finalised')::boolean;
  select count(*) into saw_cost from cost_snapshots;      -- RLS must hide these

  reset role;
  perform set_config('request.jwt.claim.sub','',true);

  select unit_cost_at_sale into froze from order_lines where order_id = ord2;

  perform c('0014','T35 sales role finalises a sale, cost freezes, cost stays invisible',
    ok_fin and froze is not null and saw_cost = 0,
    format('finalised=%s frozen_cost=%s snapshots_visible_to_sales=%s', ok_fin, froze, saw_cost));
end $$;

-- ============================================================================
-- RESULTS
-- ============================================================================
select seq, phase, case when passed then 'PASS' else 'FAIL' end as result, name from _c1 order by seq;
select count(*) filter (where passed) as passed,
       count(*) filter (where not passed) as failed,
       count(*) as total
from _c1;
