#!/usr/bin/env bash
# Generate the single controlled Phase 6 migration from the six source files.
# Regenerate rather than hand-edit: the sources are the truth, this is a bundle.
set -eu
R="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$R/deploy/runbook/PHASE6_MIGRATE.sql"
FILES=()
for n in 0034 0035 0036 0037 0038 0039 0040 0041 0042 0043 0044 0045 0046 0047 0048; do
  FILES+=("$(ls "$R"/migrations/proposed/${n}_*.sql | grep -v _rollback | head -1)")
done
{
  echo "-- ============================================================================"
  echo "-- PHASE 6 -- STEP 2: THE MIGRATION"
  echo "--"
  echo "-- FIFTEEN migrations, not six. Production is at 0033; 0034-0042 were built"
  echo "-- and tested but never deployed, and Phase 6 depends on them. Deploying"
  echo "-- 0043-0048 alone COMMITS and then cannot record a sale -- proven."
  echo "--"
  echo "-- GENERATED by scripts/build_phase6_deploy.sh. Do not hand-edit; regenerate."
  echo "-- Sources, in order, with checksums:"
  for f in "${FILES[@]}"; do
    echo "--   $(sha256sum "$f" | cut -c1-16)  $(basename "$f")"
  done
  echo "--"
  echo "-- ONE TRANSACTION. Either all six land or none of them do. Nothing here"
  echo "-- requires running outside a transaction: no CONCURRENTLY, no VACUUM, no"
  echo "-- enum value added and used in the same breath."
  echo "--"
  echo "-- Run it as one buffer. Do NOT run it statement by statement: every"
  echo "-- preflight and self-check depends on being able to abort the whole thing."
  echo "-- ============================================================================"
  echo
  echo "begin;"
  echo
  for f in "${FILES[@]}"; do
    echo "-- ===================== $(basename "$f") ====================="
    cat "$f"
    echo
  done
  echo "commit;"
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
