#!/usr/bin/env bash
# ============================================================================
# MENU MASTER NG — build SQL-Editor-compatible copies of the test suites
#
# The suites are written for psql and use meta-commands (\set, \echo). The
# Supabase SQL Editor is not psql: a backslash command is a syntax error
# there. This strips them and nothing else.
#
# \set ON_ERROR_STOP is not needed remotely: the SQL Editor wraps a
# submission in one transaction, so the first error aborts the whole run
# regardless.
#
# Deterministic. Re-run after editing a suite.
# ============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p tests/supabase

for f in tests/001_*.sql tests/002_*.sql tests/004_*.sql tests/005_*.sql tests/010_*.sql; do
  base=$(basename "$f")
  out="tests/supabase/$base"
  {
    echo "-- ============================================================================"
    echo "-- MENU MASTER NG — $base (Supabase SQL Editor build)"
    echo "--"
    echo "-- DISPOSABLE PROJECT ONLY. Never run against production."
    echo "-- Generated by scripts/build_supabase_suites.sh from tests/$base."
    echo "-- Do not edit by hand. psql meta-commands stripped; nothing else changed."
    echo "--"
    echo "-- The editor renders only the LAST result set, which is this suite's"
    echo "-- passed/failed/total summary."
    echo "-- ============================================================================"
    echo
    grep -v '^[[:space:]]*\\' "$f"
  } > "$out"
  printf '%-42s %6s lines (stripped %s)\n' "$out" "$(wc -l < "$out")" \
    "$(( $(grep -c '^[[:space:]]*\\' "$f" || true) ))"
done
echo
echo "Supabase suite builds refreshed."
