#!/usr/bin/env bash
# ============================================================================
# MENU MASTER NG — build the Supabase deployment chain
#
# Concatenates migrations/ into five parts sized for the Supabase SQL Editor.
# Deterministic: same migrations in, same bytes out. Re-run after adding a
# migration.
#
# PART 2 must be run ALONE. It contains ALTER TYPE ... ADD VALUE, which
# PostgreSQL forbids in the same transaction that created the type, and the
# SQL Editor wraps a submission in one transaction.
# ============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."
mkdir -p deploy

emit() {                       # emit <outfile> <title> <note> <migrations...>
  local out="deploy/$1" title="$2" note="$3"; shift 3
  {
    echo "-- ============================================================================"
    echo "-- MENU MASTER NG — $title"
    echo "--"
    echo "-- DISPOSABLE / NON-PRODUCTION PROJECT ONLY."
    echo "-- Generated by scripts/build_deploy_chain.sh. Do not edit by hand."
    echo "-- Source migrations: $*"
    echo "--"
    echo "-- $note"
    echo "-- ============================================================================"
    echo
    for m in "$@"; do
      echo "-- ---------------------------------------------------------------- $m"
      cat "migrations/$m"
      echo
    done
  } > "$out"
  printf '%-42s %8s bytes  <- %s\n' "$out" "$(wc -c < "$out")" "$*"
}

emit PART_1_core_schema.sql "Part 1 of 5: core schema" \
  "Run first. Creates the schema, RLS policies and base functions." \
  0001_init.sql

emit PART_2_container_unit_RUN_ALONE.sql "Part 2 of 5: container unit kind" \
  "RUN THIS ALONE, in its own submission. ALTER TYPE ... ADD VALUE cannot run in the transaction that created the type." \
  0002_unit_kind_container.sql

emit PART_3_starter_catalogue.sql "Part 3 of 5: starter catalogue" \
  "Names, categories and units only. No prices, no conversions, no yields." \
  0003_seed.sql

emit PART_4_engines_and_gate1.sql "Part 4 of 5: engines and Gate 1 hardening" \
  "Unit conversion, purchase posting, recipe costing, snapshots, sales freeze, onboarding, grants, authorization hardening." \
  0004_integrity_and_security_fixes.sql \
  0005_unit_conversion_engine.sql \
  0006_purchase_posting.sql \
  0007_recipe_cost_engine.sql \
  0008_snapshot_and_pricing_engine.sql \
  0009_sales_freeze_and_profitability.sql \
  0010_onboarding.sql \
  0011_grants_and_api_surface.sql \
  0012_gate1_authorization_hardening.sql

emit PART_5_gate1_closure.sql "Part 5 of 5: Gate 1 closure" \
  "Zero-value rejection, void-and-reissue, write-side role enforcement, role function permissions." \
  0013_reject_zero_value_amounts.sql \
  0014_sales_void_and_reissue.sql \
  0015_write_side_role_enforcement.sql \
  0016_role_function_permissions.sql

echo
echo "Deployment chain rebuilt from migrations/."
