#!/usr/bin/env bash
# Generate ONE transactional rollback for the whole 0034-0048 chain.
#
# Why this exists: at six migrations a rollback could be six separate files run
# one at a time. At fifteen that is fifteen chances to stop halfway and leave
# production in a state nobody has ever tested. Each source rollback carries its
# own begin/commit; those are stripped so the whole reversal is one transaction.
set -eu
R="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$R/deploy/runbook/ROLLBACK.sql"
ORDER="0048 0047 0046 0045 0044 0043 0042 0041 0040 0039 0038 0037 0036 0035 0034"
{
  echo "-- ============================================================================"
  echo "-- ROLLBACK -- the whole 0034-0048 chain, reversed, in ONE transaction."
  echo "--"
  echo "-- GENERATED by scripts/build_phase6_rollback.sh. Do not hand-edit."
  echo "-- Sources, in reverse order, with checksums:"
  for n in $ORDER; do
    f="$R/migrations/proposed/${n}_rollback.sql"
    echo "--   $(sha256sum "$f" | cut -c1-16)  $(basename "$f")"
  done
  echo "--"
  echo "-- Run it as ONE buffer. Either the whole reversal happens or none of it"
  echo "-- does; there is no half-rolled-back state to explain."
  echo "--"
  echo "-- ONLY run this if STEP 2 COMMITTED and a later gate then failed. If STEP 2"
  echo "-- itself failed it already undid itself and there is nothing here to do."
  echo "--"
  echo "-- WHAT IT DOES NOT UNDO, deliberately:"
  echo "--   Any sale confirmed after the deploy keeps its frozen cost. Those are"
  echo "--     real sales and unfreezing them would destroy real economics."
  echo "--   Any finalised_at that 0045 recorded on a legacy order stays. On this"
  echo "--     database that is nothing at all -- production holds zero orders -- but"
  echo "--     the rule is stated so it stays true when that changes."
  echo "--   auth.users is never touched, here or in the forward migration."
  echo "-- ============================================================================"
  echo
  echo "begin;"
  echo
  for n in $ORDER; do
    f="$R/migrations/proposed/${n}_rollback.sql"
    echo "-- ===================== ${n}_rollback.sql ====================="
    # strip the per-file transaction control; this file owns the transaction
    grep -vE '^\s*(begin|commit)\s*;\s*$' "$f"
    echo
  done
  cat <<'TAIL'
-- ---------------------------------------------------------------------------
-- Final assertion: we must be back at the 0033 catalogue we started from.
-- ---------------------------------------------------------------------------
do $$
declare v_fp text; v_ahead text;
begin
  select md5(string_agg(s,',' order by s)) into v_fp
    from (select replace(p.oid::regprocedure::text,' ','') as s from pg_proc p
           where p.pronamespace='public'::regnamespace and p.proname like 'fn\_%') z;
  if v_fp <> '26a45d7d98026721366ec58a66cb6d1b' then
    raise exception 'ROLLBACK INCOMPLETE: function catalogue is %, expected the 0033 fingerprint 26a45d7d98026721366ec58a66cb6d1b', v_fp;
  end if;
  select string_agg(o,', ') into v_ahead from (
    select 'order_lines.business_id' as o where exists(select 1 from information_schema.columns where table_name='order_lines' and column_name='business_id')
    union all select 'orders.order_discount' where exists(select 1 from information_schema.columns where table_name='orders' and column_name='order_discount')
    union all select 'cost_snapshots.seq' where exists(select 1 from information_schema.columns where table_name='cost_snapshots' and column_name='seq')
    union all select 'v_sale_lines' where exists(select 1 from pg_views where schemaname='public' and viewname='v_sale_lines')
    union all select 'v_purchase_summary' where exists(select 1 from pg_views where schemaname='public' and viewname='v_purchase_summary')
  ) x;
  if v_ahead is not null then
    raise exception 'ROLLBACK INCOMPLETE: still present: %', v_ahead;
  end if;
  if (select count(*) from pg_policies where schemaname='public') <> 116 then
    raise exception 'ROLLBACK FAILED: policy count is %, expected 116',
      (select count(*) from pg_policies where schemaname='public');
  end if;
  raise notice 'ROLLBACK OK: back at the 0033 catalogue, 116 policies, auth.users untouched.';
end
$$;

commit;
TAIL
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
