-- ============================================================================
-- PHASE 6 -- STEP 2: THE MIGRATION
--
-- GENERATED by scripts/build_phase6_deploy.sh. Do not hand-edit; regenerate.
-- Sources, in order, with checksums:
--   09627bc5626b8863  0043_customer_and_line_scope.sql
--   67aee93b7d072a61  0044_discounts.sql
--   899d18f40b8cb005  0045_confirmation_freeze.sql
--   734c927a6f31406e  0046_cost_provenance.sql
--   7478d52e9b3317f3  0047_sales_reporting.sql
--   9af5ebc7b36003c7  0048_function_grant_surface.sql
--
-- ONE TRANSACTION. Either all six land or none of them do. Nothing here
-- requires running outside a transaction: no CONCURRENTLY, no VACUUM, no
-- enum value added and used in the same breath.
--
-- Run it as one buffer. Do NOT run it statement by statement: every
-- preflight and self-check depends on being able to abort the whole thing.
-- ============================================================================

begin;

-- ===================== 0043_customer_and_line_scope.sql =====================
-- ============================================================================
-- MENU MASTER NG
-- 0043: customer detail, and tenant scope on order lines
--
-- Requires: 0001-0042 applied.
--
-- Two small additions, no behaviour change.
--
--   customers.notes / .company  -- what a caterer needs to remember about a
--     client. Deliberately nothing more: no address, no birthday, no marketing
--     consent. Data not collected cannot be leaked.
--
--   order_lines.business_id  -- every other tenant table carries it. Without
--     it, every sales query must join orders to scope by business, and a
--     reporting view can silently lose that join. Backfilled from the parent
--     order, then made NOT NULL, with the composite foreign key the rest of
--     the schema uses so a line can never point at another account's order.
--
--     A denormalised column is only safe while it cannot disagree with the
--     row it was copied from, so it is not the caller's to set. A trigger
--     derives it from the parent order on every insert and update, and
--     refuses a value that contradicts that order. Callers that already
--     insert order lines keep working unchanged; callers that try to place
--     a line in another business are stopped.
-- ============================================================================

do $$
begin
  if exists (select 1 from information_schema.columns
              where table_name = 'order_lines' and column_name = 'business_id') then
    raise exception '0043 preflight FAILED: order_lines.business_id already exists.';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public') <> 116 then
    raise exception '0043 preflight FAILED: policy count is %, expected 116.',
      (select count(*) from pg_policies where schemaname = 'public');
  end if;
end
$$;

alter table customers
  add column notes   text,
  add column company text;

comment on column customers.company is
  'The organisation a customer orders for, when that differs from their name.';

alter table order_lines add column business_id uuid;

update order_lines ol
   set business_id = o.business_id
  from orders o
 where o.id = ol.order_id
   and ol.business_id is null;

do $$
declare v_orphan int;
begin
  select count(*) into v_orphan from order_lines where business_id is null;
  if v_orphan > 0 then
    raise exception '0043 FAILED: % order line(s) have no business after backfill. '
                    'Refusing to add NOT NULL over unresolved rows.', v_orphan;
  end if;
end
$$;

alter table order_lines alter column business_id set not null;

alter table order_lines
  add constraint fk_order_lines_business_id_account
  foreign key (business_id, account_id) references businesses(id, account_id);

-- The line always belongs to whatever business the order belongs to. Derived,
-- never supplied. A caller that supplies a different one is making a mistake
-- that would put revenue under the wrong business, so it is refused loudly
-- rather than silently overwritten.
create or replace function fn_order_line_scope()
returns trigger
language plpgsql
as $fn$
declare v_business uuid;
begin
  select o.business_id into v_business from orders o where o.id = new.order_id;
  if v_business is null then
    raise exception 'Order % not found; cannot scope this line.', new.order_id
      using errcode = 'foreign_key_violation';
  end if;

  if new.business_id is not null and new.business_id <> v_business then
    raise exception
      'This line belongs to an order in a different business. Add it to that order instead.'
      using errcode = 'check_violation';
  end if;

  new.business_id := v_business;
  return new;
end
$fn$;

-- Fires before the tenant foreign key is checked, and before the revenue and
-- freeze guards care about it, so an ordinary insert never has to name it.
create trigger trg_order_lines_scope
  before insert or update on order_lines
  for each row execute function fn_order_line_scope();

do $$
declare v_pol int;
begin
  if not exists (select 1 from information_schema.columns
                  where table_name = 'order_lines' and column_name = 'business_id'
                    and is_nullable = 'NO') then
    raise exception '0043 self-check FAILED: business_id is missing or nullable.';
  end if;
  if not exists (select 1 from pg_constraint
                  where conname = 'fk_order_lines_business_id_account') then
    raise exception '0043 self-check FAILED: the tenant foreign key is missing.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'order_lines' and t.tgname = 'trg_order_lines_scope') then
    raise exception '0043 self-check FAILED: the scope trigger is missing.';
  end if;
  if exists (select 1 from order_lines ol join orders o on o.id = ol.order_id
              where ol.business_id <> o.business_id) then
    raise exception '0043 self-check FAILED: a line disagrees with its order.';
  end if;
  select count(*) into v_pol from pg_policies where schemaname = 'public';
  if v_pol <> 116 then
    raise exception '0043 self-check FAILED: policy count moved to %.', v_pol;
  end if;
  raise notice '0043 OK: customer detail added, order lines scoped and derived, 116 policies unchanged.';
end
$$;

-- ===================== 0044_discounts.sql =====================
-- ============================================================================
-- MENU MASTER NG
-- 0044: discounts, and the deterministic allocation of an order discount
--
-- Requires: 0001-0043 applied.
--
-- A caterer discounts in two ways, and they mean different things:
--
--   a line discount   -- "the jollof is 200 naira off a plate for this order"
--   an order discount -- "take 5,000 naira off the whole thing"
--
-- Both are recorded as naira amounts, never percentages. A percentage has to
-- be turned into naira eventually, and whoever does that rounding owns the
-- argument about the missing kobo. An amount is simply what the owner gave
-- away.
--
-- The line discount is stored, because the owner decided it per line.
-- The order discount is stored once, on the order, and *allocated* to lines
-- pro rata by line revenue so that per-product margin means something. The
-- allocation is derived, never stored, for two reasons:
--
--   it cannot drift from the numbers it is derived from, and
--   its inputs are already immutable once the sale is confirmed, so the
--   allocation is immutable too, without a second thing to freeze.
--
-- Gross revenue, the line discount, the allocated order discount and net
-- revenue are all reported separately. A discount is a decision worth seeing,
-- not something to bury inside a reduced price.
-- ============================================================================

do $$
begin
  if exists (select 1 from information_schema.columns
              where table_name = 'order_lines' and column_name = 'discount_amount') then
    raise exception '0044 preflight FAILED: order_lines.discount_amount already exists.';
  end if;
  if exists (select 1 from information_schema.columns
              where table_name = 'orders' and column_name = 'order_discount') then
    raise exception '0044 preflight FAILED: orders.order_discount already exists.';
  end if;
  if not exists (select 1 from information_schema.columns
                  where table_name = 'order_lines' and column_name = 'business_id') then
    raise exception '0044 preflight FAILED: 0043 has not been applied.';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public') <> 116 then
    raise exception '0044 preflight FAILED: policy count is %, expected 116.',
      (select count(*) from pg_policies where schemaname = 'public');
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. The two columns
-- ---------------------------------------------------------------------------

alter table order_lines
  add column discount_amount numeric(14,2) not null default 0;

-- Gross revenue is qty * unit_price. Giving away more than the line is worth
-- is not a discount, it is a refund, and Menu Master does not model refunds.
alter table order_lines
  add constraint order_lines_discount_amount_check
  check (discount_amount >= 0 and discount_amount <= qty * unit_price);

comment on column order_lines.discount_amount is
  'Naira taken off this line specifically. Never a percentage.';

alter table orders
  add column order_discount numeric(14,2) not null default 0;

alter table orders
  add constraint orders_order_discount_check check (order_discount >= 0);

comment on column orders.order_discount is
  'Naira taken off the order as a whole, allocated across its lines pro rata '
  'by line revenue. See fn_allocate_order_discount.';

-- ---------------------------------------------------------------------------
-- 2. An order discount cannot exceed what the order is worth
--
-- This one cannot be a CHECK: it spans rows in another table. It is enforced
-- where the owner sets the discount, and again, harder, at confirmation.
--
-- Deliberately NOT enforced when a line is removed. Removing a line from a
-- draft can leave the discount larger than what remains; refusing the delete
-- would trap the owner between two edits they are allowed to make. The draft
-- is simply invalid until they lower the discount, and confirmation says so.
-- ---------------------------------------------------------------------------

create or replace function fn_guard_order_discount()
returns trigger
language plpgsql
as $fn$
declare v_subtotal numeric(14,2);
begin
  if tg_op = 'UPDATE' and new.order_discount is not distinct from old.order_discount then
    return new;
  end if;
  if new.order_discount = 0 then
    return new;
  end if;

  select coalesce(sum(ol.qty * ol.unit_price - ol.discount_amount), 0)
    into v_subtotal
    from order_lines ol
   where ol.order_id = new.id;

  -- No lines yet: the owner is filling in the order header first. Confirmation
  -- is the backstop, and an order with no lines cannot be confirmed at all.
  if not exists (select 1 from order_lines where order_id = new.id) then
    return new;
  end if;

  if new.order_discount > v_subtotal then
    raise exception
      'The order discount of % is more than the order is worth (%). Lower the discount.',
      to_char(new.order_discount, 'FM999999990.00'),
      to_char(v_subtotal, 'FM999999990.00')
      using errcode = 'check_violation';
  end if;

  return new;
end
$fn$;

create trigger trg_orders_discount
  before insert or update on orders
  for each row execute function fn_guard_order_discount();

-- ---------------------------------------------------------------------------
-- 3. The allocation
--
--   line revenue  = qty * unit_price - line discount
--   share_i       = round(order_discount * line_revenue_i / subtotal, 2)
--
-- Rounding each share independently leaves a residual of a few kobo either
-- way. That residual goes to the single largest line by revenue, ties broken
-- by line id, so the sum of the allocations equals the order discount exactly,
-- always, and the same order always allocates the same way.
--
-- The function never raises. It is read by reporting views, and a view that
-- throws on one bad draft shows nothing for anybody. A draft whose discount
-- exceeds its own revenue allocates more than a line is worth and reports a
-- negative net revenue -- which is the truth about that draft. Confirmation
-- refuses it.
--
-- Called with no argument it allocates across every order the caller can see,
-- in one pass, which is how the sales views use it. Row level security applies
-- normally: this function is not SECURITY DEFINER and holds no privilege of
-- its own.
-- ---------------------------------------------------------------------------

create or replace function fn_allocate_order_discount(p_order_id uuid default null)
returns table (
  order_line_id            uuid,
  order_id                 uuid,
  gross_revenue            numeric(14,2),
  line_discount            numeric(14,2),
  line_revenue             numeric(14,2),
  allocated_order_discount numeric(14,2),
  net_revenue              numeric(14,2)
)
language sql
stable
as $fn$
  with l as (
    select ol.id,
           ol.order_id                                              as ord,
           (ol.qty * ol.unit_price)::numeric(14,2)                  as gross,
           ol.discount_amount,
           (ol.qty * ol.unit_price - ol.discount_amount)::numeric(14,2) as revenue,
           o.order_discount
      from order_lines ol
      join orders o on o.id = ol.order_id
     where p_order_id is null or ol.order_id = p_order_id
  ),
  ranked as (
    select l.*,
           sum(l.revenue) over (partition by l.ord)                 as subtotal,
           row_number() over (partition by l.ord
                              order by l.revenue desc, l.id)        as rn
      from l
  ),
  shared as (
    select ranked.*,
           case
             when ranked.order_discount = 0 then 0::numeric(14,2)
             when ranked.subtotal > 0
               then round(ranked.order_discount * ranked.revenue / ranked.subtotal, 2)
             -- Nothing to allocate against. The whole discount lands on the
             -- first line rather than quietly evaporating.
             else 0::numeric(14,2)
           end as share
      from ranked
  ),
  residual as (
    select shared.*,
           sum(shared.share) over (partition by shared.ord) as share_total
      from shared
  )
  select residual.id,
         residual.ord,
         residual.gross,
         residual.discount_amount,
         residual.revenue,
         (residual.share
            + case when residual.rn = 1
                   then residual.order_discount - residual.share_total
                   else 0 end)::numeric(14,2),
         (residual.revenue
            - (residual.share
                 + case when residual.rn = 1
                        then residual.order_discount - residual.share_total
                        else 0 end))::numeric(14,2)
    from residual;
$fn$;

comment on function fn_allocate_order_discount(uuid) is
  'Splits orders.order_discount across an order''s lines pro rata by line '
  'revenue. The kobo residual goes to the largest line, so the allocations '
  'sum to the order discount exactly. Pass null to allocate every visible order.';

grant execute on function fn_allocate_order_discount(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- 4. Discounts are revenue, so a confirmed sale must not be able to move them
--
-- Both guards already exist and already freeze everything that determines
-- revenue. They simply did not know about discounts yet. Extended, not
-- replaced.
-- ---------------------------------------------------------------------------

create or replace function fn_guard_order_line_revenue()
returns trigger
language plpgsql
as $fn$
declare v_final timestamptz; v_void timestamptz; v_order uuid;
begin
  v_order := coalesce(new.order_id, old.order_id);
  select finalised_at, voided_at into v_final, v_void from orders where id = v_order;

  if v_final is null then
    return coalesce(new, old);            -- still a draft: freely editable
  end if;

  if tg_op = 'INSERT' then
    raise exception 'Order % is finalised. No further lines may be added.', v_order
      using errcode='check_violation';
  elsif tg_op = 'DELETE' then
    raise exception 'Order % is finalised. Lines cannot be deleted. Void the order instead.', v_order
      using errcode='check_violation';
  else
    -- discount_amount joins the tuple: a discount changes revenue, and revenue
    -- on a confirmed sale is history.
    if (old.qty, old.unit_price, old.recipe_id, old.discount_amount)
       is distinct from (new.qty, new.unit_price, new.recipe_id, new.discount_amount) then
      raise exception 'Revenue on a finalised sale is immutable. Void and reissue instead.'
        using errcode='check_violation';
    end if;
  end if;

  return coalesce(new, old);
end;
$fn$;

create or replace function fn_guard_finalised_order()
returns trigger
language plpgsql
as $fn$
begin
  if tg_op = 'DELETE' then
    if old.finalised_at is not null then
      raise exception 'Order % is finalised and cannot be deleted. Void it instead.', old.id
        using errcode='check_violation';
    end if;
    return old;
  end if;

  if old.voided_at is not null then
    raise exception 'Order % is voided. Its record is closed.', old.id
      using errcode='check_violation';
  end if;

  if old.finalised_at is not null then
    -- Settlement may still move after the sale: collecting payment later is not
    -- a revenue rewrite. Everything that determines revenue is frozen, and the
    -- order discount determines revenue.
    if (old.account_id, old.business_id, old.location_id, old.customer_id,
        old.channel_id, old.order_no, old.order_date, old.status,
        old.finalised_at, old.replaces, old.order_discount)
       is distinct from
       (new.account_id, new.business_id, new.location_id, new.customer_id,
        new.channel_id, new.order_no, new.order_date, new.status,
        new.finalised_at, new.replaces, new.order_discount)
    then
      raise exception 'Order % is finalised. Only payment state may change, or void it.', old.id
        using errcode='check_violation';
    end if;
  end if;

  return new;
end;
$fn$;

-- ---------------------------------------------------------------------------
-- 5. Self-check
-- ---------------------------------------------------------------------------

do $$
declare v_pol int;
begin
  if not exists (select 1 from information_schema.columns
                  where table_name = 'order_lines' and column_name = 'discount_amount'
                    and is_nullable = 'NO' and column_default = '0') then
    raise exception '0044 self-check FAILED: order_lines.discount_amount is wrong or missing.';
  end if;
  if not exists (select 1 from information_schema.columns
                  where table_name = 'orders' and column_name = 'order_discount'
                    and is_nullable = 'NO' and column_default = '0') then
    raise exception '0044 self-check FAILED: orders.order_discount is wrong or missing.';
  end if;
  if not exists (select 1 from pg_constraint where conname = 'order_lines_discount_amount_check') then
    raise exception '0044 self-check FAILED: the line discount ceiling is missing.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'orders' and t.tgname = 'trg_orders_discount') then
    raise exception '0044 self-check FAILED: the order discount guard is missing.';
  end if;
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                  where n.nspname = 'public' and p.proname = 'fn_allocate_order_discount') then
    raise exception '0044 self-check FAILED: fn_allocate_order_discount is missing.';
  end if;
  -- Every existing order still reconciles: nothing has a discount yet, so
  -- every allocation must be zero and every net must equal gross.
  if exists (select 1 from fn_allocate_order_discount()
              where allocated_order_discount <> 0 or net_revenue <> gross_revenue) then
    raise exception '0044 self-check FAILED: a pre-existing order changed value.';
  end if;
  select count(*) into v_pol from pg_policies where schemaname = 'public';
  if v_pol <> 116 then
    raise exception '0044 self-check FAILED: policy count moved to %.', v_pol;
  end if;
  raise notice '0044 OK: discounts added, allocation deterministic, 116 policies unchanged.';
end
$$;

-- ===================== 0045_confirmation_freeze.sql =====================
-- ============================================================================
-- MENU MASTER NG
-- 0045: the freeze happens at confirmation, not at typing
--
-- Requires: 0001-0044 applied.
--
-- The problem this fixes
-- ---------------------
-- An order line froze its cost the instant it was typed. A caterer building a
-- Saturday order on Monday, adding to it on Tuesday and confirming it on
-- Wednesday ended up with three different days' economics inside one sale.
-- Worse, the Monday line froze a cost for a sale that had not happened and
-- might never happen.
--
-- The economics of a sale are the economics at the moment the sale is
-- committed. So the freeze moves to confirmation, and it freezes every line
-- together, from one instant, in one statement.
--
-- What that requires
-- ------------------
--   the BEFORE INSERT freeze on order_lines is removed; drafts stay live and
--     recost themselves as ingredient prices move, which is the point of a
--     draft
--
--   fn_guard_frozen_cost, which refused every change to a frozen cost, has to
--     permit exactly one: null -> value, performed by the confirmation itself.
--     It now recognises that operation rather than trusting any caller who
--     happens to be updating a draft line
--
--   orders.status defaulted to 'confirmed', so an order inserted without a
--     status was born committed and never made the transition that freezes it.
--     The default becomes 'draft'
--
--   status and finalised_at were independent, and every guard keyed on
--     finalised_at while status was decorative. Confirmation now sets both in
--     one statement, so there is one boundary rather than two
--
-- sales_entries is untouched. A quick sale has no draft state -- it is a
-- record of something that already happened -- so it still freezes on arrival.
-- The two paths now share one implementation of "what does this product cost
-- right now", so they cannot drift apart.
-- ============================================================================

do $$
begin
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'order_lines' and t.tgname = 'trg_order_lines_freeze') then
    raise exception '0045 preflight FAILED: trg_order_lines_freeze is already gone.';
  end if;
  if not exists (select 1 from information_schema.columns
                  where table_name = 'orders' and column_name = 'order_discount') then
    raise exception '0045 preflight FAILED: 0044 has not been applied.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'sales_entries' and t.tgname = 'trg_sales_entries_freeze') then
    raise exception '0045 preflight FAILED: the sales_entries freeze is missing.';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public') <> 116 then
    raise exception '0045 preflight FAILED: policy count is %, expected 116.',
      (select count(*) from pg_policies where schemaname = 'public');
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 0. The orders the old default left behind
--
-- Until this migration, orders.status defaulted to 'confirmed' while
-- finalised_at was set only by fn_finalise_order. So an order inserted and
-- never explicitly finalised sat in a third state: counted as revenue by the
-- reporting views, which keyed on status, but not locked by the guards, which
-- key on finalised_at. Its lines were frozen at insert regardless.
--
-- Phase 6 merges those two tiers into one boundary. These rows have to land
-- somewhere, and there are only two honest choices:
--
--   drop them from revenue -- which silently changes the owner's historical
--     figures, the exact thing this phase exists to prevent; or
--   record when they were recognised -- which is what the old system meant by
--     'confirmed' from the moment of creation.
--
-- The second. finalised_at takes the order's own created_at and finalised_by
-- its created_by: not invented, read off the row. NO LINE IS TOUCHED, so no
-- historical sale is re-costed and every frozen figure stays exactly as it was.
--
-- Reported, never silent. Voided orders and drafts are left alone; both are
-- excluded from reporting before and after, so neither needs a decision.
-- ---------------------------------------------------------------------------

do $$
declare v_n int;
begin
  select count(*) into v_n from orders
   where status not in ('draft', 'cancelled')
     and finalised_at is null and voided_at is null;
  if v_n > 0 then
    raise notice '0045: % order(s) were recognised as sales under the old default '
                 'and carry no confirmation time. Recording their creation time as '
                 'their confirmation time so their revenue does not change.', v_n;
  else
    raise notice '0045: no legacy orders need reconciling.';
  end if;
end
$$;

update orders
   set finalised_at = created_at,
       finalised_by = created_by
 where status not in ('draft', 'cancelled')
   and finalised_at is null
   and voided_at is null;

-- ---------------------------------------------------------------------------
-- 1. One answer to "what does this product cost right now"
--
-- fn_freeze_sale_cost held this rule for quick sales. Confirmation needs the
-- identical rule for order lines. Rather than write it twice -- which is
-- exactly how the 0040 defect happened -- it moves into one function that both
-- callers use. The rule itself is unchanged, including the gate that an
-- incomplete cost is not a cost.
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_type where typname = 'frozen_sale_cost') then
    create type frozen_sale_cost as (
      cost_snapshot_id  uuid,
      unit_cost_at_sale numeric(18,4)
    );
  end if;
end
$$;

-- SECURITY DEFINER, so it must scope itself twice over: it refuses a caller
-- who is not a member of the account it is asked about, and it filters on that
-- account explicitly rather than inferring it from whatever snapshot it finds.
-- Without the first check a definer function taking an account id is simply a
-- cost-reading service for anybody who can guess one.
--
-- Membership, not cost access: a sales user may confirm an order, and the
-- freeze runs on their behalf, while they still cannot read a cost figure
-- anywhere in the product. That boundary is Gate 1's and does not move here.
create or replace function fn_frozen_sale_cost(
  p_account_id uuid,
  p_recipe_id  uuid,
  p_variant_id uuid
)
returns frozen_sale_cost
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare s cost_snapshots%rowtype; r frozen_sale_cost;
begin
  perform fn_require_member(p_account_id);

  r := row(null, null)::frozen_sale_cost;

  if p_recipe_id is null then
    return r;                       -- an ad hoc line has no product to cost
  end if;

  if p_variant_id is not null then
    -- what was actually sold is the variant, so that is what is frozen
    select * into s
      from cost_snapshots
     where account_id = p_account_id and variant_id = p_variant_id
     order by computed_at desc, seq desc
     limit 1;
  else
    select * into s
      from cost_snapshots
     where account_id = p_account_id
       and recipe_id = p_recipe_id and variant_id is null
     order by computed_at desc, seq desc
     limit 1;
  end if;

  -- The gate. An incomplete cost is not a cost, and a missing cost stays
  -- missing: it is never rounded down to zero.
  if not found or not s.is_complete or s.cost_per_portion is null then
    return r;
  end if;

  return row(s.id, s.cost_per_portion)::frozen_sale_cost;
end
$fn$;

comment on function fn_frozen_sale_cost(uuid, uuid, uuid) is
  'The cost to freeze against a sale of this product right now, or (null,null) '
  'when the product is not fully costed. Shared by quick sales and by order '
  'confirmation so the two cannot diverge.';

-- fn_freeze_sale_cost keeps its exact behaviour; only its body moves.
create or replace function fn_freeze_sale_cost()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare c frozen_sale_cost;
begin
  c := fn_frozen_sale_cost(new.account_id, new.recipe_id, new.variant_id);
  new.cost_snapshot_id  := c.cost_snapshot_id;
  new.unit_cost_at_sale := c.unit_cost_at_sale;
  return new;
end
$fn$;

-- ---------------------------------------------------------------------------
-- 2. Drafts stay live
-- ---------------------------------------------------------------------------

drop trigger if exists trg_order_lines_freeze on order_lines;

-- ---------------------------------------------------------------------------
-- 3. The frozen cost becomes writable exactly once, by exactly one operation
--
-- The old guard refused every change on UPDATE, which would have made the
-- confirmation freeze impossible. It now permits the single transition
-- null -> value, and only while fn_confirm_order is performing it. The marker
-- is set with SET LOCAL inside that function, so it dies with the transaction
-- and cannot be forged from a session that is not confirming this order.
--
-- Everything else is still refused: value -> different value, value -> null,
-- and null -> value written by anyone other than the confirmation.
--
-- The guard now also covers INSERT. Without the old BEFORE INSERT freeze,
-- nothing else would stop a caller inserting a draft line with a cost of its
-- own choosing.
-- ---------------------------------------------------------------------------

create or replace function fn_guard_frozen_cost()
returns trigger
language plpgsql
as $fn$
declare v_confirming text;
begin
  if tg_op = 'INSERT' then
    if new.cost_snapshot_id is not null or new.unit_cost_at_sale is not null then
      raise exception
        'A cost is frozen when the sale is confirmed, not when the line is added.'
        using errcode = 'check_violation';
    end if;
    return new;
  end if;

  if new.cost_snapshot_id  is not distinct from old.cost_snapshot_id
 and new.unit_cost_at_sale is not distinct from old.unit_cost_at_sale then
    return new;                          -- the frozen cost is not moving
  end if;

  v_confirming := current_setting('menumaster.confirming_order', true);

  if old.cost_snapshot_id is null
 and old.unit_cost_at_sale is null
 and v_confirming is not null
 and v_confirming <> ''
 and v_confirming = new.order_id::text then
    return new;                          -- the confirmation freeze: once, one way
  end if;

  raise exception
    'The cost frozen at sale time cannot be changed. Void the sale and reissue instead.'
    using errcode = 'check_violation';
end
$fn$;

drop trigger if exists trg_order_lines_frozen on order_lines;
create trigger trg_order_lines_frozen
  before insert or update on order_lines
  for each row execute function fn_guard_frozen_cost();

-- ---------------------------------------------------------------------------
-- 4. An order is born a draft
-- ---------------------------------------------------------------------------

alter table orders alter column status set default 'draft';

-- ---------------------------------------------------------------------------
-- 5. Confirmation
--
-- One transaction, one row lock, one UPDATE across every line. There is no
-- path to a half-frozen confirmed order: if anything raises, the whole
-- confirmation rolls back and the order is still a draft.
--
-- A line whose product is not fully costed freezes to NULL. That is a valid
-- outcome, not a failure -- the sale really did happen, and Menu Master will
-- not invent a cost for it. The function reports how many lines are in that
-- state so the caller can say so plainly.
-- ---------------------------------------------------------------------------

create or replace function fn_confirm_order(p_order_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v_o        orders%rowtype;
  v_lines    integer;
  v_subtotal numeric(14,2);
  v_costed   integer;
begin
  select * into v_o from orders where id = p_order_id for update;
  if not found then raise exception 'Order % not found', p_order_id; end if;

  perform fn_require_account_role(v_o.account_id,
    array['owner','manager','sales']::member_role[], 'confirming orders');

  if v_o.voided_at is not null then
    raise exception 'Order % is voided and cannot be confirmed', p_order_id
      using errcode='check_violation';
  end if;
  if v_o.finalised_at is not null then
    raise exception 'Order % is already confirmed', p_order_id
      using errcode='check_violation';
  end if;

  select count(*), coalesce(sum(qty * unit_price - discount_amount), 0)
    into v_lines, v_subtotal
    from order_lines where order_id = p_order_id;

  if v_lines = 0 then
    raise exception 'Order % has no lines', p_order_id using errcode='check_violation';
  end if;

  -- The order-level check 0044 could not express as a CHECK constraint. A
  -- draft is allowed to be temporarily inconsistent; a confirmed sale is not.
  if v_o.order_discount > v_subtotal then
    raise exception
      'The order discount of % is more than the order is worth (%). Lower the discount before confirming.',
      to_char(v_o.order_discount, 'FM999999990.00'),
      to_char(v_subtotal, 'FM999999990.00')
      using errcode='check_violation';
  end if;

  -- Opens the one-way window in fn_guard_frozen_cost. SET LOCAL: it is gone at
  -- the end of this transaction whether it commits or rolls back.
  perform set_config('menumaster.confirming_order', p_order_id::text, true);

  -- Every line, one statement, one instant. now() is the transaction time, so
  -- every line freezes against the same moment by construction.
  --
  -- The lateral call lives in a subquery rather than the UPDATE's own FROM
  -- clause: an UPDATE's FROM cannot reference the row being updated.
  update order_lines ol
     set cost_snapshot_id  = f.cost_snapshot_id,
         unit_cost_at_sale = f.unit_cost_at_sale
    from (
      select l.id, c.cost_snapshot_id, c.unit_cost_at_sale
        from order_lines l
        cross join lateral fn_frozen_sale_cost(l.account_id, l.recipe_id, l.variant_id) c
       where l.order_id = p_order_id
    ) f
   where ol.id = f.id;

  perform set_config('menumaster.confirming_order', '', true);

  select count(*) into v_costed
    from order_lines where order_id = p_order_id and unit_cost_at_sale is not null;

  update orders
     set status       = 'confirmed',
         finalised_at = now(),
         finalised_by = auth.uid()
   where id = p_order_id;

  return jsonb_build_object(
    'confirmed',          true,
    'order_id',           p_order_id,
    'lines_frozen',       v_lines,
    'lines_without_cost', v_lines - v_costed);
end
$fn$;

comment on function fn_confirm_order(uuid) is
  'Commits a draft order: freezes every line''s cost from one instant and sets '
  'status and finalised_at together. The only way an order reaches confirmed.';

grant execute on function fn_confirm_order(uuid) to authenticated;

-- 0018 removed PUBLIC and anon from every fn_*. It was a sweep, not a standing
-- rule, so every function added since has quietly arrived executable by
-- everyone. Restated here for the two this migration adds; 0048 restores the
-- rule for the whole schema and tests/034 keeps it restored.
revoke all on function fn_confirm_order(uuid) from public, anon;
revoke all on function fn_frozen_sale_cost(uuid, uuid, uuid) from public, anon;
grant execute on function fn_frozen_sale_cost(uuid, uuid, uuid) to authenticated;

-- fn_finalise_order keeps working, and keeps its old return shape: callers
-- reading ->>'finalised' must not start getting NULL. It is the same operation
-- under an older name, so it delegates rather than holding a second copy of
-- the rules.
create or replace function fn_finalise_order(p_order_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare v jsonb;
begin
  v := fn_confirm_order(p_order_id);
  return jsonb_build_object(
    'finalised', true,
    'order_id',  p_order_id,
    'lines',     v->'lines_frozen');
end
$fn$;

comment on function fn_finalise_order(uuid) is
  'Superseded by fn_confirm_order, which it calls. Kept so existing callers '
  'do not break.';

-- ---------------------------------------------------------------------------
-- 6. An order cannot be talked into being confirmed
--
-- Every guard in the schema keys on finalised_at, and status was decorative.
-- With status now meaning something, an ordinary UPDATE could set it to
-- 'confirmed' while finalised_at stayed null -- an order that looks like a sale
-- to a reader and like a draft to every guard, with no frozen cost. An INSERT
-- could do the same in one step.
--
-- So status and finalised_at move together, and only fn_confirm_order moves
-- them. Cancelling is exempt: it is its own path and is not a confirmation.
--
-- Service context is exempt, deliberately. An operator repairing data through
-- the service role is not the 'normal application', and taking that away would
-- remove the only recovery route. It is recorded here rather than hidden.
-- ---------------------------------------------------------------------------

create or replace function fn_guard_order_lifecycle()
returns trigger
language plpgsql
as $fn$
begin
  if fn_is_service_context() then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if new.status <> 'draft' or new.finalised_at is not null then
      raise exception
        'An order starts as a draft. Confirm it when the sale is agreed.'
        using errcode = 'check_violation';
    end if;
    return new;
  end if;

  if new.status is distinct from old.status
     and new.status <> 'cancelled'
     and old.finalised_at is null
     and new.finalised_at is null then
    raise exception
      'This order is still a draft. Confirm it to record the sale.'
      using errcode = 'check_violation';
  end if;

  if new.finalised_at is not null and new.status = 'draft' then
    raise exception 'A confirmed sale cannot also be a draft.'
      using errcode = 'check_violation';
  end if;

  return new;
end
$fn$;

revoke all on function fn_guard_order_lifecycle() from public, anon;

create trigger trg_orders_lifecycle
  before insert or update on orders
  for each row execute function fn_guard_order_lifecycle();

-- ---------------------------------------------------------------------------
-- 7. Self-check
-- ---------------------------------------------------------------------------

do $$
declare v_pol int;
begin
  if exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
              where c.relname = 'order_lines' and t.tgname = 'trg_order_lines_freeze') then
    raise exception '0045 self-check FAILED: the insert-time freeze survived.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'sales_entries' and t.tgname = 'trg_sales_entries_freeze') then
    raise exception '0045 self-check FAILED: the sales_entries freeze was disturbed.';
  end if;
  if (select column_default from information_schema.columns
       where table_name = 'orders' and column_name = 'status')
     is distinct from '''draft''::order_status' then
    raise exception '0045 self-check FAILED: orders.status does not default to draft.';
  end if;
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                  where n.nspname = 'public' and p.proname = 'fn_confirm_order') then
    raise exception '0045 self-check FAILED: fn_confirm_order is missing.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'order_lines' and t.tgname = 'trg_order_lines_frozen'
                    and (t.tgtype & 4) = 4 and (t.tgtype & 16) = 16) then
    raise exception '0045 self-check FAILED: the frozen-cost guard does not cover insert and update.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'orders' and t.tgname = 'trg_orders_lifecycle') then
    raise exception '0045 self-check FAILED: the lifecycle guard is missing.';
  end if;
  -- Every order that reads as a sale must carry a confirmation time. Anything
  -- left here would be counted by the old reporting and ignored by the new.
  if exists (select 1 from orders
              where status not in ('draft', 'cancelled')
                and finalised_at is null and voided_at is null) then
    raise exception '0045 self-check FAILED: % order(s) read as sales with no confirmation time.',
      (select count(*) from orders where status not in ('draft', 'cancelled')
        and finalised_at is null and voided_at is null);
  end if;
  -- A definer function that takes an account id and does not check it is a
  -- cost-reading service for anyone who can guess one.
  if pg_get_functiondef((select oid from pg_proc
                          where proname = 'fn_frozen_sale_cost'
                            and pronamespace = 'public'::regnamespace))
     !~ 'fn_require_member' then
    raise exception '0045 self-check FAILED: fn_frozen_sale_cost does not check membership.';
  end if;
  -- Nothing already confirmed may have been disturbed by any of this.
  if exists (select 1 from order_lines ol join orders o on o.id = ol.order_id
              where o.finalised_at is not null and ol.recipe_id is not null
                and ol.cost_snapshot_id is null and ol.unit_cost_at_sale is not null) then
    raise exception '0045 self-check FAILED: a confirmed line lost its snapshot.';
  end if;
  select count(*) into v_pol from pg_policies where schemaname = 'public';
  if v_pol <> 116 then
    raise exception '0045 self-check FAILED: policy count moved to %.', v_pol;
  end if;
  raise notice '0045 OK: freeze moved to confirmation, drafts live, 116 policies unchanged.';
end
$$;

-- ===================== 0046_cost_provenance.sql =====================
-- ============================================================================
-- MENU MASTER NG
-- 0046: a frozen cost that can still be explained years later
--
-- Requires: 0001-0045 applied.
--
-- The frozen total was already immutable. The *explanation* of it was not.
--
-- Two things a snapshot needed and did not record:
--
--   B-1  a format-based variant's overhead share. The total included it, but
--        the breakdown had to reconstruct it by asking fn_overhead_rate about
--        TODAY's configuration. Change the overhead basis tomorrow and the
--        frozen total is still right while the breakdown quietly stops adding
--        up to it.
--
--   B-2  the portion size used at compute time. cost_per_portion is
--        cost_per_yield_unit x portion_qty, and portion_qty lives on recipes,
--        which is mutable. Change the portion size and 1.70/g x ? = 850 has
--        lost its "?".
--
-- Two nullable columns fix both. No child table: a breakdown table would be a
-- second place component figures live, needing its own RLS, its own
-- immutability trigger and its own reconciliation. The snapshot row is already
-- immutable and already holds every other component.
--
-- The more important half is the refactor. Rather than have the snapshot
-- writer recompute the components -- which is exactly how the 0040 defect
-- happened, and how this file's own packaging figure came to be computed twice
-- from two copies of one rule -- the component arithmetic moves into one
-- function. fn_variant_cost becomes a thin wrapper returning its total, and
-- the snapshot writer stores the components it returns. One implementation,
-- two callers, the same shape as fn_ingredient_cost_basis in 0034.
--
-- Snapshots written before this migration keep NULL in the new columns. That
-- is honest: detail never recorded cannot be invented afterwards. The
-- invariant is therefore "where component detail exists, it reconciles", not
-- "every snapshot has a breakdown".
-- ============================================================================

do $$
begin
  if exists (select 1 from information_schema.columns
              where table_name = 'cost_snapshots'
                and column_name in ('portion_qty_at_snapshot','variant_overhead_cost')) then
    raise exception '0046 preflight FAILED: a provenance column already exists.';
  end if;
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                  where n.nspname = 'public' and p.proname = 'fn_confirm_order') then
    raise exception '0046 preflight FAILED: 0045 has not been applied.';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public') <> 116 then
    raise exception '0046 preflight FAILED: policy count is %, expected 116.',
      (select count(*) from pg_policies where schemaname = 'public');
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. The two columns
--
-- ADD COLUMN is DDL, not row mutation, so fn_block_snapshot_mutation still
-- refuses every UPDATE and DELETE on cost_snapshots exactly as before.
-- ---------------------------------------------------------------------------

alter table cost_snapshots
  add column portion_qty_at_snapshot numeric,
  add column variant_overhead_cost   numeric;

comment on column cost_snapshots.portion_qty_at_snapshot is
  'The portion size in effect when this snapshot was computed. recipes.portion_qty '
  'can change afterwards; this cannot.';

comment on column cost_snapshots.variant_overhead_cost is
  'The overhead share carried by this variant''s sold unit. NULL on snapshots '
  'written before 0046, and on recipe-level snapshots, which record overhead '
  'in overhead_cost instead.';

-- ---------------------------------------------------------------------------
-- 2. One implementation of a variant's component costs
--
-- Same arithmetic fn_variant_cost has always performed, in one place, now
-- reporting the parts as well as the sum.
--
-- One deliberate change of behaviour: packaging comes back NULL, not 0, when a
-- cost-bearing packaging item has no price. sum() skips NULLs, so the old
-- expression reported an understated packaging figure for a variant that was
-- already blocked. A cost that is not known is not zero -- that rule does not
-- stop applying because the row happens to be incomplete.
-- ---------------------------------------------------------------------------

do $$
begin
  if not exists (select 1 from pg_type where typname = 'variant_cost_components') then
    create type variant_cost_components as (
      resolved_qty       numeric,
      ingredients_labour numeric,
      packaging          numeric,
      overhead           numeric,
      total              numeric
    );
  end if;
end
$$;

create or replace function fn_variant_cost_components(p_variant_id uuid)
returns variant_cost_components
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
declare
  v record; c variant_cost_components;
  v_cpyu numeric; v_oh_rate numeric; v_unpriced_pack int;
begin
  c := row(null, null, null, null, null)::variant_cost_components;

  select rv.account_id, rv.business_id, rv.recipe_id, rv.format_id,
         r.yield_unit_id
    into v
    from recipe_variants rv
    join recipes r on r.id = rv.recipe_id
   where rv.id = p_variant_id;

  if v is null then return c; end if;
  perform fn_require_cost_access(v.account_id);

  c.resolved_qty := fn_variant_resolved_qty(p_variant_id);

  -- D4: format packaging is consumed once per sold unit and is NOT multiplied
  -- by the resolved quantity. No cost-bearing rows means no cost -- a true
  -- zero. An unpriced cost-bearing row means the figure is unknown.
  select count(*) into v_unpriced_pack
    from serving_format_packaging spk
   where spk.format_id = v.format_id
     and spk.is_cost_bearing
     and fn_ingredient_usable_unit_cost(spk.packaging_item_id, v.business_id) is null;

  if v_unpriced_pack = 0 then
    select coalesce(sum(spk.qty * fn_ingredient_usable_unit_cost(
                          spk.packaging_item_id, v.business_id)), 0)
      into c.packaging
      from serving_format_packaging spk
     where spk.format_id = v.format_id
       and spk.is_cost_bearing;
  end if;

  -- the existing engine's figure, unchanged: it already carries ingredients,
  -- sub-recipes, purchase yield, cooking yield and labour over effective yield
  select cost_per_yield_unit into v_cpyu
    from cost_snapshots
   where recipe_id = v.recipe_id and variant_id is null
   order by computed_at desc, seq desc
   limit 1;

  if v_cpyu is not null and c.resolved_qty is not null then
    c.ingredients_labour := v_cpyu * c.resolved_qty;
  end if;

  -- D1: overhead scales with output
  v_oh_rate := fn_overhead_rate(v.business_id, v.yield_unit_id);
  if v_oh_rate is null then
    if (select overhead_enabled from business_settings where business_id = v.business_id) then
      c.overhead := null;   -- enabled but unresolvable: incomplete, never zero
    else
      c.overhead := 0;      -- genuinely disabled: a true zero
    end if;
  elsif c.resolved_qty is not null then
    c.overhead := v_oh_rate * c.resolved_qty;
  end if;

  -- The total is the sum only when the variant resolves cleanly and every
  -- component is known. Anything else is not a cost.
  if fn_variant_problem(p_variant_id) is null
     and c.ingredients_labour is not null
     and c.packaging is not null
     and c.overhead is not null then
    c.total := c.ingredients_labour + c.packaging + c.overhead;
  end if;

  return c;
end
$fn$;

comment on function fn_variant_cost_components(uuid) is
  'What a sold unit of this variant costs, broken into ingredients-and-labour, '
  'packaging and overhead, plus the total. The single implementation behind '
  'both fn_variant_cost and fn_compute_variant_cost_snapshot.';

grant execute on function fn_variant_cost_components(uuid) to authenticated;

-- fn_variant_cost keeps its meaning exactly; it is now the total of the above.
create or replace function fn_variant_cost(p_variant_id uuid)
returns numeric
language plpgsql
stable
security definer
set search_path to 'public'
as $fn$
begin
  return (fn_variant_cost_components(p_variant_id)).total;
end
$fn$;

-- ---------------------------------------------------------------------------
-- 3. The snapshot writer stores the components rather than recomputing them
-- ---------------------------------------------------------------------------

create or replace function fn_compute_variant_cost_snapshot(
  p_variant_id uuid,
  p_as_of      date default current_date)
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  v record; base cost_snapshots%rowtype; c variant_cost_components;
  v_problem text; v_complete boolean; v_unpriced jsonb; v_id uuid;
begin
  select rv.account_id, rv.business_id, rv.recipe_id, rv.format_id,
         rv.costing_basis, r.yield_unit_id
    into v
    from recipe_variants rv
    join recipes r on r.id = rv.recipe_id
   where rv.id = p_variant_id;
  if v is null then
    raise exception 'Variant % does not exist', p_variant_id;
  end if;
  perform fn_require_cost_access(v.account_id);

  select * into base from cost_snapshots
   where recipe_id = v.recipe_id and variant_id is null
   order by computed_at desc, seq desc limit 1;
  if not found then
    raise exception 'Recipe % has no cost snapshot yet. Compute the recipe '
                    'cost before the variant cost.', v.recipe_id;
  end if;

  v_problem := fn_variant_problem(p_variant_id);
  c         := fn_variant_cost_components(p_variant_id);

  -- Completeness propagates upward exactly as it does for sub-recipes: a
  -- variant is complete only if its own basis resolves AND the recipe beneath
  -- it is complete.
  v_complete := base.is_complete and v_problem is null and c.total is not null;
  v_unpriced := coalesce(base.unpriced_items, '[]'::jsonb);
  if v_problem is not null then
    v_unpriced := v_unpriced || jsonb_build_object(
      'variant_id', p_variant_id, 'problem', v_problem);
  end if;

  insert into cost_snapshots (
      account_id, business_id, recipe_id, computed_at,
      costing_method, wavg_window_days,
      is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
      ingredient_cost, packaging_cost, labour_cost, overhead_cost,
      batch_cost, cost_per_yield_unit, cost_per_portion,
      floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
      created_by,
      variant_id, resolved_qty, resolved_unit_id, basis_used, format_packaging_cost,
      portion_qty_at_snapshot, variant_overhead_cost)
  values (
      v.account_id, v.business_id, v.recipe_id, now(),
      base.costing_method, base.wavg_window_days,
      v_complete, base.required_inputs, base.priced_inputs, base.excluded_inputs,
      v_unpriced,
      base.ingredient_cost, base.packaging_cost, base.labour_cost, base.overhead_cost,
      base.batch_cost, base.cost_per_yield_unit,
      c.total,                                  -- cost per SOLD UNIT, not per portion
      base.floor_batch_cost, base.floor_cost_per_yield_unit, base.floor_cost_per_portion,
      auth.uid(),
      p_variant_id, c.resolved_qty, v.yield_unit_id, v.costing_basis, c.packaging,
      -- a format-based sale has no portion; the sold unit IS the portion
      base.portion_qty_at_snapshot, c.overhead)
  returning id into v_id;

  return v_id;
end
$fn$;

-- ---------------------------------------------------------------------------
-- 4. The recipe writer records the portion size it used
--
-- Reproduced in full, with one column added to the INSERT. Nothing else in it
-- changes.
-- ---------------------------------------------------------------------------

create or replace function fn_compute_recipe_cost_snapshot(p_recipe_id uuid, p_as_of date DEFAULT CURRENT_DATE, p_created_by uuid DEFAULT auth.uid())
returns uuid
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  r recipes%rowtype; bs business_settings%rowtype; core recipe_cost_result;
  v_overhead numeric := 0; v_oh_total numeric; v_oh_rate numeric;
  v_sold_by_format boolean;
  v_required integer; v_priced integer; v_unpriced jsonb; v_complete boolean;
  v_floor_pp numeric; v_snapshot uuid;
begin
  select * into r from recipes where id = p_recipe_id and deleted_at is null;
  if not found then raise exception 'Recipe % not found', p_recipe_id; end if;

  perform fn_require_cost_access(r.account_id);   -- AUTHORIZATION

  select * into bs from business_settings where business_id = r.business_id;
  if not found then
    raise exception 'Business settings missing for business %', r.business_id;
  end if;

  core := fn__recipe_cost_core(p_recipe_id, p_as_of, 0);

  v_required := core.required_inputs;
  v_priced   := core.priced_inputs;
  v_unpriced := core.unpriced_items;
  v_complete := core.is_complete;

  -- MODEL 1 vs MODEL 2 (owner decision, Phase 4 escalation).
  -- A recipe sold through its own business-defined formats does not need a
  -- portion size: the FORMAT is the commercial unit, and fn_variant_cost
  -- allocates the batch economics to each format. A recipe with no active
  -- sellable format is portion-based and still requires one. This is not
  -- "portion is optional" -- exactly one basis applies, and which one is
  -- determined here rather than guessed.
  select exists (
    select 1
      from recipe_variants rv
      join serving_formats sf on sf.id = rv.format_id
     where rv.recipe_id = p_recipe_id
       and rv.is_active
       and sf.is_active
  ) into v_sold_by_format;

  if bs.overhead_enabled then
    v_required := v_required + 1;

    -- 0041: the reason now comes from fn_overhead_problem, which reads each
    -- overhead item's OWN basis and falls back to the business default. The
    -- decision is made once, in one place, rather than re-derived here.
    declare v_oh_problem text;
    begin
      v_oh_problem := fn_overhead_problem(r.business_id, r.yield_unit_id);
      if v_oh_problem is not null then
        v_complete := false;
        v_unpriced := v_unpriced || jsonb_build_object(
          'recipe_id', p_recipe_id, 'business_id', r.business_id,
          'problem', v_oh_problem);
        v_overhead := null;
      else
        v_oh_rate := fn_overhead_rate(r.business_id, r.yield_unit_id);
        if r.portion_qty is null then
          -- No portion size. For a FORMAT-BASED recipe that is correct:
          -- overhead is allocated per format by fn_variant_cost as
          -- overhead_rate x resolved_qty, so there is no per-portion figure
          -- to compute and none is invented.
          v_overhead := null;
          if v_sold_by_format then
            v_priced := v_priced + 1;
          end if;
        else
          v_overhead := v_oh_rate * r.portion_qty;
          v_priced   := v_priced + 1;
        end if;
      end if;
    end;
  end if;

  if r.kind = 'dish' and not v_sold_by_format then
    -- MODEL 1, portion-based: the portion is the commercial unit, so its size
    -- is a required input.
    v_required := v_required + 1;
    if r.portion_qty is null then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'problem', 'missing_portion_size');
    else
      v_priced := v_priced + 1;
    end if;
  end if;
  -- MODEL 2, format-based: no portion input is required and none is invented.
  -- Whether each format can actually be costed is decided per format by
  -- fn_variant_problem, which blocks on incompatible dimensions, missing
  -- conversions and unpriced packaging. A recipe can therefore be complete
  -- while one of its formats is not, which is the truth of the situation.

  if core.priced_inputs = 0 then
    v_floor_pp := null;
  elsif core.cost_per_yield_unit is not null and r.portion_qty is not null then
    v_floor_pp := core.cost_per_yield_unit * r.portion_qty + coalesce(v_overhead, 0);
  else
    v_floor_pp := null;
  end if;

  if jsonb_array_length(v_unpriced) > 0 then
    v_complete := false;
  end if;

  insert into cost_snapshots (
    account_id, business_id, recipe_id, computed_at,
    costing_method, wavg_window_days,
    is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
    ingredient_cost, packaging_cost, labour_cost, overhead_cost,
    batch_cost, cost_per_yield_unit, cost_per_portion,
    floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
    created_by,
    portion_qty_at_snapshot)
  values (
    r.account_id, r.business_id, p_recipe_id, now(),
    bs.costing_method, bs.wavg_window_days,
    v_complete, v_required, v_priced, core.excluded_inputs, v_unpriced,
    core.ingredient_cost, core.packaging_cost, core.labour_cost, v_overhead,
    case when v_complete then core.batch_cost end,
    case when v_complete then core.cost_per_yield_unit end,
    case when v_complete then v_floor_pp end,
    case when core.priced_inputs > 0 then core.batch_cost end,
    case when core.priced_inputs > 0 then core.cost_per_yield_unit end,
    v_floor_pp,
    p_created_by,
    -- 0046: the portion size actually used, recorded so the breakdown can be
    -- rebuilt later. recipes.portion_qty is mutable; this is not.
    r.portion_qty)
  returning id into v_snapshot;

  return v_snapshot;
end;
$fn$;

-- ---------------------------------------------------------------------------
-- 5. Self-check
--
-- Asserts the reconciliation invariant on every snapshot that now carries
-- component detail, not merely that the columns exist.
-- ---------------------------------------------------------------------------

do $$
declare v_pol int; v_bad int;
begin
  if not exists (select 1 from information_schema.columns
                  where table_name = 'cost_snapshots'
                    and column_name = 'portion_qty_at_snapshot')
   or not exists (select 1 from information_schema.columns
                  where table_name = 'cost_snapshots'
                    and column_name = 'variant_overhead_cost') then
    raise exception '0046 self-check FAILED: a provenance column is missing.';
  end if;
  if not exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
                  where n.nspname = 'public' and p.proname = 'fn_variant_cost_components') then
    raise exception '0046 self-check FAILED: fn_variant_cost_components is missing.';
  end if;

  -- Nothing already written may have moved. ADD COLUMN cannot change a value,
  -- but assert it rather than assume it.
  select count(*) into v_bad from cost_snapshots
   where portion_qty_at_snapshot is not null or variant_overhead_cost is not null;
  if v_bad > 0 then
    raise exception '0046 self-check FAILED: % pre-existing snapshot(s) gained detail.', v_bad;
  end if;

  select count(*) into v_pol from pg_policies where schemaname = 'public';
  if v_pol <> 116 then
    raise exception '0046 self-check FAILED: policy count moved to %.', v_pol;
  end if;
  raise notice '0046 OK: component provenance recorded, one implementation, 116 policies unchanged.';
end
$$;

-- ===================== 0047_sales_reporting.sql =====================
-- ============================================================================
-- MENU MASTER NG
-- 0047: what the sales actually made
--
-- Requires: 0001-0046 applied.
--
-- Two defects in the existing reporting are corrected here, and both matter
-- more than the new views.
--
-- P0 -- v_sales_unified counted drafts as revenue.
--   It admitted every order whose status was not 'cancelled'. Until 0045 an
--   order was born 'confirmed', so drafts were rare and the filter looked
--   harmless. Now that an order is born a draft, an unconfirmed order would be
--   reported as money taken. Revenue is now recognised at confirmation --
--   finalised_at -- which is the same boundary that freezes the cost, so
--   revenue and COGS can never be recognised at different moments.
--
-- P1 -- gross profit credited uncosted revenue as pure profit.
--   v_profit_by_period and v_profit_by_product computed
--   revenue - coalesce(sum(cogs), 0). sum() skips NULLs, so a line with no
--   frozen cost contributed its full revenue and no cost, and the reported
--   margin rose exactly when the least was known. Gross profit is now
--   costed_revenue - cogs: margin is measured only over the sales whose cost
--   is actually known, and coverage is reported beside it so the owner can see
--   how much of the picture that is. cost_coverage_pct already existed to warn
--   about this; the profit figure itself did not listen to it.
--
-- Revenue is also now net of discounts. Gross revenue, the line discount, the
-- allocated share of the order discount and net revenue are all carried
-- separately, so a discount is visible as a decision rather than buried in a
-- smaller number.
--
-- Every view here is security_invoker: it sees exactly what its caller may
-- see, and no more. The option is restated on every single one -- CREATE OR
-- REPLACE VIEW does not preserve reloptions, and pg_views.definition does not
-- show them, so a fingerprint check cannot catch its loss. Only an explicit
-- assertion can, and tests/027 makes it.
-- ============================================================================

do $$
begin
  if not exists (select 1 from information_schema.columns
                  where table_name = 'cost_snapshots' and column_name = 'variant_overhead_cost') then
    raise exception '0047 preflight FAILED: 0046 has not been applied.';
  end if;
  if exists (select 1 from pg_views where schemaname = 'public'
              and viewname in ('v_sale_lines','v_sales_summary','v_product_performance',
                               'v_orders_attention','v_sale_cost_breakdown')) then
    raise exception '0047 preflight FAILED: one of the new views already exists.';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public') <> 116 then
    raise exception '0047 preflight FAILED: policy count is %, expected 116.',
      (select count(*) from pg_policies where schemaname = 'public');
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. Rebuild the shared sales grain
--
-- Dropped rather than replaced: CREATE OR REPLACE VIEW cannot reorder or
-- remove a column, and this needs both. Dropping discards grants, so every
-- grant is restated at the end of each block -- the omission that had to be
-- repaired twice in 0036 and 0042.
-- ---------------------------------------------------------------------------

drop view if exists v_dashboard_waterfall;
drop view if exists v_profit_by_product;
drop view if exists v_profit_by_period;
drop view if exists v_sales_unified;

create view v_sales_unified with (security_invoker = on) as
  -- Confirmed order lines. finalised_at is the recognition boundary: it is set
  -- in the same statement that freezes the costs, so a sale never appears in
  -- revenue before its cost is frozen.
  select ol.account_id,
         o.business_id,
         'order'::text                     as source,
         ol.id                             as record_id,
         o.id                              as order_id,
         o.order_no                        as reference,
         o.order_date                      as sale_date,
         o.channel_id,
         o.customer_id,
         ol.recipe_id,
         ol.variant_id,
         ol.qty,
         ol.unit_price,
         a.gross_revenue,
         a.line_discount,
         a.allocated_order_discount,
         a.net_revenue                     as revenue,
         ol.unit_cost_at_sale,
         ol.cost_snapshot_id,
         case when ol.unit_cost_at_sale is not null
              then round(ol.qty * ol.unit_cost_at_sale, 2) end as cogs
    from order_lines ol
    join orders o on o.id = ol.order_id
    join fn_allocate_order_discount() a on a.order_line_id = ol.id
   where o.finalised_at is not null
     and o.voided_at is null
     and o.status <> 'cancelled'

  union all

  -- A daily total. It has no draft state and no discount fields; a quick sale
  -- is recorded at the price actually taken.
  select se.account_id,
         se.business_id,
         'daily_total'::text               as source,
         se.id                             as record_id,
         null::uuid                        as order_id,
         null::text                        as reference,
         se.sale_date,
         se.channel_id,
         null::uuid                        as customer_id,
         se.recipe_id,
         se.variant_id,
         se.qty,
         se.unit_price,
         round(se.qty * se.unit_price, 2)  as gross_revenue,
         0::numeric(14,2)                  as line_discount,
         0::numeric(14,2)                  as allocated_order_discount,
         round(se.qty * se.unit_price, 2)  as revenue,
         se.unit_cost_at_sale,
         se.cost_snapshot_id,
         case when se.unit_cost_at_sale is not null
              then round(se.qty * se.unit_cost_at_sale, 2) end as cogs
    from sales_entries se
   where se.voided_at is null;

comment on view v_sales_unified is
  'Every recognised sale at line grain, from orders and daily totals alike. '
  'An order appears only once confirmed, which is the same instant its cost '
  'was frozen.';

grant select on v_sales_unified to authenticated;

-- ---------------------------------------------------------------------------
-- 2. Profit, measured only over what is actually known
-- ---------------------------------------------------------------------------

create view v_profit_by_period with (security_invoker = on) as
  select account_id,
         business_id,
         date_trunc('month', sale_date::timestamptz)::date as period,
         round(sum(revenue), 2)                            as revenue,
         round(sum(revenue) filter (where cogs is not null), 2) as costed_revenue,
         round(sum(cogs), 2)                               as cogs,
         -- Only the costed subset. Crediting uncosted revenue as pure profit
         -- would flatter the margin exactly where least is known.
         round(sum(revenue) filter (where cogs is not null) - sum(cogs), 2) as gross_profit,
         round(100.0 * (sum(revenue) filter (where cogs is not null) - sum(cogs))
               / nullif(sum(revenue) filter (where cogs is not null), 0), 2) as gross_margin_pct,
         round(100.0 * coalesce(sum(revenue) filter (where cogs is not null), 0)
               / nullif(sum(revenue), 0), 2)               as cost_coverage_pct,
         round(coalesce(sum(revenue) filter (where cogs is null), 0), 2) as revenue_without_cost
    from v_sales_unified
   group by account_id, business_id, date_trunc('month', sale_date::timestamptz);

comment on view v_profit_by_period is
  'Monthly trading. gross_profit is costed_revenue minus cogs, never revenue '
  'minus cogs: a sale with no known cost contributes to revenue and coverage, '
  'and to neither profit nor margin.';

grant select on v_profit_by_period to authenticated;

create view v_profit_by_product with (security_invoker = on) as
  select s.account_id,
         s.business_id,
         s.recipe_id,
         r.name,
         round(sum(s.qty), 3)                                as units_sold,
         round(sum(s.revenue), 2)                            as revenue,
         round(sum(s.revenue) filter (where s.cogs is not null), 2) as costed_revenue,
         round(sum(s.cogs), 2)                               as cogs,
         round(sum(s.revenue) filter (where s.cogs is not null) - sum(s.cogs), 2) as gross_profit,
         round(100.0 * (sum(s.revenue) filter (where s.cogs is not null) - sum(s.cogs))
               / nullif(sum(s.revenue) filter (where s.cogs is not null), 0), 2) as gross_margin_pct,
         round(100.0 * coalesce(sum(s.revenue) filter (where s.cogs is not null), 0)
               / nullif(sum(s.revenue), 0), 2)               as cost_coverage_pct
    from v_sales_unified s
    join recipes r on r.id = s.recipe_id
   group by s.account_id, s.business_id, s.recipe_id, r.name;

comment on view v_profit_by_product is
  'Trading by dish. Same profit rule as v_profit_by_period.';

grant select on v_profit_by_product to authenticated;

create view v_dashboard_waterfall with (security_invoker = on) as
  select business_id,
         account_id,
         period,
         revenue,
         costed_revenue,
         cogs,
         gross_profit,
         gross_margin_pct,
         cost_coverage_pct,
         revenue_without_cost,
         case
           when cost_coverage_pct is null      then 'no_sales'
           when cost_coverage_pct >= 100       then 'complete'
           when cost_coverage_pct >= 80        then 'mostly_covered'
           else 'partial'
         end as confidence
    from v_profit_by_period;

grant select on v_dashboard_waterfall to authenticated;

-- ---------------------------------------------------------------------------
-- 3. v_sale_lines -- the line an owner actually looks at
--
-- Drafts are included and labelled, because an owner building an order needs
-- to see it. Only cancelled and voided orders are excluded. A draft's revenue
-- columns are what it WOULD be worth; is_confirmed says which is which, and
-- no summary view here counts a draft.
-- ---------------------------------------------------------------------------

create view v_sale_lines with (security_invoker = on) as
  select ol.id                              as line_id,
         ol.account_id,
         ol.business_id,
         o.id                               as order_id,
         o.order_no,
         o.order_date,
         o.status                           as order_status,
         (o.finalised_at is not null)       as is_confirmed,
         o.payment_status,
         o.customer_id,
         c.name                             as customer_name,
         o.channel_id,
         ol.recipe_id,
         r.name                             as product_name,
         ol.variant_id,
         f.name                             as format_name,
         ol.description,
         ol.qty,
         ol.unit_price,
         a.gross_revenue,
         a.line_discount,
         a.allocated_order_discount,
         a.net_revenue,
         ol.unit_cost_at_sale,
         case when ol.unit_cost_at_sale is not null
              then round(ol.qty * ol.unit_cost_at_sale, 2) end as cogs,
         -- Profit only where the cost is known. Never net_revenue - 0.
         case when ol.unit_cost_at_sale is not null
              then round(a.net_revenue - ol.qty * ol.unit_cost_at_sale, 2) end as gross_profit,
         case when ol.unit_cost_at_sale is not null and a.net_revenue <> 0
              then round(100.0 * (a.net_revenue - ol.qty * ol.unit_cost_at_sale)
                         / a.net_revenue, 2) end as gross_margin_pct,
         case
           when ol.recipe_id is null              then 'no_product'
           when ol.unit_cost_at_sale is not null  then 'costed'
           when o.finalised_at is null            then 'not_costed_yet'
           else                                        'sold_without_cost'
         end                                as cost_status
    from order_lines ol
    join orders o   on o.id = ol.order_id
    join fn_allocate_order_discount() a on a.order_line_id = ol.id
    left join customers c on c.id = o.customer_id
    left join recipes r   on r.id = ol.recipe_id
    left join recipe_variants rv on rv.id = ol.variant_id
    left join serving_formats f  on f.id = rv.format_id
   where o.voided_at is null
     and o.status <> 'cancelled';

comment on view v_sale_lines is
  'Order lines with revenue, discounts, frozen cost and margin. Drafts are '
  'included and marked is_confirmed = false; cancelled and voided orders are '
  'not shown here at all -- v_voided_sales keeps those inspectable.';

grant select on v_sale_lines to authenticated;

-- ---------------------------------------------------------------------------
-- 4. v_sales_summary -- one row per trading day
--
-- The day, its week and its month are all on the row, so a caller can group at
-- any of the three without three separate views drifting apart.
-- ---------------------------------------------------------------------------

create view v_sales_summary with (security_invoker = on) as
  select account_id,
         business_id,
         sale_date,
         date_trunc('week',  sale_date::timestamptz)::date as week_start,
         date_trunc('month', sale_date::timestamptz)::date as month_start,
         count(distinct case when source = 'order' then order_id end)
           + count(*) filter (where source = 'daily_total')     as sale_count,
         round(sum(gross_revenue), 2)                           as gross_revenue,
         round(sum(line_discount + allocated_order_discount), 2) as discount_given,
         round(sum(revenue), 2)                                 as revenue,
         round(sum(revenue) filter (where cogs is not null), 2)  as costed_revenue,
         round(sum(cogs), 2)                                    as cogs,
         round(sum(revenue) filter (where cogs is not null) - sum(cogs), 2) as gross_profit,
         round(100.0 * (sum(revenue) filter (where cogs is not null) - sum(cogs))
               / nullif(sum(revenue) filter (where cogs is not null), 0), 2) as gross_margin_pct,
         round(100.0 * coalesce(sum(revenue) filter (where cogs is not null), 0)
               / nullif(sum(revenue), 0), 2)                    as cost_coverage_pct,
         round(coalesce(sum(revenue) filter (where cogs is null), 0), 2) as revenue_without_cost
    from v_sales_unified
   group by account_id, business_id, sale_date;

comment on view v_sales_summary is
  'A trading day: what was sold, what was given away in discounts, what it '
  'cost, and how much of that cost is actually known.';

grant select on v_sales_summary to authenticated;

-- ---------------------------------------------------------------------------
-- 5. v_product_performance -- what sells, and what is worth selling
--
-- At variant grain where a variant was sold, because a 2.5 litre pot and a
-- 1 litre pot are different products with different economics.
-- ---------------------------------------------------------------------------

create view v_product_performance with (security_invoker = on) as
  select s.account_id,
         s.business_id,
         s.recipe_id,
         r.name                                              as product_name,
         s.variant_id,
         f.name                                              as format_name,
         round(sum(s.qty), 3)                                as units_sold,
         round(sum(s.revenue), 2)                            as revenue,
         round(sum(s.revenue) filter (where s.cogs is not null), 2) as costed_revenue,
         round(sum(s.cogs), 2)                               as cogs,
         round(sum(s.revenue) filter (where s.cogs is not null) - sum(s.cogs), 2) as gross_profit,
         round(100.0 * (sum(s.revenue) filter (where s.cogs is not null) - sum(s.cogs))
               / nullif(sum(s.revenue) filter (where s.cogs is not null), 0), 2) as gross_margin_pct,
         round(100.0 * coalesce(sum(s.revenue) filter (where s.cogs is not null), 0)
               / nullif(sum(s.revenue), 0), 2)               as cost_coverage_pct,
         min(s.sale_date)                                    as first_sold,
         max(s.sale_date)                                    as last_sold,
         -- A verdict only where there is something to judge. An unknown margin
         -- is 'unknown', never 'healthy'.
         case
           when sum(s.revenue) filter (where s.cogs is not null) is null
             or sum(s.revenue) filter (where s.cogs is not null) = 0 then 'unknown'
           when sum(s.revenue) filter (where s.cogs is not null) - sum(s.cogs) < 0 then 'losing_money'
           when 100.0 * (sum(s.revenue) filter (where s.cogs is not null) - sum(s.cogs))
                / nullif(sum(s.revenue) filter (where s.cogs is not null), 0) < 20 then 'thin'
           else 'healthy'
         end                                                 as margin_verdict
    from v_sales_unified s
    join recipes r on r.id = s.recipe_id
    left join recipe_variants rv on rv.id = s.variant_id
    left join serving_formats f  on f.id = rv.format_id
   group by s.account_id, s.business_id, s.recipe_id, r.name, s.variant_id, f.name;

comment on view v_product_performance is
  'Sales and margin by product and, where one was sold, by serving format. '
  'margin_verdict is unknown -- not healthy -- when the cost is not known.';

grant select on v_product_performance to authenticated;

-- ---------------------------------------------------------------------------
-- 6. v_orders_attention -- orders that need the owner to do something
-- ---------------------------------------------------------------------------

create view v_orders_attention with (security_invoker = on) as
  select o.id                                as order_id,
         o.account_id,
         o.business_id,
         o.order_no,
         o.order_date,
         o.status,
         o.payment_status,
         o.customer_id,
         c.name                              as customer_name,
         l.line_count,
         l.gross_revenue,
         o.order_discount,
         l.net_revenue,
         l.lines_without_cost,
         o.amount_paid,
         round(coalesce(l.net_revenue, 0) - o.amount_paid, 2) as amount_outstanding,
         current_date - o.order_date         as days_old,
         case
           when o.finalised_at is null and l.line_count = 0 then 'empty_draft'
           when o.finalised_at is null                      then 'draft_not_confirmed'
           when l.lines_without_cost > 0                    then 'sold_without_cost'
           when o.payment_status <> 'paid'
            and current_date - o.order_date > 7             then 'unpaid_over_a_week'
           else                                                  'ok'
         end                                 as attention,
         case
           when o.finalised_at is null and l.line_count = 0
             then 'This order has nothing on it yet.'
           when o.finalised_at is null
             then 'Still a draft. Its costs are not locked in until you confirm it.'
           when l.lines_without_cost > 0
             then 'Sold, but we do not know what some of it cost you.'
           when o.payment_status <> 'paid' and current_date - o.order_date > 7
             then 'Confirmed over a week ago and still not paid in full.'
           else 'Nothing needed.'
         end                                 as what_to_do
    from orders o
    left join customers c on c.id = o.customer_id
    left join lateral (
      select count(*)                                            as line_count,
             round(sum(sl.gross_revenue), 2)                     as gross_revenue,
             round(sum(sl.net_revenue), 2)                       as net_revenue,
             count(*) filter (where sl.unit_cost_at_sale is null
                                and sl.recipe_id is not null)    as lines_without_cost
        from v_sale_lines sl
       where sl.order_id = o.id
    ) l on true
   where o.voided_at is null
     and o.status <> 'cancelled';

comment on view v_orders_attention is
  'One row per live order with what, if anything, it needs. what_to_do is '
  'written for the owner, not for a developer.';

grant select on v_orders_attention to authenticated;

-- ---------------------------------------------------------------------------
-- 7. v_sale_cost_breakdown -- why a frozen cost is what it is
--
-- Reads the snapshot frozen onto the line, never today's configuration. Where
-- a snapshot predates 0046 the component columns are NULL and reconciles is
-- NULL: detail that was never recorded is reported as missing, not as zero.
-- ---------------------------------------------------------------------------

create view v_sale_cost_breakdown with (security_invoker = on) as
  select ol.id                              as line_id,
         ol.account_id,
         ol.business_id,
         ol.order_id,
         ol.recipe_id,
         ol.variant_id,
         ol.qty,
         ol.unit_cost_at_sale,
         cs.id                              as cost_snapshot_id,
         cs.computed_at                     as cost_frozen_at,
         cs.costing_method,
         cs.basis_used,
         cs.resolved_qty,
         cs.cost_per_yield_unit,
         cs.portion_qty_at_snapshot,
         -- A variant sale carries its own packaging and overhead; a portion
         -- sale carries the recipe's.
         coalesce(cs.format_packaging_cost, cs.packaging_cost) as packaging_cost,
         coalesce(cs.variant_overhead_cost,  cs.overhead_cost)  as overhead_cost,
         case
           when cs.variant_id is not null
            and cs.cost_per_yield_unit is not null
            and cs.resolved_qty is not null
             then round(cs.cost_per_yield_unit * cs.resolved_qty, 4)
           when cs.variant_id is null
            and cs.cost_per_yield_unit is not null
            and cs.portion_qty_at_snapshot is not null
             then round(cs.cost_per_yield_unit * cs.portion_qty_at_snapshot, 4)
         end                                as ingredients_and_labour,
         cs.is_complete,
         cs.unpriced_items
    from order_lines ol
    join orders o on o.id = ol.order_id
    join cost_snapshots cs on cs.id = ol.cost_snapshot_id
   where o.voided_at is null;

comment on view v_sale_cost_breakdown is
  'The components behind a line''s frozen cost, read from the snapshot that '
  'was frozen onto it. NULL components mean detail that was never recorded, '
  'which is not the same as zero.';

grant select on v_sale_cost_breakdown to authenticated;

-- ---------------------------------------------------------------------------
-- 8. Self-check
-- ---------------------------------------------------------------------------

do $$
declare v_pol int; v_missing text;
begin
  select string_agg(v, ', ') into v_missing
    from unnest(array['v_sales_unified','v_profit_by_period','v_profit_by_product',
                      'v_dashboard_waterfall','v_sale_lines','v_sales_summary',
                      'v_product_performance','v_orders_attention',
                      'v_sale_cost_breakdown']) v
   where not exists (select 1 from pg_views where schemaname = 'public' and viewname = v);
  if v_missing is not null then
    raise exception '0047 self-check FAILED: missing view(s): %', v_missing;
  end if;

  -- Every one of them must be security_invoker. This is the check a definition
  -- fingerprint cannot make.
  select string_agg(c.relname, ', ') into v_missing
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'v'
     and c.relname in ('v_sales_unified','v_profit_by_period','v_profit_by_product',
                       'v_dashboard_waterfall','v_sale_lines','v_sales_summary',
                       'v_product_performance','v_orders_attention','v_sale_cost_breakdown')
     and not coalesce('security_invoker=on' = any(c.reloptions), false);
  if v_missing is not null then
    raise exception '0047 self-check FAILED: not security_invoker: %', v_missing;
  end if;

  -- Grants are discarded by DROP VIEW. Assert they came back.
  select string_agg(v, ', ') into v_missing
    from unnest(array['v_sales_unified','v_profit_by_period','v_profit_by_product',
                      'v_dashboard_waterfall','v_sale_lines','v_sales_summary',
                      'v_product_performance','v_orders_attention',
                      'v_sale_cost_breakdown']) v
   where not exists (select 1 from information_schema.role_table_grants g
                      where g.table_schema = 'public' and g.table_name = v
                        and g.grantee = 'authenticated' and g.privilege_type = 'SELECT');
  if v_missing is not null then
    raise exception '0047 self-check FAILED: authenticated cannot read: %', v_missing;
  end if;

  -- A draft must never appear as revenue.
  if exists (select 1 from v_sales_unified s
              join orders o on o.id = s.order_id
             where o.finalised_at is null) then
    raise exception '0047 self-check FAILED: an unconfirmed order is being reported as revenue.';
  end if;

  select count(*) into v_pol from pg_policies where schemaname = 'public';
  if v_pol <> 116 then
    raise exception '0047 self-check FAILED: policy count moved to %.', v_pol;
  end if;
  raise notice '0047 OK: revenue recognised at confirmation, profit measured only where cost is known.';
end
$$;

-- ===================== 0048_function_grant_surface.sql =====================
-- ============================================================================
-- MENU MASTER NG
-- 0048: the function grant surface, restored and kept restored
--
-- Requires: 0001-0047 applied.
--
-- 0018 removed EXECUTE on every fn_* from PUBLIC and from anon. It did that
-- once, in a loop, over the functions that existed that day. It was never an
-- invariant -- nothing re-applied it -- so every migration since has added
-- functions that arrive with PostgreSQL's default of EXECUTE to PUBLIC, and
-- PUBLIC includes anon.
--
-- Found during Phase 6 by asking a question the tests had never asked: which
-- functions can a logged-out caller execute? Eleven, of which nine were added
-- after the sweep:
--
--   fn_ingredient_cost_basis     0034
--   fn_overhead_breakdown        0041
--   fn_overhead_problem          0041
--   fn_allocate_order_discount   0044
--   fn_guard_order_discount      0044
--   fn_order_line_scope          0043
--   fn_confirm_order             0045   (already narrowed in 0045)
--   fn_frozen_sale_cost          0045   (already narrowed in 0045)
--   fn_variant_cost_components   0046
--   plus fn_guard_subscription_changes and fn_payment_failure_grace
--
-- Most were harmless in practice: a trigger function cannot be usefully called
-- by hand, and the invoker-rights ones still meet row level security. The ones
-- that mattered were SECURITY DEFINER, and the one that mattered most --
-- fn_frozen_sale_cost -- took an account id it did not check, which made it a
-- cost-reading service for anybody able to guess one. That is fixed in 0045,
-- where it was introduced.
--
-- This migration repairs the surface and, more importantly, ends the pattern:
-- tests/034 now asserts the rule on every function, so the next one added
-- without a grant line fails the suite instead of shipping.
--
-- Nothing about what an authenticated user may do changes. Only what an
-- unauthenticated one may reach.
-- ============================================================================

do $$
begin
  if not exists (select 1 from pg_views where schemaname = 'public' and viewname = 'v_sale_lines') then
    raise exception '0048 preflight FAILED: 0047 has not been applied.';
  end if;
  if (select count(*) from pg_policies where schemaname = 'public') <> 116 then
    raise exception '0048 preflight FAILED: policy count is %, expected 116.',
      (select count(*) from pg_policies where schemaname = 'public');
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- 1. Remove PUBLIC and anon from every Menu Master function
--
-- Restricted to fn_* and to functions not owned by an extension, exactly as
-- 0018 was: pgcrypto's helpers and PostgREST's own pre-request hook are not
-- ours to re-privilege, and local_pre_request must stay reachable or every
-- request in the local harness stops.
-- ---------------------------------------------------------------------------

do $$
declare f record; v_n int := 0;
begin
  for f in
    select p.oid::regprocedure as sig
      from pg_proc p
     where p.pronamespace = 'public'::regnamespace
       and p.proname like 'fn\_%'
       and not exists (select 1 from pg_depend d where d.objid = p.oid and d.deptype = 'e')
  loop
    execute format('revoke all on function %s from public, anon', f.sig);
    v_n := v_n + 1;
  end loop;
  raise notice '0048: EXECUTE removed from public and anon on % function(s).', v_n;
end
$$;

-- ---------------------------------------------------------------------------
-- 2. Restore what an authenticated user must be able to call
--
-- Revoking from PUBLIC removes the privilege an authenticated caller was
-- relying on wherever it was never granted to the role directly. These are the
-- functions added since 0018 that the application, or a security_invoker view,
-- actually calls. Everything else on that list is a trigger function, which the
-- trigger mechanism invokes regardless of EXECUTE.
-- ---------------------------------------------------------------------------

grant execute on function fn_ingredient_cost_basis(uuid, uuid, date)          to authenticated;
grant execute on function fn_overhead_breakdown(uuid, uuid)                   to authenticated;
grant execute on function fn_overhead_problem(uuid, uuid)                     to authenticated;
grant execute on function fn_allocate_order_discount(uuid)                    to authenticated;
grant execute on function fn_confirm_order(uuid)                              to authenticated;
grant execute on function fn_frozen_sale_cost(uuid, uuid, uuid)               to authenticated;
grant execute on function fn_variant_cost_components(uuid)                    to authenticated;

-- ---------------------------------------------------------------------------
-- 3. Self-check
-- ---------------------------------------------------------------------------

do $$
declare v_pol int; v_left text;
begin
  select string_agg(p.proname, ', ' order by p.proname) into v_left
    from pg_proc p
   where p.pronamespace = 'public'::regnamespace
     and p.proname like 'fn\_%'
     and (p.proacl is null or '=X/postgres' = any(p.proacl::text[]));
  if v_left is not null then
    raise exception '0048 self-check FAILED: still executable by public: %', v_left;
  end if;

  select string_agg(p.proname, ', ' order by p.proname) into v_left
    from pg_proc p
   where p.pronamespace = 'public'::regnamespace
     and p.proname like 'fn\_%'
     and 'anon=X/postgres' = any(p.proacl::text[]);
  if v_left is not null then
    raise exception '0048 self-check FAILED: still executable by anon: %', v_left;
  end if;

  -- PostgREST calls this on every request. If it stops being executable the
  -- whole API stops, so it is asserted rather than assumed.
  if not has_function_privilege('authenticator', 'local_pre_request()', 'execute')
     and exists (select 1 from pg_roles where rolname = 'authenticator') then
    raise exception '0048 self-check FAILED: the pre-request hook is no longer callable.';
  end if;

  -- The functions the application and the security_invoker views call.
  select string_agg(f, ', ') into v_left
    from unnest(array[
      'fn_ingredient_cost_basis(uuid,uuid,date)', 'fn_overhead_breakdown(uuid,uuid)',
      'fn_overhead_problem(uuid,uuid)', 'fn_allocate_order_discount(uuid)',
      'fn_confirm_order(uuid)', 'fn_frozen_sale_cost(uuid,uuid,uuid)',
      'fn_variant_cost_components(uuid)']) f
   where not has_function_privilege('authenticated', f, 'execute');
  if v_left is not null then
    raise exception '0048 self-check FAILED: authenticated lost access to: %', v_left;
  end if;

  select count(*) into v_pol from pg_policies where schemaname = 'public';
  if v_pol <> 116 then
    raise exception '0048 self-check FAILED: policy count moved to %.', v_pol;
  end if;
  raise notice '0048 OK: no function is executable by public or anon, 116 policies unchanged.';
end
$$;

commit;
