-- ============================================================================
-- ROLLBACK -- the whole 0034-0048 chain, reversed, in ONE transaction.
--
-- GENERATED by scripts/build_phase6_rollback.sh. Do not hand-edit.
-- Sources, in reverse order, with checksums:
--   fda2de06eee2954b  0048_rollback.sql
--   3c7c997729686d8d  0047_rollback.sql
--   16aac46e45a463c9  0046_rollback.sql
--   ec86e09088e8faa3  0045_rollback.sql
--   254cceee7fa3e5fe  0044_rollback.sql
--   fa1ad7c2dd966cd9  0043_rollback.sql
--   6aa092cb227010d0  0042_rollback.sql
--   c6723a3b90b0d065  0041_rollback.sql
--   6a68f16fc14dc9ad  0040_rollback.sql
--   013b7e1c7deff40a  0039_rollback.sql
--   b3e93e3d8ded48a5  0038_rollback.sql
--   2ad00758a0db120a  0037_rollback.sql
--   dff711ccd2f40e34  0036_rollback.sql
--   cb9f5e9f216f1ead  0035_rollback.sql
--   52db38664894778d  0034_rollback.sql
--
-- Run it as ONE buffer. Either the whole reversal happens or none of it
-- does; there is no half-rolled-back state to explain.
--
-- ONLY run this if STEP 2 COMMITTED and a later gate then failed. If STEP 2
-- itself failed it already undid itself and there is nothing here to do.
--
-- WHAT IT DOES NOT UNDO, deliberately:
--   Any sale confirmed after the deploy keeps its frozen cost. Those are
--     real sales and unfreezing them would destroy real economics.
--   Any finalised_at that 0045 recorded on a legacy order stays. On this
--     database that is nothing at all -- production holds zero orders -- but
--     the rule is stated so it stays true when that changes.
--   auth.users is never touched, here or in the forward migration.
-- ============================================================================

begin;

-- ===================== 0048_rollback.sql =====================
-- Rollback for 0048.
--
-- Restores EXECUTE to PUBLIC on the functions that carried it before this
-- migration -- which is to say, it puts the drift back. It exists because a
-- rollback must be honest about what it undoes, not because there is any
-- reason to run it.
--
-- It does NOT restore fn_frozen_sale_cost's missing membership check: that fix
-- lives in 0045 and is a correctness matter, not a grant.

grant execute on function fn_ingredient_cost_basis(uuid, uuid, date) to public;
grant execute on function fn_overhead_breakdown(uuid, uuid)         to public;
grant execute on function fn_overhead_problem(uuid, uuid)           to public;
grant execute on function fn_allocate_order_discount(uuid)          to public;
grant execute on function fn_guard_order_discount()                 to public;
grant execute on function fn_order_line_scope()                     to public;
grant execute on function fn_guard_order_lifecycle()                to public;
grant execute on function fn_confirm_order(uuid)                    to public;
grant execute on function fn_frozen_sale_cost(uuid, uuid, uuid)     to public;
grant execute on function fn_variant_cost_components(uuid)          to public;
grant execute on function fn_guard_subscription_changes()           to public;
grant execute on function fn_payment_failure_grace()                to public;

do $$
begin
  if (select count(*) from pg_proc p
       where p.pronamespace = 'public'::regnamespace
         and p.proname like 'fn\_%'
         and '=X/postgres' = any(p.proacl::text[])) <> 12 then
    raise exception '0048 rollback FAILED: the previous grant surface was not restored exactly.';
  end if;
  raise notice '0048 rollback OK: the pre-0048 grant surface is back, drift included.';
end
$$;


-- ===================== 0047_rollback.sql =====================
-- Rollback for 0047.
--
-- Restores v_sales_unified, v_profit_by_period, v_profit_by_product and
-- v_dashboard_waterfall to their 0046 definitions, and removes the five new
-- views.
--
-- Two things this deliberately restores are DEFECTS, and rolling back means
-- accepting them again:
--   v_sales_unified will count unconfirmed drafts as revenue, which after 0045
--     means most orders, and
--   gross profit will again credit uncosted revenue as pure profit.
-- Roll back only to unblock, and go forward again quickly.
--
-- security_invoker and the grants are restated on every view: DROP VIEW
-- discards both, and a definition fingerprint cannot see either.

drop view if exists v_sale_cost_breakdown;
drop view if exists v_orders_attention;
drop view if exists v_product_performance;
drop view if exists v_sales_summary;
drop view if exists v_sale_lines;

drop view if exists v_dashboard_waterfall;
drop view if exists v_profit_by_product;
drop view if exists v_profit_by_period;
drop view if exists v_sales_unified;

create view v_sales_unified with (security_invoker = on) as
  select ol.account_id,
         o.business_id,
         o.order_date as sale_date,
         o.channel_id,
         ol.recipe_id,
         ol.qty,
         ol.unit_price,
         ol.line_total as revenue,
         ol.unit_cost_at_sale,
         ol.cost_snapshot_id,
         case when ol.unit_cost_at_sale is not null
              then ol.qty * ol.unit_cost_at_sale end as cogs,
         'order'::text as source
    from order_lines ol
    join orders o on o.id = ol.order_id
   where o.status <> 'cancelled'::order_status and o.voided_at is null
  union all
  select se.account_id,
         se.business_id,
         se.sale_date,
         se.channel_id,
         se.recipe_id,
         se.qty,
         se.unit_price,
         se.qty * se.unit_price as revenue,
         se.unit_cost_at_sale,
         se.cost_snapshot_id,
         case when se.unit_cost_at_sale is not null
              then se.qty * se.unit_cost_at_sale end as cogs,
         'daily_total'::text as source
    from sales_entries se
   where se.voided_at is null;

grant select, insert, update, delete on v_sales_unified to authenticated;

create view v_profit_by_period with (security_invoker = on) as
  select account_id,
         business_id,
         date_trunc('month', sale_date::timestamptz)::date as period,
         round(sum(revenue), 2) as revenue,
         round(sum(cogs), 2) as cogs,
         round(sum(revenue) - coalesce(sum(cogs), 0), 2) as gross_profit,
         round(100.0 * (sum(revenue) - coalesce(sum(cogs), 0))
               / nullif(sum(revenue), 0), 2) as gross_margin_pct,
         round(100.0 * sum(case when unit_cost_at_sale is not null then revenue else 0 end)
               / nullif(sum(revenue), 0), 2) as cost_coverage_pct,
         round(sum(case when unit_cost_at_sale is null then revenue else 0 end), 2)
           as revenue_without_cost
    from v_sales_unified
   group by account_id, business_id, date_trunc('month', sale_date::timestamptz);

grant select, insert, update, delete on v_profit_by_period to authenticated;

create view v_profit_by_product with (security_invoker = on) as
  select s.account_id,
         s.business_id,
         s.recipe_id,
         r.name,
         round(sum(s.qty), 3) as units_sold,
         round(sum(s.revenue), 2) as revenue,
         round(sum(s.cogs), 2) as cogs,
         round(sum(s.revenue) - coalesce(sum(s.cogs), 0), 2) as gross_profit,
         round(100.0 * (sum(s.revenue) - coalesce(sum(s.cogs), 0))
               / nullif(sum(s.revenue), 0), 2) as gross_margin_pct,
         round(100.0 * sum(case when s.unit_cost_at_sale is not null then s.revenue else 0 end)
               / nullif(sum(s.revenue), 0), 2) as cost_coverage_pct
    from v_sales_unified s
    join recipes r on r.id = s.recipe_id
   group by s.account_id, s.business_id, s.recipe_id, r.name;

grant select, insert, update, delete on v_profit_by_product to authenticated;

create view v_dashboard_waterfall with (security_invoker = on) as
  select business_id, account_id, period, revenue, cogs, gross_profit,
         gross_margin_pct, cost_coverage_pct, revenue_without_cost,
         case
           when cost_coverage_pct is null then 'no_sales'
           when cost_coverage_pct >= 100  then 'complete'
           when cost_coverage_pct >= 80   then 'mostly_covered'
           else 'partial'
         end as confidence
    from v_profit_by_period;

grant select, insert, update, delete on v_dashboard_waterfall to authenticated;

do $$
declare v_bad text;
begin
  if exists (select 1 from pg_views where schemaname = 'public'
              and viewname in ('v_sale_lines','v_sales_summary','v_product_performance',
                               'v_orders_attention','v_sale_cost_breakdown')) then
    raise exception '0047 rollback FAILED: a Phase 6 view survived.';
  end if;
  select string_agg(c.relname, ', ') into v_bad
    from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'public' and c.relkind = 'v'
     and c.relname in ('v_sales_unified','v_profit_by_period','v_profit_by_product',
                       'v_dashboard_waterfall')
     and not coalesce('security_invoker=on' = any(c.reloptions), false);
  if v_bad is not null then
    raise exception '0047 rollback FAILED: restored without security_invoker: %', v_bad;
  end if;
  select string_agg(v, ', ') into v_bad
    from unnest(array['v_sales_unified','v_profit_by_period','v_profit_by_product',
                      'v_dashboard_waterfall']) v
   where not exists (select 1 from information_schema.role_table_grants g
                      where g.table_schema = 'public' and g.table_name = v
                        and g.grantee = 'authenticated' and g.privilege_type = 'SELECT');
  if v_bad is not null then
    raise exception '0047 rollback FAILED: authenticated cannot read: %', v_bad;
  end if;
  raise notice '0047 rollback OK: pre-0047 reporting restored, with its known defects.';
end
$$;


-- ===================== 0046_rollback.sql =====================
-- Rollback for 0046.
--
-- Restores the three functions to their 0045 text before dropping the columns
-- and the component type they depend on, then removes the provenance columns.
--
-- Note what this cannot undo: snapshots written while 0046 was in force keep
-- their component detail until the columns are dropped, at which point the
-- detail is gone for good. The frozen totals are untouched.

create or replace function fn_variant_cost(p_variant_id uuid)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
as $fn$
declare
  v record; v_qty numeric; v_cpyu numeric; v_pack numeric;
  v_oh_rate numeric; v_oh numeric; v_problem text;
begin
  select rv.account_id, rv.business_id, rv.recipe_id, rv.format_id,
         r.yield_unit_id
    into v
    from recipe_variants rv
    join recipes r on r.id = rv.recipe_id
   where rv.id = p_variant_id;

  if v is null then return null; end if;
  perform fn_require_cost_access(v.account_id);

  v_problem := fn_variant_problem(p_variant_id);
  if v_problem is not null then return null; end if;

  v_qty := fn_variant_resolved_qty(p_variant_id);
  if v_qty is null then return null; end if;

  -- the existing engine's figure, unchanged: it already carries ingredients,
  -- sub-recipes, purchase yield, cooking yield and labour over effective yield
  select cost_per_yield_unit into v_cpyu
    from cost_snapshots
   where recipe_id = v.recipe_id
   order by computed_at desc, seq desc
   limit 1;
  if v_cpyu is null then return null; end if;

  -- D4: format packaging is consumed once per sold unit and is NOT multiplied
  -- by the resolved quantity. No rows means no cost -- a true zero, not a NULL
  -- coerced into one.
  select coalesce(sum(spk.qty * fn_ingredient_usable_unit_cost(
                        spk.packaging_item_id, v.business_id)), 0)
    into v_pack
    from serving_format_packaging spk
   where spk.format_id = v.format_id
     and spk.is_cost_bearing;

  -- D1: overhead scales with output
  v_oh_rate := fn_overhead_rate(v.business_id, v.yield_unit_id);
  if v_oh_rate is null then
    if (select overhead_enabled from business_settings where business_id = v.business_id) then
      return null;      -- enabled but unresolvable: incomplete, never zero
    end if;
    v_oh := 0;          -- genuinely disabled: a true zero
  else
    v_oh := v_oh_rate * v_qty;
  end if;

  return v_cpyu * v_qty + v_pack + v_oh;
end;
$fn$;

create or replace function fn_compute_variant_cost_snapshot(p_variant_id uuid, p_as_of date DEFAULT CURRENT_DATE)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
as $fn$
declare
  v record; base cost_snapshots%rowtype;
  v_qty numeric; v_cost numeric; v_problem text; v_pack numeric;
  v_complete boolean; v_unpriced jsonb; v_id uuid;
begin
  select rv.account_id, rv.business_id, rv.recipe_id, rv.format_id,
         rv.costing_basis, r.yield_unit_id
    into v
    from recipe_variants rv
    join recipes r on r.id = rv.recipe_id
   where rv.id = p_variant_id;
  if v is null then
    raise exception 'Variant % does not exist', p_variant_id;
  end if;
  perform fn_require_cost_access(v.account_id);

  select * into base from cost_snapshots
   where recipe_id = v.recipe_id and variant_id is null
   order by computed_at desc, seq desc limit 1;
  if not found then
    raise exception 'Recipe % has no cost snapshot yet. Compute the recipe '
                    'cost before the variant cost.', v.recipe_id;
  end if;

  v_problem := fn_variant_problem(p_variant_id);
  v_qty     := fn_variant_resolved_qty(p_variant_id);
  v_cost    := fn_variant_cost(p_variant_id);

  select coalesce(sum(spk.qty * fn_ingredient_usable_unit_cost(
                        spk.packaging_item_id, v.business_id)), 0)
    into v_pack
    from serving_format_packaging spk
   where spk.format_id = v.format_id and spk.is_cost_bearing;

  -- Completeness propagates upward exactly as it does for sub-recipes: a
  -- variant is complete only if its own basis resolves AND the recipe beneath
  -- it is complete.
  v_complete := base.is_complete and v_problem is null and v_cost is not null;
  v_unpriced := coalesce(base.unpriced_items, '[]'::jsonb);
  if v_problem is not null then
    v_unpriced := v_unpriced || jsonb_build_object(
      'variant_id', p_variant_id, 'problem', v_problem);
  end if;

  insert into cost_snapshots (
      account_id, business_id, recipe_id, computed_at,
      costing_method, wavg_window_days,
      is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
      ingredient_cost, packaging_cost, labour_cost, overhead_cost,
      batch_cost, cost_per_yield_unit, cost_per_portion,
      floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
      created_by,
      variant_id, resolved_qty, resolved_unit_id, basis_used, format_packaging_cost)
  values (
      v.account_id, v.business_id, v.recipe_id, now(),
      base.costing_method, base.wavg_window_days,
      v_complete, base.required_inputs, base.priced_inputs, base.excluded_inputs,
      v_unpriced,
      base.ingredient_cost, base.packaging_cost, base.labour_cost, base.overhead_cost,
      base.batch_cost, base.cost_per_yield_unit,
      v_cost,                                   -- cost per SOLD UNIT, not per portion
      base.floor_batch_cost, base.floor_cost_per_yield_unit, base.floor_cost_per_portion,
      auth.uid(),
      p_variant_id, v_qty, v.yield_unit_id, v.costing_basis, v_pack)
  returning id into v_id;

  return v_id;
end;
$fn$;

create or replace function fn_compute_recipe_cost_snapshot(p_recipe_id uuid, p_as_of date DEFAULT CURRENT_DATE, p_created_by uuid DEFAULT auth.uid())
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
as $fn$
declare
  r recipes%rowtype; bs business_settings%rowtype; core recipe_cost_result;
  v_overhead numeric := 0; v_oh_total numeric; v_oh_rate numeric;
  v_sold_by_format boolean;
  v_required integer; v_priced integer; v_unpriced jsonb; v_complete boolean;
  v_floor_pp numeric; v_snapshot uuid;
begin
  select * into r from recipes where id = p_recipe_id and deleted_at is null;
  if not found then raise exception 'Recipe % not found', p_recipe_id; end if;

  perform fn_require_cost_access(r.account_id);   -- AUTHORIZATION

  select * into bs from business_settings where business_id = r.business_id;
  if not found then
    raise exception 'Business settings missing for business %', r.business_id;
  end if;

  core := fn__recipe_cost_core(p_recipe_id, p_as_of, 0);

  v_required := core.required_inputs;
  v_priced   := core.priced_inputs;
  v_unpriced := core.unpriced_items;
  v_complete := core.is_complete;

  -- MODEL 1 vs MODEL 2 (owner decision, Phase 4 escalation).
  -- A recipe sold through its own business-defined formats does not need a
  -- portion size: the FORMAT is the commercial unit, and fn_variant_cost
  -- allocates the batch economics to each format. A recipe with no active
  -- sellable format is portion-based and still requires one. This is not
  -- "portion is optional" -- exactly one basis applies, and which one is
  -- determined here rather than guessed.
  select exists (
    select 1
      from recipe_variants rv
      join serving_formats sf on sf.id = rv.format_id
     where rv.recipe_id = p_recipe_id
       and rv.is_active
       and sf.is_active
  ) into v_sold_by_format;

  if bs.overhead_enabled then
    v_required := v_required + 1;

    -- 0041: the reason now comes from fn_overhead_problem, which reads each
    -- overhead item's OWN basis and falls back to the business default. The
    -- decision is made once, in one place, rather than re-derived here.
    declare v_oh_problem text;
    begin
      v_oh_problem := fn_overhead_problem(r.business_id, r.yield_unit_id);
      if v_oh_problem is not null then
        v_complete := false;
        v_unpriced := v_unpriced || jsonb_build_object(
          'recipe_id', p_recipe_id, 'business_id', r.business_id,
          'problem', v_oh_problem);
        v_overhead := null;
      else
        v_oh_rate := fn_overhead_rate(r.business_id, r.yield_unit_id);
        if r.portion_qty is null then
          -- No portion size. For a FORMAT-BASED recipe that is correct:
          -- overhead is allocated per format by fn_variant_cost as
          -- overhead_rate x resolved_qty, so there is no per-portion figure
          -- to compute and none is invented.
          v_overhead := null;
          if v_sold_by_format then
            v_priced := v_priced + 1;
          end if;
        else
          v_overhead := v_oh_rate * r.portion_qty;
          v_priced   := v_priced + 1;
        end if;
      end if;
    end;
  end if;

  if r.kind = 'dish' and not v_sold_by_format then
    -- MODEL 1, portion-based: the portion is the commercial unit, so its size
    -- is a required input.
    v_required := v_required + 1;
    if r.portion_qty is null then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'problem', 'missing_portion_size');
    else
      v_priced := v_priced + 1;
    end if;
  end if;
  -- MODEL 2, format-based: no portion input is required and none is invented.
  -- Whether each format can actually be costed is decided per format by
  -- fn_variant_problem, which blocks on incompatible dimensions, missing
  -- conversions and unpriced packaging. A recipe can therefore be complete
  -- while one of its formats is not, which is the truth of the situation.

  if core.priced_inputs = 0 then
    v_floor_pp := null;
  elsif core.cost_per_yield_unit is not null and r.portion_qty is not null then
    v_floor_pp := core.cost_per_yield_unit * r.portion_qty + coalesce(v_overhead, 0);
  else
    v_floor_pp := null;
  end if;

  if jsonb_array_length(v_unpriced) > 0 then
    v_complete := false;
  end if;

  insert into cost_snapshots (
    account_id, business_id, recipe_id, computed_at,
    costing_method, wavg_window_days,
    is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
    ingredient_cost, packaging_cost, labour_cost, overhead_cost,
    batch_cost, cost_per_yield_unit, cost_per_portion,
    floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
    created_by)
  values (
    r.account_id, r.business_id, p_recipe_id, now(),
    bs.costing_method, bs.wavg_window_days,
    v_complete, v_required, v_priced, core.excluded_inputs, v_unpriced,
    core.ingredient_cost, core.packaging_cost, core.labour_cost, v_overhead,
    case when v_complete then core.batch_cost end,
    case when v_complete then core.cost_per_yield_unit end,
    case when v_complete then v_floor_pp end,
    case when core.priced_inputs > 0 then core.batch_cost end,
    case when core.priced_inputs > 0 then core.cost_per_yield_unit end,
    v_floor_pp,
    p_created_by)
  returning id into v_snapshot;

  return v_snapshot;
end;
$fn$;

alter table cost_snapshots
  drop column if exists portion_qty_at_snapshot,
  drop column if exists variant_overhead_cost;

drop function if exists fn_variant_cost_components(uuid);
drop type if exists variant_cost_components;

do $$
begin
  if exists (select 1 from information_schema.columns
              where table_name = 'cost_snapshots'
                and column_name in ('portion_qty_at_snapshot','variant_overhead_cost')) then
    raise exception '0046 rollback FAILED: a provenance column survived.';
  end if;
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
              where n.nspname = 'public' and p.proname = 'fn_variant_cost_components')
   or exists (select 1 from pg_type where typname = 'variant_cost_components') then
    raise exception '0046 rollback FAILED: the component function or type survived.';
  end if;
  raise notice '0046 rollback OK: provenance columns removed, functions restored.';
end
$$;


-- ===================== 0045_rollback.sql =====================
-- Rollback for 0045.
--
-- Restores the insert-time freeze, the guard that refused every change to a
-- frozen cost, the 'confirmed' status default, and fn_finalise_order's own
-- body. fn_frozen_sale_cost and the frozen_sale_cost type are dropped last,
-- after fn_freeze_sale_cost has stopped depending on them.
--
-- Note: this restores the *mechanism*. It cannot un-freeze lines that were
-- frozen at confirmation, and must not try to -- those are confirmed sales.
--
-- It also leaves the finalised_at values 0045 recorded on legacy orders. That
-- is deliberate. Blanking them would mean guessing which rows were reconciled
-- and which were genuinely finalised, and guessing wrong would unlock a real
-- sale. Leaving them is harmless: the pre-0045 reporting keys on status, not
-- finalised_at, so no figure changes -- those orders simply read as finalised,
-- which under the old rules is what a confirmed order was always meant to be.

alter table orders alter column status set default 'confirmed';

drop trigger if exists trg_orders_lifecycle on orders;
drop function if exists fn_guard_order_lifecycle();
drop function if exists fn_confirm_order(uuid);

create or replace function fn_finalise_order(p_order_id uuid)
returns jsonb
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare v_o orders%rowtype; v_lines integer;
begin
  select * into v_o from orders where id = p_order_id for update;
  if not found then raise exception 'Order % not found', p_order_id; end if;

  perform fn_require_account_role(v_o.account_id,
    array['owner','manager','sales']::member_role[], 'finalising orders');

  if v_o.voided_at is not null then
    raise exception 'Order % is voided and cannot be finalised', p_order_id
      using errcode='check_violation';
  end if;
  if v_o.finalised_at is not null then
    raise exception 'Order % is already finalised', p_order_id
      using errcode='check_violation';
  end if;

  select count(*) into v_lines from order_lines where order_id = p_order_id;
  if v_lines = 0 then
    raise exception 'Order % has no lines', p_order_id using errcode='check_violation';
  end if;

  update orders set finalised_at = now(), finalised_by = auth.uid() where id = p_order_id;

  return jsonb_build_object('finalised', true, 'order_id', p_order_id, 'lines', v_lines);
end;
$fn$;

create or replace function fn_guard_frozen_cost()
returns trigger
language plpgsql
as $fn$
begin
  if new.cost_snapshot_id is distinct from old.cost_snapshot_id
     or new.unit_cost_at_sale is distinct from old.unit_cost_at_sale then
    raise exception
      'The cost frozen at sale time cannot be changed. Reverse the sale instead.'
      using errcode='check_violation';
  end if;
  return new;
end;
$fn$;

drop trigger if exists trg_order_lines_frozen on order_lines;
create trigger trg_order_lines_frozen
  before update on order_lines
  for each row execute function fn_guard_frozen_cost();

create or replace function fn_freeze_sale_cost()
returns trigger
language plpgsql
security definer
set search_path to 'public'
as $fn$
declare
  s cost_snapshots%rowtype;
begin
  if new.recipe_id is null then
    new.cost_snapshot_id  := null;
    new.unit_cost_at_sale := null;
    return new;
  end if;

  if new.variant_id is not null then
    -- what was actually sold is the variant, so that is what is frozen
    select * into s
    from cost_snapshots
    where variant_id = new.variant_id
    order by computed_at desc, seq desc
    limit 1;
  else
    -- unchanged legacy path: recipe-level snapshots only
    select * into s
    from cost_snapshots
    where recipe_id = new.recipe_id and variant_id is null
    order by computed_at desc, seq desc
    limit 1;
  end if;

  -- The gate applies here too. An incomplete cost is not a cost.
  if not found or not s.is_complete or s.cost_per_portion is null then
    new.cost_snapshot_id  := null;
    new.unit_cost_at_sale := null;
  else
    new.cost_snapshot_id  := s.id;
    new.unit_cost_at_sale := s.cost_per_portion;
  end if;

  return new;
end;
$fn$;

drop trigger if exists trg_order_lines_freeze on order_lines;
create trigger trg_order_lines_freeze
  before insert on order_lines
  for each row execute function fn_freeze_sale_cost();

drop function if exists fn_frozen_sale_cost(uuid, uuid, uuid);
drop type if exists frozen_sale_cost;

do $$
begin
  if exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace
              where n.nspname = 'public'
                and p.proname in ('fn_confirm_order','fn_frozen_sale_cost',
                                  'fn_guard_order_lifecycle')) then
    raise exception '0045 rollback FAILED: a 0045 function survived.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'order_lines' and t.tgname = 'trg_order_lines_freeze') then
    raise exception '0045 rollback FAILED: the insert-time freeze was not restored.';
  end if;
  if (select column_default from information_schema.columns
       where table_name = 'orders' and column_name = 'status')
     is distinct from '''confirmed''::order_status' then
    raise exception '0045 rollback FAILED: the status default was not restored.';
  end if;
  raise notice '0045 rollback OK: insert-time freeze restored.';
end
$$;


-- ===================== 0044_rollback.sql =====================
-- Rollback for 0044.
--
-- The two revenue guards are restored to their 0043 text, not merely dropped:
-- dropping them would leave a finalised sale editable, which is worse than the
-- state we are rolling back from.

drop trigger if exists trg_orders_discount on orders;
drop function if exists fn_guard_order_discount();
drop function if exists fn_allocate_order_discount(uuid);

alter table order_lines drop constraint if exists order_lines_discount_amount_check;
alter table order_lines drop column if exists discount_amount;

alter table orders drop constraint if exists orders_order_discount_check;
alter table orders drop column if exists order_discount;

create or replace function fn_guard_order_line_revenue()
returns trigger
language plpgsql
as $fn$
declare v_final timestamptz; v_void timestamptz; v_order uuid;
begin
  v_order := coalesce(new.order_id, old.order_id);
  select finalised_at, voided_at into v_final, v_void from orders where id = v_order;

  if v_final is null then
    return coalesce(new, old);            -- still a draft: freely editable
  end if;

  if tg_op = 'INSERT' then
    raise exception 'Order % is finalised. No further lines may be added.', v_order
      using errcode='check_violation';
  elsif tg_op = 'DELETE' then
    raise exception 'Order % is finalised. Lines cannot be deleted. Void the order instead.', v_order
      using errcode='check_violation';
  else
    if (old.qty, old.unit_price, old.recipe_id)
       is distinct from (new.qty, new.unit_price, new.recipe_id) then
      raise exception 'Revenue on a finalised sale is immutable. Void and reissue instead.'
        using errcode='check_violation';
    end if;
  end if;

  return coalesce(new, old);
end;
$fn$;

create or replace function fn_guard_finalised_order()
returns trigger
language plpgsql
as $fn$
begin
  if tg_op = 'DELETE' then
    if old.finalised_at is not null then
      raise exception 'Order % is finalised and cannot be deleted. Void it instead.', old.id
        using errcode='check_violation';
    end if;
    return old;
  end if;

  if old.voided_at is not null then
    raise exception 'Order % is voided. Its record is closed.', old.id
      using errcode='check_violation';
  end if;

  if old.finalised_at is not null then
    -- Settlement may still move after the sale: collecting payment later is not
    -- a revenue rewrite. Everything that determines revenue is frozen.
    if (old.account_id, old.business_id, old.location_id, old.customer_id,
        old.channel_id, old.order_no, old.order_date, old.status,
        old.finalised_at, old.replaces)
       is distinct from
       (new.account_id, new.business_id, new.location_id, new.customer_id,
        new.channel_id, new.order_no, new.order_date, new.status,
        new.finalised_at, new.replaces)
    then
      raise exception 'Order % is finalised. Only payment state may change, or void it.', old.id
        using errcode='check_violation';
    end if;
  end if;

  return new;
end;
$fn$;

do $$
begin
  if exists (select 1 from information_schema.columns
              where table_name = 'order_lines' and column_name = 'discount_amount')
   or exists (select 1 from information_schema.columns
              where table_name = 'orders' and column_name = 'order_discount') then
    raise exception '0044 rollback FAILED: a discount column survived.';
  end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'order_lines' and t.tgname = 'trg_order_lines_revenue')
   or not exists (select 1 from pg_trigger t join pg_class c on c.oid = t.tgrelid
                  where c.relname = 'orders' and t.tgname = 'trg_orders_finalised') then
    raise exception '0044 rollback FAILED: a revenue guard is no longer attached.';
  end if;
  raise notice '0044 rollback OK: discounts removed, revenue guards restored.';
end
$$;


-- ===================== 0043_rollback.sql =====================
-- Rollback for 0043.
drop trigger if exists trg_order_lines_scope on order_lines;
drop function if exists fn_order_line_scope();
alter table order_lines drop constraint if exists fk_order_lines_business_id_account;
alter table order_lines drop column if exists business_id;
alter table customers drop column if exists company;
alter table customers drop column if exists notes;

-- ===================== 0042_rollback.sql =====================
-- Rollback for 0042.
--
-- DROP then CREATE for v_onboarding_status: PostgreSQL cannot remove columns
-- from a view in place, so a replace would silently leave the six new ones
-- behind. security_invoker is restated -- a dropped view loses it -- and the
-- grant is reissued because dropping discards it.

drop view if exists v_ingredient_price_status;

-- v_onboarding_status reads v_product_attention, so it must go first.
drop view if exists v_onboarding_status;
drop view if exists v_product_attention;

create view v_onboarding_status with (security_invoker = on) as
 SELECT account_id,
    id AS business_id,
    name,
    ( SELECT count(*) AS count
           FROM ingredients i
          WHERE i.account_id = b.account_id AND i.deleted_at IS NULL) AS ingredients,
    ( SELECT count(*) AS count
           FROM ingredient_prices ip
          WHERE ip.account_id = b.account_id AND ip.reversed_at IS NULL) AS prices_entered,
    ( SELECT count(*) AS count
           FROM recipes r
          WHERE r.business_id = b.id AND r.deleted_at IS NULL) AS recipes,
    ( SELECT count(*) AS count
           FROM cost_snapshots s
          WHERE s.business_id = b.id AND s.is_complete) AS complete_costings,
    ( SELECT count(*) AS count
           FROM v_missing_unit_conversions m
          WHERE m.account_id = b.account_id AND m.reason <> 'suggested'::text) AS blocking_conversions,
    ( SELECT count(*) AS count
           FROM recipe_prices rp
             JOIN recipes r2 ON r2.id = rp.recipe_id
          WHERE r2.business_id = b.id) AS selling_prices_set
   FROM businesses b
  WHERE deleted_at IS NULL;

-- Restored EXACTLY as the baseline had them: dropping the view discards its
-- grants, and the pre-0042 view carried the four privileges Supabase default
-- privileges give `authenticated`. The write privileges are inert -- the view
-- is not auto-updatable -- but a rollback must not change the security
-- posture in either direction.
grant select, insert, update, delete on v_onboarding_status to authenticated;


-- ===================== 0041_rollback.sql =====================
-- Rollback for 0041. Restores the single business-wide overhead basis.
-- Multi-dimension businesses become uncostable in one dimension again.

CREATE OR REPLACE FUNCTION public.fn_overhead_rate(p_business_id uuid, p_target_unit_id uuid)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_total numeric; v_qty numeric; v_unit uuid; v_basis numeric;
begin
  if p_business_id is null or p_target_unit_id is null then return null; end if;

  select overhead_basis_qty, overhead_basis_unit_id
    into v_qty, v_unit
    from business_settings
   where business_id = p_business_id;

  -- no declared basis is not a rate of zero; it is the absence of a rate
  if v_qty is null or v_unit is null then return null; end if;

  select coalesce(sum(monthly_cost), 0) into v_total
    from overhead_items
   where business_id = p_business_id and is_active;

  -- returns NULL across measurement kinds and for container units with no
  -- universal factor. That NULL is the incompatibility signal; it is never
  -- coerced to a number.
  v_basis := fn_convert_between_units(v_qty, v_unit, p_target_unit_id);
  if v_basis is null or v_basis <= 0 then return null; end if;

  return v_total / v_basis;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_compute_recipe_cost_snapshot(p_recipe_id uuid, p_as_of date DEFAULT CURRENT_DATE, p_created_by uuid DEFAULT auth.uid())
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  r recipes%rowtype; bs business_settings%rowtype; core recipe_cost_result;
  v_overhead numeric := 0; v_oh_total numeric; v_oh_rate numeric;
  v_sold_by_format boolean;
  v_required integer; v_priced integer; v_unpriced jsonb; v_complete boolean;
  v_floor_pp numeric; v_snapshot uuid;
begin
  select * into r from recipes where id = p_recipe_id and deleted_at is null;
  if not found then raise exception 'Recipe % not found', p_recipe_id; end if;

  perform fn_require_cost_access(r.account_id);   -- AUTHORIZATION

  select * into bs from business_settings where business_id = r.business_id;
  if not found then
    raise exception 'Business settings missing for business %', r.business_id;
  end if;

  core := fn__recipe_cost_core(p_recipe_id, p_as_of, 0);

  v_required := core.required_inputs;
  v_priced   := core.priced_inputs;
  v_unpriced := core.unpriced_items;
  v_complete := core.is_complete;

  -- MODEL 1 vs MODEL 2 (owner decision, Phase 4 escalation).
  -- A recipe sold through its own business-defined formats does not need a
  -- portion size: the FORMAT is the commercial unit, and fn_variant_cost
  -- allocates the batch economics to each format. A recipe with no active
  -- sellable format is portion-based and still requires one. This is not
  -- "portion is optional" -- exactly one basis applies, and which one is
  -- determined here rather than guessed.
  select exists (
    select 1
      from recipe_variants rv
      join serving_formats sf on sf.id = rv.format_id
     where rv.recipe_id = p_recipe_id
       and rv.is_active
       and sf.is_active
  ) into v_sold_by_format;

  if bs.overhead_enabled then
    v_required := v_required + 1;
    select sum(monthly_cost) into v_oh_total
    from overhead_items
    where business_id = r.business_id and is_active and monthly_cost is not null;

    -- D1: the overhead ITEMS are the config question. Whether a BASIS exists
    -- is a separate question, with its own problem code below. The deprecated
    -- per-portion denominator is retained on the table but no longer read.
    if v_oh_total is null
       or exists (select 1 from overhead_items
                   where business_id = r.business_id and is_active and monthly_cost is null)
    then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'business_id', r.business_id,
        'problem', 'missing_overhead_config');
      v_overhead := null;
    elsif bs.overhead_basis_qty is null or bs.overhead_basis_unit_id is null then
      -- overhead is enabled but no basis has been declared. Report it by name.
      -- DO NOT fall back to the old denominator: silently switching methodology
      -- is exactly what this migration exists to prevent.
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'business_id', r.business_id,
        'problem', 'missing_overhead_basis');
      v_overhead := null;
    else
      v_oh_rate := fn_overhead_rate(r.business_id, r.yield_unit_id);
      if v_oh_rate is null then
        -- the basis exists but cannot be expressed in this recipe's yield unit:
        -- a litre basis cannot allocate to a recipe sold by the piece. No
        -- cross-kind conversion is invented (D1 option a).
        v_complete := false;
        v_unpriced := v_unpriced || jsonb_build_object(
          'recipe_id', p_recipe_id, 'business_id', r.business_id,
          'problem', 'overhead_basis_incompatible');
        v_overhead := null;
      elsif r.portion_qty is null then
        -- No portion size. For a PORTION-BASED recipe that is incomplete, and
        -- missing_portion_size below records it. For a FORMAT-BASED recipe it
        -- is correct: overhead is allocated per sellable format by
        -- fn_variant_cost as overhead_rate x resolved_qty, so there is no
        -- per-portion figure to compute and none is invented. The rate itself
        -- is resolvable either way -- only this projection of it is absent.
        v_overhead := null;
        if v_sold_by_format then
          v_priced := v_priced + 1;
        end if;
      else
        v_overhead := v_oh_rate * r.portion_qty;
        v_priced   := v_priced + 1;
      end if;
    end if;
  end if;

  if r.kind = 'dish' and not v_sold_by_format then
    -- MODEL 1, portion-based: the portion is the commercial unit, so its size
    -- is a required input.
    v_required := v_required + 1;
    if r.portion_qty is null then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'problem', 'missing_portion_size');
    else
      v_priced := v_priced + 1;
    end if;
  end if;
  -- MODEL 2, format-based: no portion input is required and none is invented.
  -- Whether each format can actually be costed is decided per format by
  -- fn_variant_problem, which blocks on incompatible dimensions, missing
  -- conversions and unpriced packaging. A recipe can therefore be complete
  -- while one of its formats is not, which is the truth of the situation.

  if core.priced_inputs = 0 then
    v_floor_pp := null;
  elsif core.cost_per_yield_unit is not null and r.portion_qty is not null then
    v_floor_pp := core.cost_per_yield_unit * r.portion_qty + coalesce(v_overhead, 0);
  else
    v_floor_pp := null;
  end if;

  if jsonb_array_length(v_unpriced) > 0 then
    v_complete := false;
  end if;

  insert into cost_snapshots (
    account_id, business_id, recipe_id, computed_at,
    costing_method, wavg_window_days,
    is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
    ingredient_cost, packaging_cost, labour_cost, overhead_cost,
    batch_cost, cost_per_yield_unit, cost_per_portion,
    floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
    created_by)
  values (
    r.account_id, r.business_id, p_recipe_id, now(),
    bs.costing_method, bs.wavg_window_days,
    v_complete, v_required, v_priced, core.excluded_inputs, v_unpriced,
    core.ingredient_cost, core.packaging_cost, core.labour_cost, v_overhead,
    case when v_complete then core.batch_cost end,
    case when v_complete then core.cost_per_yield_unit end,
    case when v_complete then v_floor_pp end,
    case when core.priced_inputs > 0 then core.batch_cost end,
    case when core.priced_inputs > 0 then core.cost_per_yield_unit end,
    v_floor_pp,
    p_created_by)
  returning id into v_snapshot;

  return v_snapshot;
end;
$function$;

drop function if exists fn_overhead_problem(uuid, uuid);
drop function if exists fn_overhead_breakdown(uuid, uuid);

alter table overhead_items drop constraint if exists chk_overhead_item_basis_positive;
alter table overhead_items drop constraint if exists chk_overhead_item_basis_pair;
alter table overhead_items drop column if exists basis_unit_id;
alter table overhead_items drop column if exists basis_qty;


-- ===================== 0040_rollback.sql =====================
-- Rollback for 0040. Restores fn_variant_problem verbatim. Count- and
-- container-yield businesses become uncostable again with it.

CREATE OR REPLACE FUNCTION public.fn_variant_problem(p_variant_id uuid)
 RETURNS text
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v record; v_from_kind unit_kind; v_to_kind unit_kind;
  v_from_factor numeric; v_unpriced int;
begin
  select rv.account_id, rv.business_id, rv.costing_basis, rv.sellable_qty,
         rv.sellable_unit_id, rv.format_id,
         f.capacity_qty, f.capacity_unit_id,
         r.yield_unit_id, r.id as recipe_id
    into v
    from recipe_variants rv
    join serving_formats f on f.id = rv.format_id
    join recipes r on r.id = rv.recipe_id
   where rv.id = p_variant_id;

  if v is null then return 'variant_not_found'; end if;
  perform fn_require_member(v.account_id);

  select kind into v_to_kind from units where id = v.yield_unit_id;

  if v.costing_basis = 'capacity' then
    if v.capacity_qty is null or v.capacity_unit_id is null then
      return 'format_missing_capacity';
    end if;
    select kind, factor_to_base into v_from_kind, v_from_factor
      from units where id = v.capacity_unit_id;
    if v_from_kind is distinct from v_to_kind then
      return 'capacity_unit_incompatible';
    end if;
    -- a container unit has no universal factor, and a recipe has no ingredient
    -- against which to look one up. Correct behaviour: it cannot resolve.
    if v_from_factor is null then
      return 'capacity_unit_unconvertible';
    end if;
  else
    if v.sellable_qty is null or v.sellable_unit_id is null then
      return 'missing_sellable_quantity';
    end if;
    select kind, factor_to_base into v_from_kind, v_from_factor
      from units where id = v.sellable_unit_id;
    if v_from_kind is distinct from v_to_kind or v_from_factor is null then
      return 'sellable_unit_incompatible';
    end if;
  end if;

  -- a format packaging item with no price blocks the variant, exactly as an
  -- unpriced ingredient blocks the recipe
  select count(*) into v_unpriced
    from serving_format_packaging spk
   where spk.format_id = v.format_id
     and spk.is_cost_bearing
     and fn_ingredient_usable_unit_cost(spk.packaging_item_id, v.business_id) is null;
  if v_unpriced > 0 then
    return 'missing_packaging_price';
  end if;

  return null;
end;
$function$;

-- ===================== 0039_rollback.sql =====================
-- Rollback for 0039. Restores the pre-0039 snapshot function verbatim, so
-- portion_qty is required for every dish again, and drops v_recipe_basis.
-- Format-based businesses become uncostable again with it.

CREATE OR REPLACE FUNCTION public.fn_compute_recipe_cost_snapshot(p_recipe_id uuid, p_as_of date DEFAULT CURRENT_DATE, p_created_by uuid DEFAULT auth.uid())
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  r recipes%rowtype; bs business_settings%rowtype; core recipe_cost_result;
  v_overhead numeric := 0; v_oh_total numeric; v_oh_rate numeric;
  v_required integer; v_priced integer; v_unpriced jsonb; v_complete boolean;
  v_floor_pp numeric; v_snapshot uuid;
begin
  select * into r from recipes where id = p_recipe_id and deleted_at is null;
  if not found then raise exception 'Recipe % not found', p_recipe_id; end if;

  perform fn_require_cost_access(r.account_id);   -- AUTHORIZATION

  select * into bs from business_settings where business_id = r.business_id;
  if not found then
    raise exception 'Business settings missing for business %', r.business_id;
  end if;

  core := fn__recipe_cost_core(p_recipe_id, p_as_of, 0);

  v_required := core.required_inputs;
  v_priced   := core.priced_inputs;
  v_unpriced := core.unpriced_items;
  v_complete := core.is_complete;

  if bs.overhead_enabled then
    v_required := v_required + 1;
    select sum(monthly_cost) into v_oh_total
    from overhead_items
    where business_id = r.business_id and is_active and monthly_cost is not null;

    -- D1: the overhead ITEMS are the config question. Whether a BASIS exists
    -- is a separate question, with its own problem code below. The deprecated
    -- per-portion denominator is retained on the table but no longer read.
    if v_oh_total is null
       or exists (select 1 from overhead_items
                   where business_id = r.business_id and is_active and monthly_cost is null)
    then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'business_id', r.business_id,
        'problem', 'missing_overhead_config');
      v_overhead := null;
    elsif bs.overhead_basis_qty is null or bs.overhead_basis_unit_id is null then
      -- overhead is enabled but no basis has been declared. Report it by name.
      -- DO NOT fall back to the old denominator: silently switching methodology
      -- is exactly what this migration exists to prevent.
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'business_id', r.business_id,
        'problem', 'missing_overhead_basis');
      v_overhead := null;
    else
      v_oh_rate := fn_overhead_rate(r.business_id, r.yield_unit_id);
      if v_oh_rate is null then
        -- the basis exists but cannot be expressed in this recipe's yield unit:
        -- a litre basis cannot allocate to a recipe sold by the piece. No
        -- cross-kind conversion is invented (D1 option a).
        v_complete := false;
        v_unpriced := v_unpriced || jsonb_build_object(
          'recipe_id', p_recipe_id, 'business_id', r.business_id,
          'problem', 'overhead_basis_incompatible');
        v_overhead := null;
      elsif r.portion_qty is null then
        -- no portion size, so no per-portion overhead. missing_portion_size
        -- below already accounts for the incompleteness.
        v_overhead := null;
      else
        v_overhead := v_oh_rate * r.portion_qty;
        v_priced   := v_priced + 1;
      end if;
    end if;
  end if;

  if r.kind = 'dish' then
    v_required := v_required + 1;
    if r.portion_qty is null then
      v_complete := false;
      v_unpriced := v_unpriced || jsonb_build_object(
        'recipe_id', p_recipe_id, 'problem', 'missing_portion_size');
    else
      v_priced := v_priced + 1;
    end if;
  end if;

  if core.priced_inputs = 0 then
    v_floor_pp := null;
  elsif core.cost_per_yield_unit is not null and r.portion_qty is not null then
    v_floor_pp := core.cost_per_yield_unit * r.portion_qty + coalesce(v_overhead, 0);
  else
    v_floor_pp := null;
  end if;

  if jsonb_array_length(v_unpriced) > 0 then
    v_complete := false;
  end if;

  insert into cost_snapshots (
    account_id, business_id, recipe_id, computed_at,
    costing_method, wavg_window_days,
    is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
    ingredient_cost, packaging_cost, labour_cost, overhead_cost,
    batch_cost, cost_per_yield_unit, cost_per_portion,
    floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
    created_by)
  values (
    r.account_id, r.business_id, p_recipe_id, now(),
    bs.costing_method, bs.wavg_window_days,
    v_complete, v_required, v_priced, core.excluded_inputs, v_unpriced,
    core.ingredient_cost, core.packaging_cost, core.labour_cost, v_overhead,
    case when v_complete then core.batch_cost end,
    case when v_complete then core.cost_per_yield_unit end,
    case when v_complete then v_floor_pp end,
    case when core.priced_inputs > 0 then core.batch_cost end,
    case when core.priced_inputs > 0 then core.cost_per_yield_unit end,
    v_floor_pp,
    p_created_by)
  returning id into v_snapshot;

  return v_snapshot;
end;
$function$;

drop view if exists v_recipe_basis;


-- ===================== 0038_rollback.sql =====================
-- Rollback for 0038. Restores the three functions verbatim, without the
-- tie-breaker. The ordering ambiguity returns with them.

CREATE OR REPLACE FUNCTION public.fn_variant_cost(p_variant_id uuid)
 RETURNS numeric
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v record; v_qty numeric; v_cpyu numeric; v_pack numeric;
  v_oh_rate numeric; v_oh numeric; v_problem text;
begin
  select rv.account_id, rv.business_id, rv.recipe_id, rv.format_id,
         r.yield_unit_id
    into v
    from recipe_variants rv
    join recipes r on r.id = rv.recipe_id
   where rv.id = p_variant_id;

  if v is null then return null; end if;
  perform fn_require_cost_access(v.account_id);

  v_problem := fn_variant_problem(p_variant_id);
  if v_problem is not null then return null; end if;

  v_qty := fn_variant_resolved_qty(p_variant_id);
  if v_qty is null then return null; end if;

  -- the existing engine's figure, unchanged: it already carries ingredients,
  -- sub-recipes, purchase yield, cooking yield and labour over effective yield
  select cost_per_yield_unit into v_cpyu
    from cost_snapshots
   where recipe_id = v.recipe_id
   order by computed_at desc
   limit 1;
  if v_cpyu is null then return null; end if;

  -- D4: format packaging is consumed once per sold unit and is NOT multiplied
  -- by the resolved quantity. No rows means no cost -- a true zero, not a NULL
  -- coerced into one.
  select coalesce(sum(spk.qty * fn_ingredient_usable_unit_cost(
                        spk.packaging_item_id, v.business_id)), 0)
    into v_pack
    from serving_format_packaging spk
   where spk.format_id = v.format_id
     and spk.is_cost_bearing;

  -- D1: overhead scales with output
  v_oh_rate := fn_overhead_rate(v.business_id, v.yield_unit_id);
  if v_oh_rate is null then
    if (select overhead_enabled from business_settings where business_id = v.business_id) then
      return null;      -- enabled but unresolvable: incomplete, never zero
    end if;
    v_oh := 0;          -- genuinely disabled: a true zero
  else
    v_oh := v_oh_rate * v_qty;
  end if;

  return v_cpyu * v_qty + v_pack + v_oh;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_compute_variant_cost_snapshot(p_variant_id uuid, p_as_of date DEFAULT CURRENT_DATE)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v record; base cost_snapshots%rowtype;
  v_qty numeric; v_cost numeric; v_problem text; v_pack numeric;
  v_complete boolean; v_unpriced jsonb; v_id uuid;
begin
  select rv.account_id, rv.business_id, rv.recipe_id, rv.format_id,
         rv.costing_basis, r.yield_unit_id
    into v
    from recipe_variants rv
    join recipes r on r.id = rv.recipe_id
   where rv.id = p_variant_id;
  if v is null then
    raise exception 'Variant % does not exist', p_variant_id;
  end if;
  perform fn_require_cost_access(v.account_id);

  select * into base from cost_snapshots
   where recipe_id = v.recipe_id and variant_id is null
   order by computed_at desc limit 1;
  if not found then
    raise exception 'Recipe % has no cost snapshot yet. Compute the recipe '
                    'cost before the variant cost.', v.recipe_id;
  end if;

  v_problem := fn_variant_problem(p_variant_id);
  v_qty     := fn_variant_resolved_qty(p_variant_id);
  v_cost    := fn_variant_cost(p_variant_id);

  select coalesce(sum(spk.qty * fn_ingredient_usable_unit_cost(
                        spk.packaging_item_id, v.business_id)), 0)
    into v_pack
    from serving_format_packaging spk
   where spk.format_id = v.format_id and spk.is_cost_bearing;

  -- Completeness propagates upward exactly as it does for sub-recipes: a
  -- variant is complete only if its own basis resolves AND the recipe beneath
  -- it is complete.
  v_complete := base.is_complete and v_problem is null and v_cost is not null;
  v_unpriced := coalesce(base.unpriced_items, '[]'::jsonb);
  if v_problem is not null then
    v_unpriced := v_unpriced || jsonb_build_object(
      'variant_id', p_variant_id, 'problem', v_problem);
  end if;

  insert into cost_snapshots (
      account_id, business_id, recipe_id, computed_at,
      costing_method, wavg_window_days,
      is_complete, required_inputs, priced_inputs, excluded_inputs, unpriced_items,
      ingredient_cost, packaging_cost, labour_cost, overhead_cost,
      batch_cost, cost_per_yield_unit, cost_per_portion,
      floor_batch_cost, floor_cost_per_yield_unit, floor_cost_per_portion,
      created_by,
      variant_id, resolved_qty, resolved_unit_id, basis_used, format_packaging_cost)
  values (
      v.account_id, v.business_id, v.recipe_id, now(),
      base.costing_method, base.wavg_window_days,
      v_complete, base.required_inputs, base.priced_inputs, base.excluded_inputs,
      v_unpriced,
      base.ingredient_cost, base.packaging_cost, base.labour_cost, base.overhead_cost,
      base.batch_cost, base.cost_per_yield_unit,
      v_cost,                                   -- cost per SOLD UNIT, not per portion
      base.floor_batch_cost, base.floor_cost_per_yield_unit, base.floor_cost_per_portion,
      auth.uid(),
      p_variant_id, v_qty, v.yield_unit_id, v.costing_basis, v_pack)
  returning id into v_id;

  return v_id;
end;
$function$;

CREATE OR REPLACE FUNCTION public.fn_freeze_sale_cost()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  s cost_snapshots%rowtype;
begin
  if new.recipe_id is null then
    new.cost_snapshot_id  := null;
    new.unit_cost_at_sale := null;
    return new;
  end if;

  if new.variant_id is not null then
    -- what was actually sold is the variant, so that is what is frozen
    select * into s
    from cost_snapshots
    where variant_id = new.variant_id
    order by computed_at desc
    limit 1;
  else
    -- unchanged legacy path: recipe-level snapshots only
    select * into s
    from cost_snapshots
    where recipe_id = new.recipe_id and variant_id is null
    order by computed_at desc
    limit 1;
  end if;

  -- The gate applies here too. An incomplete cost is not a cost.
  if not found or not s.is_complete or s.cost_per_portion is null then
    new.cost_snapshot_id  := null;
    new.unit_cost_at_sale := null;
  else
    new.cost_snapshot_id  := s.id;
    new.unit_cost_at_sale := s.cost_per_portion;
  end if;

  return new;
end;
$function$;


-- ===================== 0037_rollback.sql =====================
-- Rollback for 0037. Restores the pre-0037 view definitions verbatim, WITH
-- security_invoker restated on each -- a replaced view silently loses it --
-- and drops the tie-breaker column. The ordering ambiguity returns with it.

create or replace view v_recipe_cost_current with (security_invoker = on) as
 SELECT DISTINCT ON (recipe_id) id,
    account_id,
    business_id,
    recipe_id,
    computed_at,
    costing_method,
    wavg_window_days,
    is_complete,
    required_inputs,
    priced_inputs,
    excluded_inputs,
    unpriced_items,
    ingredient_cost,
    packaging_cost,
    labour_cost,
    overhead_cost,
    batch_cost,
    cost_per_yield_unit,
    cost_per_portion,
    created_by
   FROM cost_snapshots
  ORDER BY recipe_id, computed_at DESC;

create or replace view v_price_check with (security_invoker = on) as
 WITH recipe_latest AS (
         SELECT DISTINCT ON (cost_snapshots.recipe_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion,
            cost_snapshots.variant_id,
            cost_snapshots.resolved_qty,
            cost_snapshots.resolved_unit_id,
            cost_snapshots.basis_used,
            cost_snapshots.format_packaging_cost
           FROM cost_snapshots
          WHERE cost_snapshots.variant_id IS NULL
          ORDER BY cost_snapshots.recipe_id, cost_snapshots.computed_at DESC
        ), variant_latest AS (
         SELECT DISTINCT ON (cost_snapshots.variant_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion,
            cost_snapshots.variant_id,
            cost_snapshots.resolved_qty,
            cost_snapshots.resolved_unit_id,
            cost_snapshots.basis_used,
            cost_snapshots.format_packaging_cost
           FROM cost_snapshots
          WHERE cost_snapshots.variant_id IS NOT NULL
          ORDER BY cost_snapshots.variant_id, cost_snapshots.computed_at DESC
        ), rows AS (
         SELECT r.id AS recipe_id,
            r.business_id,
            r.account_id,
            r.name,
            rv.id AS variant_id,
            f.name AS format_name,
            vl.resolved_qty,
            COALESCE(vl.is_complete, false) AS is_complete,
            vl.required_inputs,
            vl.priced_inputs,
            vl.excluded_inputs,
            COALESCE(vl.unpriced_items, '[]'::jsonb) AS unpriced_items,
            vl.floor_cost_per_portion,
            vl.cost_per_portion
           FROM recipes r
             JOIN recipe_variants rv ON rv.recipe_id = r.id AND rv.is_active
             JOIN serving_formats f ON f.id = rv.format_id
             LEFT JOIN variant_latest vl ON vl.variant_id = rv.id
          WHERE r.kind = 'dish'::recipe_kind AND r.deleted_at IS NULL
        UNION ALL
         SELECT r.id,
            r.business_id,
            r.account_id,
            r.name,
            NULL::uuid AS uuid,
            NULL::text AS text,
            NULL::numeric AS "numeric",
            COALESCE(rl.is_complete, false) AS "coalesce",
            rl.required_inputs,
            rl.priced_inputs,
            rl.excluded_inputs,
            COALESCE(rl.unpriced_items, '[]'::jsonb) AS "coalesce",
            rl.floor_cost_per_portion,
            rl.cost_per_portion
           FROM recipes r
             LEFT JOIN recipe_latest rl ON rl.recipe_id = r.id
          WHERE r.kind = 'dish'::recipe_kind AND r.deleted_at IS NULL AND NOT (EXISTS ( SELECT 1
                   FROM recipe_variants rv
                  WHERE rv.recipe_id = r.id AND rv.is_active))
        )
 SELECT x.recipe_id,
    x.business_id,
    x.account_id,
    x.name,
    ch.id AS channel_id,
    ch.name AS channel_name,
    x.is_complete,
    x.required_inputs,
    x.priced_inputs,
    x.excluded_inputs,
    x.unpriced_items,
    x.floor_cost_per_portion AS cost_floor_per_portion,
    x.cost_per_portion,
    p.price AS selling_price,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL THEN round(p.price - x.cost_per_portion, 2)
            ELSE NULL::numeric
        END AS profit,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL AND p.price > 0::numeric THEN round(100.0 * (p.price - x.cost_per_portion) / p.price, 2)
            ELSE NULL::numeric
        END AS margin_pct,
        CASE
            WHEN x.is_complete AND x.cost_per_portion IS NOT NULL AND COALESCE(ch.target_margin, bs.default_target_margin) < 100::numeric THEN ceil(x.cost_per_portion / (1::numeric - COALESCE(ch.target_margin, bs.default_target_margin) / 100.0) / bs.price_rounding_to) * bs.price_rounding_to
            ELSE NULL::numeric
        END AS recommended_price,
    COALESCE(ch.target_margin, bs.default_target_margin) AS target_margin,
    bs.price_rounding_to,
    ch.commission_pct,
    x.variant_id,
    x.format_name,
    x.resolved_qty,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL AND x.cost_per_portion > 0::numeric THEN round(100.0 * (p.price - x.cost_per_portion) / x.cost_per_portion, 2)
            ELSE NULL::numeric
        END AS markup_pct
   FROM rows x
     JOIN business_settings bs ON bs.business_id = x.business_id
     LEFT JOIN channels ch ON ch.business_id = x.business_id AND ch.is_active
     LEFT JOIN LATERAL ( SELECT rp.price
           FROM recipe_prices rp
          WHERE rp.recipe_id = x.recipe_id AND (rp.channel_id IS NULL OR rp.channel_id = ch.id) AND (rp.variant_id IS NULL OR rp.variant_id = x.variant_id) AND rp.effective_from <= CURRENT_DATE
          ORDER BY (rp.variant_id IS NOT NULL) DESC, rp.effective_from DESC, rp.created_at DESC
         LIMIT 1) p ON true;

create or replace view v_costing_blockers with (security_invoker = on) as
 WITH latest AS (
         SELECT DISTINCT ON (cost_snapshots.recipe_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion
           FROM cost_snapshots
          ORDER BY cost_snapshots.recipe_id, cost_snapshots.computed_at DESC
        )
 SELECT r.account_id,
    r.business_id,
    r.id AS recipe_id,
    r.name,
    s.required_inputs,
    s.priced_inputs,
    s.excluded_inputs,
    item.value ->> 'problem'::text AS problem,
    item.value ->> 'ingredient_name'::text AS ingredient_name,
    item.value ->> 'unit'::text AS unit_code,
    item.value AS item
   FROM recipes r
     JOIN latest s ON s.recipe_id = r.id
     CROSS JOIN LATERAL jsonb_array_elements(s.unpriced_items) item(value)
  WHERE NOT s.is_complete AND r.deleted_at IS NULL;

create or replace view v_gate2_cutover with (security_invoker = on) as
 WITH latest AS (
         SELECT DISTINCT ON (cost_snapshots.recipe_id) cost_snapshots.recipe_id,
            cost_snapshots.cost_per_portion,
            cost_snapshots.computed_at,
            cost_snapshots.is_complete
           FROM cost_snapshots
          ORDER BY cost_snapshots.recipe_id, cost_snapshots.computed_at DESC
        )
 SELECT rv.account_id,
    rv.business_id,
    rv.id AS variant_id,
    r.id AS recipe_id,
    r.name AS recipe_name,
    f.name AS format_name,
    rv.costing_basis,
    r.portion_qty AS legacy_portion_qty,
    fn_variant_resolved_qty(rv.id) AS resolved_qty,
    s.cost_per_portion AS legacy_cost_per_portion,
    fn_variant_cost(rv.id) AS variant_cost,
    pk.pack_cost AS format_packaging_cost,
    fn_variant_problem(rv.id) AS problem,
    bs.overhead_enabled,
        CASE
            WHEN s.cost_per_portion IS NULL AND fn_variant_cost(rv.id) IS NULL THEN 'BOTH INCOMPLETE'::text
            WHEN s.cost_per_portion IS NULL OR fn_variant_cost(rv.id) IS NULL THEN 'ONE SIDE INCOMPLETE'::text
            WHEN abs(s.cost_per_portion - (fn_variant_cost(rv.id) - pk.pack_cost)) <= 0.000001 THEN
            CASE
                WHEN pk.pack_cost > 0::numeric THEN 'MATCH -- plus new format packaging'::text
                ELSE 'MATCH'::text
            END
            WHEN bs.overhead_enabled THEN 'DIFFERS -- OVERHEAD METHODOLOGY CHANGED BY 0023 (expected)'::text
            ELSE 'MISMATCH'::text
        END AS verdict
   FROM recipe_variants rv
     JOIN recipes r ON r.id = rv.recipe_id
     JOIN serving_formats f ON f.id = rv.format_id
     JOIN business_settings bs ON bs.business_id = rv.business_id
     LEFT JOIN latest s ON s.recipe_id = r.id
     CROSS JOIN LATERAL ( SELECT COALESCE(sum(spk.qty * fn_ingredient_usable_unit_cost(spk.packaging_item_id, rv.business_id)), 0::numeric) AS pack_cost
           FROM serving_format_packaging spk
          WHERE spk.format_id = rv.format_id AND spk.is_cost_bearing) pk
  WHERE r.deleted_at IS NULL;

alter table cost_snapshots drop column if exists seq;


-- ===================== 0036_rollback.sql =====================
-- Rollback for 0036.
--
-- DROP then CREATE, not CREATE OR REPLACE: PostgreSQL cannot remove a column
-- from a view in place, so a replace silently leaves markup_pct behind.
--
-- security_invoker is restated: a dropped view loses it, and without it the
-- view runs with the definer's rights and reads across tenants.

drop view v_price_check;

create view v_price_check with (security_invoker = on) as
 WITH recipe_latest AS (
         SELECT DISTINCT ON (cost_snapshots.recipe_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion,
            cost_snapshots.variant_id,
            cost_snapshots.resolved_qty,
            cost_snapshots.resolved_unit_id,
            cost_snapshots.basis_used,
            cost_snapshots.format_packaging_cost
           FROM cost_snapshots
          WHERE cost_snapshots.variant_id IS NULL
          ORDER BY cost_snapshots.recipe_id, cost_snapshots.computed_at DESC
        ), variant_latest AS (
         SELECT DISTINCT ON (cost_snapshots.variant_id) cost_snapshots.id,
            cost_snapshots.account_id,
            cost_snapshots.business_id,
            cost_snapshots.recipe_id,
            cost_snapshots.computed_at,
            cost_snapshots.costing_method,
            cost_snapshots.wavg_window_days,
            cost_snapshots.is_complete,
            cost_snapshots.required_inputs,
            cost_snapshots.priced_inputs,
            cost_snapshots.excluded_inputs,
            cost_snapshots.unpriced_items,
            cost_snapshots.ingredient_cost,
            cost_snapshots.packaging_cost,
            cost_snapshots.labour_cost,
            cost_snapshots.overhead_cost,
            cost_snapshots.batch_cost,
            cost_snapshots.cost_per_yield_unit,
            cost_snapshots.cost_per_portion,
            cost_snapshots.created_by,
            cost_snapshots.floor_batch_cost,
            cost_snapshots.floor_cost_per_yield_unit,
            cost_snapshots.floor_cost_per_portion,
            cost_snapshots.variant_id,
            cost_snapshots.resolved_qty,
            cost_snapshots.resolved_unit_id,
            cost_snapshots.basis_used,
            cost_snapshots.format_packaging_cost
           FROM cost_snapshots
          WHERE cost_snapshots.variant_id IS NOT NULL
          ORDER BY cost_snapshots.variant_id, cost_snapshots.computed_at DESC
        ), rows AS (
         SELECT r.id AS recipe_id,
            r.business_id,
            r.account_id,
            r.name,
            rv.id AS variant_id,
            f.name AS format_name,
            vl.resolved_qty,
            COALESCE(vl.is_complete, false) AS is_complete,
            vl.required_inputs,
            vl.priced_inputs,
            vl.excluded_inputs,
            COALESCE(vl.unpriced_items, '[]'::jsonb) AS unpriced_items,
            vl.floor_cost_per_portion,
            vl.cost_per_portion
           FROM recipes r
             JOIN recipe_variants rv ON rv.recipe_id = r.id AND rv.is_active
             JOIN serving_formats f ON f.id = rv.format_id
             LEFT JOIN variant_latest vl ON vl.variant_id = rv.id
          WHERE r.kind = 'dish'::recipe_kind AND r.deleted_at IS NULL
        UNION ALL
         SELECT r.id,
            r.business_id,
            r.account_id,
            r.name,
            NULL::uuid AS uuid,
            NULL::text AS text,
            NULL::numeric AS "numeric",
            COALESCE(rl.is_complete, false) AS "coalesce",
            rl.required_inputs,
            rl.priced_inputs,
            rl.excluded_inputs,
            COALESCE(rl.unpriced_items, '[]'::jsonb) AS "coalesce",
            rl.floor_cost_per_portion,
            rl.cost_per_portion
           FROM recipes r
             LEFT JOIN recipe_latest rl ON rl.recipe_id = r.id
          WHERE r.kind = 'dish'::recipe_kind AND r.deleted_at IS NULL AND NOT (EXISTS ( SELECT 1
                   FROM recipe_variants rv
                  WHERE rv.recipe_id = r.id AND rv.is_active))
        )
 SELECT x.recipe_id,
    x.business_id,
    x.account_id,
    x.name,
    ch.id AS channel_id,
    ch.name AS channel_name,
    x.is_complete,
    x.required_inputs,
    x.priced_inputs,
    x.excluded_inputs,
    x.unpriced_items,
    x.floor_cost_per_portion AS cost_floor_per_portion,
    x.cost_per_portion,
    p.price AS selling_price,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL THEN round(p.price - x.cost_per_portion, 2)
            ELSE NULL::numeric
        END AS profit,
        CASE
            WHEN x.is_complete AND p.price IS NOT NULL AND p.price > 0::numeric THEN round(100.0 * (p.price - x.cost_per_portion) / p.price, 2)
            ELSE NULL::numeric
        END AS margin_pct,
        CASE
            WHEN x.is_complete AND x.cost_per_portion IS NOT NULL AND COALESCE(ch.target_margin, bs.default_target_margin) < 100::numeric THEN ceil(x.cost_per_portion / (1::numeric - COALESCE(ch.target_margin, bs.default_target_margin) / 100.0) / bs.price_rounding_to) * bs.price_rounding_to
            ELSE NULL::numeric
        END AS recommended_price,
    COALESCE(ch.target_margin, bs.default_target_margin) AS target_margin,
    bs.price_rounding_to,
    ch.commission_pct,
    x.variant_id,
    x.format_name,
    x.resolved_qty
   FROM rows x
     JOIN business_settings bs ON bs.business_id = x.business_id
     LEFT JOIN channels ch ON ch.business_id = x.business_id AND ch.is_active
     LEFT JOIN LATERAL ( SELECT rp.price
           FROM recipe_prices rp
          WHERE rp.recipe_id = x.recipe_id AND (rp.channel_id IS NULL OR rp.channel_id = ch.id) AND (rp.variant_id IS NULL OR rp.variant_id = x.variant_id) AND rp.effective_from <= CURRENT_DATE
          ORDER BY (rp.variant_id IS NOT NULL) DESC, rp.effective_from DESC, rp.created_at DESC
         LIMIT 1) p ON true;

-- Restored EXACTLY as the baseline had them. Dropping the view discards its
-- grants. The write privileges are inert -- the view is not auto-updatable --
-- but a rollback must not quietly change the security posture either way.
grant select, insert, update, delete on v_price_check to authenticated;


-- ===================== 0035_rollback.sql =====================
drop view if exists v_purchase_summary;

-- ===================== 0034_rollback.sql =====================
-- Rollback for 0034. Restores the pre-0034 blending behaviour and the 21-column
-- view exactly as 0033 created it. Drop order matters: the view reads the basis
-- function, and the function returns the composite type.

-- Restored verbatim from 0012_gate1_authorization_hardening.sql, the migration
-- that last defined it, so the rollback reproduces the original definition
-- byte for byte and a definition fingerprint matches the pre-0034 baseline.
create or replace function fn_ingredient_unit_cost(
  p_ingredient_id uuid,
  p_business_id   uuid,
  p_as_of         date default current_date
)
returns numeric
language plpgsql stable security definer set search_path = public
as $$
declare
  v_account_id uuid;
  v_ing_acct   uuid;
  v_window     integer;
  v_cost       numeric;
begin
  select account_id, wavg_window_days into v_account_id, v_window
  from business_settings where business_id = p_business_id;

  if v_account_id is null then
    return null;                                  -- unknown business
  end if;

  perform fn_require_cost_access(v_account_id);   -- AUTHORIZATION

  -- The ingredient must belong to the same account as the business.
  -- This blocks the mix-and-match parameter attack.
  select account_id into v_ing_acct from ingredients where id = p_ingredient_id;
  if v_ing_acct is distinct from v_account_id then
    raise exception 'Ingredient does not belong to this account'
      using errcode = '42501';
  end if;

  select sum(amount) / nullif(sum(qty_base), 0) into v_cost
  from ingredient_prices
  where ingredient_id = p_ingredient_id
    and account_id    = v_account_id
    and reversed_at is null
    and effective_date <= p_as_of
    and effective_date >  p_as_of - (v_window || ' days')::interval;

  if v_cost is null then
    select unit_cost into v_cost
    from ingredient_prices
    where ingredient_id = p_ingredient_id
      and account_id    = v_account_id
      and reversed_at is null
      and effective_date <= p_as_of
    order by effective_date desc, created_at desc
    limit 1;
  end if;

  return v_cost;   -- NULL still means not entered. Never zero.
end;
$$;

drop view if exists v_recipe_line_costs;

create view v_recipe_line_costs with (security_invoker = on) as
select
  rl.id as line_id, rl.recipe_id, rl.account_id, r.business_id,
  rl.ingredient_id, rl.sub_recipe_id,
  coalesce(i.name, sr.name) as item_name, i.kind as item_kind,
  rl.is_cost_bearing, rl.exclusion_reason,
  rl.qty as recipe_qty, u.code as recipe_unit, bu.code as base_unit,
  fn_resolve_qty_to_base(rl.ingredient_id, rl.qty, rl.unit_id) as base_qty,
  fn_ingredient_usable_unit_cost(rl.ingredient_id, r.business_id) as unit_cost,
  case when rl.is_cost_bearing then
    fn_resolve_qty_to_base(rl.ingredient_id, rl.qty, rl.unit_id)
      * fn_ingredient_usable_unit_cost(rl.ingredient_id, r.business_id)
  end as line_cost,
  case when w.qty_base > 0 then w.qty_base       else l.qty_base       end as purchase_qty_base,
  case when w.qty_base > 0 then w.amount         else l.amount         end as purchase_amount,
  case when w.qty_base > 0 then w.last_date      else l.effective_date end as purchase_date,
  case when w.qty_base > 0 then w.purchase_count
       when l.qty_base is not null then 1 else 0 end                       as purchase_count,
  case
    when not rl.is_cost_bearing                                              then 'excluded'
    when rl.sub_recipe_id is not null                                        then 'sub_recipe'
    when fn_resolve_qty_to_base(rl.ingredient_id, rl.qty, rl.unit_id) is null then 'missing_conversion'
    when fn_ingredient_usable_unit_cost(rl.ingredient_id, r.business_id) is null then 'missing_price'
    else                                                                          'ok'
  end as problem
from recipe_lines rl
join recipes r on r.id = rl.recipe_id and r.deleted_at is null
left join ingredients i on i.id = rl.ingredient_id
left join recipes sr on sr.id = rl.sub_recipe_id
left join units u on u.id = rl.unit_id
left join units bu on bu.id = i.base_unit_id
left join business_settings bs on bs.business_id = r.business_id
left join lateral (
  select sum(ip.qty_base) as qty_base, sum(ip.amount) as amount,
         max(ip.effective_date) as last_date, count(*)::int as purchase_count
    from ingredient_prices ip
   where ip.ingredient_id = rl.ingredient_id and ip.account_id = r.account_id
     and ip.reversed_at is null and ip.effective_date <= current_date
     and ip.effective_date > current_date - (bs.wavg_window_days || ' days')::interval
) w on true
left join lateral (
  select ip.qty_base, ip.amount, ip.effective_date
    from ingredient_prices ip
   where ip.ingredient_id = rl.ingredient_id and ip.account_id = r.account_id
     and ip.reversed_at is null and ip.effective_date <= current_date
   order by ip.effective_date desc, ip.created_at desc limit 1
) l on true;

grant select on v_recipe_line_costs to authenticated;

drop function if exists fn_ingredient_cost_basis(uuid, uuid, date);
drop type if exists ingredient_cost_basis;


-- ---------------------------------------------------------------------------
-- Final assertion: we must be back at the 0033 catalogue we started from.
-- ---------------------------------------------------------------------------
do $$
declare v_fp text; v_ahead text;
begin
  select md5(string_agg(s,',' order by s)) into v_fp
    from (select replace(p.oid::regprocedure::text,' ','') as s from pg_proc p
           where p.pronamespace='public'::regnamespace and p.proname like 'fn\_%') z;
  if v_fp <> '26a45d7d98026721366ec58a66cb6d1b' then
    raise exception 'ROLLBACK INCOMPLETE: function catalogue is %, expected the 0033 fingerprint 26a45d7d98026721366ec58a66cb6d1b', v_fp;
  end if;
  select string_agg(o,', ') into v_ahead from (
    select 'order_lines.business_id' as o where exists(select 1 from information_schema.columns where table_name='order_lines' and column_name='business_id')
    union all select 'orders.order_discount' where exists(select 1 from information_schema.columns where table_name='orders' and column_name='order_discount')
    union all select 'cost_snapshots.seq' where exists(select 1 from information_schema.columns where table_name='cost_snapshots' and column_name='seq')
    union all select 'v_sale_lines' where exists(select 1 from pg_views where schemaname='public' and viewname='v_sale_lines')
    union all select 'v_purchase_summary' where exists(select 1 from pg_views where schemaname='public' and viewname='v_purchase_summary')
  ) x;
  if v_ahead is not null then
    raise exception 'ROLLBACK INCOMPLETE: still present: %', v_ahead;
  end if;
  if (select count(*) from pg_policies where schemaname='public') <> 116 then
    raise exception 'ROLLBACK FAILED: policy count is %, expected 116',
      (select count(*) from pg_policies where schemaname='public');
  end if;
  raise notice 'ROLLBACK OK: back at the 0033 catalogue, 116 policies, auth.users untouched.';
end
$$;

commit;
